(function(a){function b(){a(".reuters-nav-menu, .section-nav, .section").removeClass("active");a(".reuters-search-button").toggleClass("active");a(".section-nav").addClass("header-main-large");a("body").hasClass("sec-search")?a("body").hasClass("sec-search")&&a(".search-nav, #searchForm").addClass("active"):(a(".header-pane-main").fadeOut(100,function(){a(".header-pane-search").fadeIn(200)}),a(".search-nav, #searchForm").addClass("active"),a(".header-pane-main, .header-pane-search").toggleClass("active"),
a(".header-main").css("position","relative"));a(".section-nav").css("padding-top","0");a("#searchfield").focus();a("html, body").scrollTop(0)}a(".reuters-nav-menu").on("click",function(){a(".section-nav").removeClass("header-main-large");a(".header-pane-menu, .header-pane-main, .reuters-nav-menu, .section-nav").toggleClass("active");a(".header-pane-main").fadeOut(200,function(){a(".header-pane-menu").fadeIn(200)});a("body").hasClass("sec-search")&&a(".search-nav").hasClass("active")?(a(".search-nav").toggleClass("active"),
a(".search-nav").fadeOut(200)):a(".reuters-search-button, .search-nav").removeClass("active");a("body").hasClass("sec-search")||a(".header-main").css("position","relative");a(".section-nav").css("padding-top","0");a("html, body").scrollTop(0)});a(".reuters-search-button").on("click",b);a(".sub-section-button").on("click",function(c){a(c.currentTarget).parent(".section").toggleClass("active")});a(".header-pane-search .pane-ico-close, .header-pane-menu .pane-ico-close").on("click",function(){a(".header-main").css("position",
"fixed");a(".section-nav").css("padding-top","");a(".header-pane-main").addClass("active");var c=a(".reuters-nav-menu, .section-nav, .search-nav, .reuters-search-button, #searchForm, .header-pane-search, .header-pane-menu");a(".header-pane-search").hasClass("active")?a(".header-pane-search").fadeOut(100,function(){a(".header-pane-main").fadeIn(200);c.removeClass("active");a(".section-nav").removeClass("header-main-large")}):a(".header-pane-menu").hasClass("active")&&!a("body").hasClass("sec-search")?
a(".header-pane-menu").fadeOut(100,function(){a(".header-pane-main").fadeIn(500);c.removeClass("active");a(".section-nav").removeClass("header-main-large")}):a("body").hasClass("sec-search")&&!a(".search-nav").hasClass("active")&&(a(".header-pane-menu").fadeOut(100,function(){a(".header-pane-main").fadeIn(500);a(".reuters-nav-menu, .section-nav, .reuters-search-button, .header-pane-search, .header-pane-menu").removeClass("active");a(".section-nav").removeClass("header-main-large")}),a("body").hasClass("sec-search")||
a(".header-main").css("position","relative"),a(".search-nav").fadeIn(200),a(".search-nav, #searchForm").addClass("active"),a(".section-nav").css("padding-top","0"))});a(".mini-back-to-top").on("click",function(){a("html, body").animate({scrollTop:0},300)});a("body").hasClass("sec-search")&&(b(),a("#searchfield").focus());(function(){a(".section-nav .section .heading a:contains('Video')").each(function(){a(this).append('<span class="ico-video"></span>')});a(".section-nav .section .heading a:contains('Pictures')").each(function(){a(this).append('<span class="ico-picture"></span>')})})()})(jQuery);
$(window).scroll(function(){var a=$(".header-main"),b=$(window).scrollTop(),c=$(".reuters-nav-buttons"),d=$(".header-mini-buttons");$(".mini-back-to-top");$(".header-mini-pipe");$(".mini-share");var e=$(".header-pane-search.active"),f=$(".header-pane-menu.active");b>=50&&!$("body").hasClass("sec-search")&&e.length==0&&f.length==0?c.fadeOut(200).promise().done(function(){d.fadeIn(200);a.css("height","36px");a.addClass("header-mini")}):(d.fadeOut(200).promise().done(function(){c.fadeIn(200);a.removeClass("header-mini")}),
a.css("height","54px"))});var stringSplicer=function(a,b,c,d){b.innerHTML=a.length>c?a.substring(0,c)+d:a},littleHeaderCheck=function(a){if(a.text()===a.text().toUpperCase())return true},heroCaptionsHash={};
$(document).ready(function(){if($(".caption-info").length>0&&$(".caption-desc").length>0){var a=$(".caption-info");$.each(a,function(a,b){heroCaptionsHash[a]=b.querySelector(".caption-desc").innerHTML.trim();moreButton=this.querySelector(".more-icon");maxLength=Math.round($(window).width()*0.15);stringSplicer(heroCaptionsHash[a],this.querySelector(".caption-desc"),maxLength,"...");heroCaptionsHash[a].length>maxLength?moreButton.onclick=function(){caption=this.parentNode.parentNode.querySelector(".caption-desc");
heroCaptionsHash[a]!=caption.innerHTML.trim()?(caption.innerHTML=heroCaptionsHash[a],this.innerHTML="-"):(caption.innerHTML=caption.innerHTML.substring(0,maxLength)+"...",this.innerHTML="+")}:$(moreButton).hide()})}var a=$(".transcript-button"),b=$(".more-icon");a.on("click",function(){b.text()=="+"?($(".current-slide-transcript").show(),b.text("-")):($(".current-slide-transcript").hide(),b.text("+"))})});var objectResizer=function(a,b,c){a.css({width:b,height:c})};