var Reuters=Reuters||{},registerNamespace=function(a){for(var a=a.split("."),b=window,c=0;c<a.length;c++)typeof b[a[c]]=="undefined"&&(b[a[c]]={}),b=b[a[c]]};Reuters.namespace=function(){var a=arguments,b=null,c,d,e;for(c=0;c<a.length;c+=1){e=(""+a[c]).split(".");b=Reuters;for(d=e[0]=="Reuters"?1:0;d<e.length;d+=1)b[e[d]]=b[e[d]]||{},b=b[e[d]]}return b};
Reuters.utils={addLoadEvent:function(a,b){if(typeof a!="function")try{console.debug("function called addLoadEvent with a non-function param")}catch(c){}else{var d=window.onload;window.onload=typeof window.onload!="function"?b!==void 0?function(){a.call(b)}:a:function(){d();b!==void 0?a.call(b):a()}}},replaceContent:function(a,b,c,d){(new Reuters.utils._contentReplacer(a,b,c,d)).update()},_contentReplacer:function(a,b,c,d){this.elementId=a;this.url=b;this.reloadCallbackFunc=d;this.interval=c?c:null;
this.success=function(b){if(b.responseText!==void 0&&b.responseText!=null&&b.responseText.indexOf("No Data")<0){var b=b.responseText,c=document.getElementById(a),d=document.createElement(c.tagName);d.innerHTML=b;if(c.innerHTML!=d.innerHTML)c.parentNode.replaceChild(d,c),d.id=a,this.reloadCallbackFunc&&typeof this.reloadCallbackFunc=="function"&&this.reloadCallbackFunc()}if(this.interval!=null)try{setTimeout(this.update.bind(this),this.interval)}catch(g){trace("Somebody tell Mike about this: "+g)}};
this.failure=function(){};this.update=function(){YAHOO.util.Connect.asyncRequest("GET",this.url,this)}},loadScript:function(a,b){var c=document.getElementById(a),d=document.getElementsByTagName("head")[0];c!=null&&d.removeChild&&d.removeChild(c);if(document.createElement)c=document.createElement("script"),c.id=a,c.setAttribute("type","text/javascript"),c.setAttribute("src",Reuters.utils.convertStaticUrl(b)),c.setAttribute("charset","UTF-8");d.appendChild(c)},loadStylesheet:function(a,b){var c=document.getElementById(a),
d=document.getElementsByTagName("head")[0];c!=null&&d.removeChild&&d.removeChild(c);if(document.createElement)c=document.createElement("link"),c.id=a,c.setAttribute("rel","stylesheet"),c.setAttribute("href",Reuters.utils.convertStaticUrl(b));d.appendChild(c)},writeScript:function(a){document.write('<script src="'+Reuters.utils.convertStaticUrl(a)+'" type="text/javascript"><\/script>')},writeStylesheet:function(a){document.write('<link href="'+Reuters.utils.convertStaticUrl(a)+'" rel="stylesheet" />')},
convertStaticUrl:function(a){try{if(!parallelMediaHosts||parallelMediaHosts===null||typeof parallelMediaHosts==="undefined")return a;var b=parallelMediaHosts;if(a.indexOf("/resources")==0&&b instanceof Array&&b.length>0){var c=a.lastIndexOf("/"),d=a.toLowerCase().substring(c+1),e=d.lastIndexOf(".");e>0&&(d=d.substring(0,e));var f=d.lastIndexOf("-min");f>0&&(d=d.substring(0,f));var h=d.charCodeAt(d.length-1)%b.length;return"http://"+b[h]+a}}catch(g){console.debug("convert static url error ! "+g),console.debug(a),
console.debug(typeof a)}return a},localStorageSupportFlag:true,checkLocalStorageSupport:function(){if(JSON&&localStorage)try{return localStorage.setItem("test",1),localStorage.removeItem("test"),true}catch(a){}return false},setToLocalStorage:function(a,b){if(JSON&&localStorage&&Reuters.utils.localStorageSupportFlag){var c=JSON.stringify(b);localStorage.setItem(a,c)}},getFromLocalStorage:function(a){var b="";JSON&&localStorage&&Reuters.utils.localStorageSupportFlag&&(b=localStorage.getItem(a),b!==
null&&(b=JSON.parse(b)));return b},removeFromLocalStorage:function(a){localStorage&&Reuters.utils.localStorageSupportFlag&&localStorage.removeItem(a)},clearLocalStorage:function(){localStorage&&Reuters.utils.localStorageSupportFlag&&localStorage.clear()},isArticleLink:function(a){return Reuters.utils.getArticleId(a)!=""},getArticleId:function(a){var b="",c=/\/article(\/[^\\\/]*)*([\/|\\-])id([^\\?]*)(\\?(.*))?\s*$/ig;a&&(a=c.exec(a))&&a.length>=4&&(b=a[3]);return b},getArticleProps:function(){var a=
$("meta[name=win-tracking-article-id]").attr("content"),b=$("meta[name=win-tracking-article-title]").attr("content"),c=$("meta[name=win-tracking-article-author]").attr("content"),d=$("meta[name=win-tracking-article-publishDate]").attr("content"),e=$("meta[name=win-tracking-section-name]").attr("content"),f=$("meta[name=win-tracking-article-type]").attr("content");return{"Article ID":a,"Article Title":b,Author:c,"Date Published":d,"Section Name":e,"Article Type":f,"Ad Insertion":"TODO"}},getSlideshowProps:function(){var a=
$("meta[name=win-tracking-slideshow-title]").attr("content"),b=$("meta[name=win-tracking-section-name]").attr("content");return{"Slideshow Title":a,"Slideshow Topic":"","Section Name":b}},getSlideshowNavigation:function(a,b,c){var d="right";b==0?a!=b+1&&(d="left"):b==c-1?a!=0&&(d="left"):b-1&&(d="left");return d},getRightNowModuleType:function(){var a=function(){var a="";$("#topStory .photo .videoOverlay").length>0?a="Right Now Video":$("#topStory .photo .slideshowOverlay").length>0?a="Right Now Sldeshow":
$("#topStory .photo").length>0&&(a="Right Now Picture");return a},b=function(){var a="";$("#topStory .top-story-heading a").text()!==""&&(a="Headline");return a},c=function(){var a="";if($("#topStory .top-story-content li").length>0){var b=$("#topStory .top-story-content li").length+1;for(i=1;i<b;i++)a=a+"Related"+i,i<b-1&&(a+=":")}return a},d="";$("#topStory").hasClass("curationModule")&&(a()&&(d=a()),b()&&(d=d?d+":"+b():b()),c()&&(d=d?d+":"+c():c()));return d},getDeviceName:function(){var a="";
Reuters.utils.md&&(a=Reuters.utils.md.mobile()!=null?Reuters.utils.md.mobile():"unknown");return a},getDeviceType:function(){var a="";Reuters.utils.md&&(a=Reuters.utils.md.phone()!=null?"smartphone":Reuters.utils.md.tablet()!=null?"tablet":"unknown");return a},getOsVersion:function(){var a="",b="";if(Reuters.utils.md){a=Reuters.utils.md.os()?Reuters.utils.md.os():Reuters.utils.md.userAgent();if(a==="AndroidOS"||a==="BlackBerryOS"||a==="SymbianOS"||a==="JavaOS"||a==="BREWOS")a=a.substring(0,a.length-
2);else if(a==="WindowsPhoneOS"||a==="WindowsMobileOS")a="Windows Phone";(b=Reuters.utils.md.version(a))&&(a+=b)}return a},getDeviceOrientation:function(){var a="";console.log("window.orientation="+window.orientation);typeof window.orientation!="undefined"&&(a=Math.abs(window.orientation)===90?"Landscape":"Portrait");return a}};if(MobileDetect)Reuters.utils.md=new MobileDetect(window.navigator.userAgent);Reuters.utils.localStorageSupportFlag=Reuters.utils.checkLocalStorageSupport();