(function(){function B(a){var b=document.createElement("script"),c="//",c=window.location.search&&-1<window.location.search.indexOf("tpd_test=1")?c+"beta-s.206ads.com":c+"s.206ads.com";b.src=c+"/js/data/"+a+".js?r="+Math.random();b.type="text/javascript";document.getElementsByTagName("head")[0].appendChild(b);window.twoOhSixLoaded=!0}var m=window.twoOhSix={},q=[],d={},w=!1,t=!1,x=15E3,C=(new Date).getTime(),y=document.URL,h={domReady:function(a){"interactive"===document.readyState||"complete"===document.readyState?
a():document.addEventListener?(document.addEventListener("DOMContentLoaded",a,!1),window.addEventListener("load",a,!1)):document.onreadystatechange=function(){"interactive"!==document.readyState&&"complete"!==document.readyState||a()}},getAdUnitById:function(a){var b=h.getAdUnits();if("2.0"===d.version)for(var c=0;c<b.length;c++){if(b[c].getAttribute("data-tpd-id")===a||b[c].getAttribute("data-ad-id")===a)return b[c]}else return document.getElementById(a)},getAdUnits:function(){return h.getElementsByClassName("2.0"===
d.version?"tpd-box":"ad gpt")},getAdUnitsById:function(a){var b=[],c=h.getAdUnits();if("2.0"===d.version)for(var e=0;e<c.length;e++)c[e].getAttribute("data-tpd-id")!==a&&c[e].getAttribute("data-ad-id")!==a||b.push(c[e]);else(a=document.getElementById(a))&&null!==a&&"undefined"!==typeof a&&b.push(a);return b},getBrowserHeight:function(){var a=window,b=document.documentElement,c=document.getElementsByTagName("body")[0];return a.innerHeight||b.clientHeight||c.clientHeight},getBrowserWidth:function(){var a=
window,b=document.documentElement,c=document.getElementsByTagName("body")[0];return a.innerWidth||b.clientWidth||c.clientWidth},getElementsByClassName:function(a){if(document.getElementsByClassName)return document.getElementsByClassName(a);var b=[],c=document.getElementsByTagName("div"),e=c.length;a=new RegExp("(^|\\s)"+a+"(\\s|$)");var d,g;for(g=d=0;d<e;d++)a.test(c[d].className)&&(b[g]=c[d],g++);return b},getParameterByName:function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=(new RegExp("[\\?&]"+
a+"=([^&#]*)")).exec(location.search);return null===a?"":decodeURIComponent(decodeURIComponent(a[1].replace(/\+/g," ")))},getStyleProperty:function(a,b){if(window.getComputedStyle)return window.getComputedStyle(a,null).getPropertyValue(b);if(a.currentStyle)return a.currentStyle[b]},getUUID:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)})},hasClass:function(a,b){return 0<=a.getAttribute("class").indexOf(b)},
inCookie:function(a){return-1<document.cookie.indexOf(a)},isAdExpired:function(a){var b=a.getAttribute("data-tpd-end");if("undefined"!==typeof b){var c=new Date;h.isElementInViewport(a)&&("true"===a.getAttribute("data-tpd-viewed")?parseInt(b)<c.getTime()-x&&m.refreshAds([a]):a.setAttribute("data-tpd-viewed","true"))}},isElementInViewport:function(a){for(var b=a.offsetTop,c=a.offsetLeft,d=a.offsetWidth,f=a.offsetHeight;a.offsetParent;)a=a.offsetParent,b+=a.offsetTop,c+=a.offsetLeft;return b<window.pageYOffset+
window.innerHeight&&c<window.pageXOffset+window.innerWidth&&b+f>window.pageYOffset&&c+d>window.pageXOffset},isVisible:function(a){a=h.getStyleProperty(a,"display");return"block"===a||"inline-block"===a},showMessage:function(a){if(w){var b=(new Date).getTime();console.log(b-C+" ms - "+a)}}},D={init:function(){var a=document.createElement("script");a.type="text/javascript";a.src="//c.amazon-adsystem.com/aax2/amzn_ads.js";document.getElementsByTagName("head")[0].appendChild(a);window.amznAdsResponse=
function(){var a=a||{};a.cmd=a.cmd||[];try{amznads.setTargetingForGPTAsync("amznslots")}catch(b){}};try{amznads.getAdsCallback("3345",window.amznAdsResponse,2E3)}catch(b){}}},E={init:function(){if(d.adsnative){var a=document.createElement("script");a.setAttribute("type","text/javascript");a.setAttribute("src","//static.adsnative.com/static/js/render.v1.js");document.body.appendChild(a)}}},F={init:function(){if(d.adsupply.guid){var a=document.createElement("script");a.type="text/javascript";a.async=
!0;a.src="//cdn.engine.4dsply.com/Scripts/infinity.js.aspx?guid="+d.adsupply.guid;a.id="infinity";a.setAttribute("data-guid",d.adsupply.guid);a.setAttribute("data-version","async");var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}}},G={init:function(){if(d.adsense.channelId&&400>window.screen.width){var a=document.createElement("script");a.type="text/javascript";a.src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js";document.getElementsByTagName("head")[0].appendChild(a);
(adsbygoogle=window.adsbygoogle||[]).push({google_ad_client:"ca-pub-2322157869609449",enable_page_level_ads:!0,inserts:{google_ad_channel:d.adsense.channelId}})}}},H={init:function(){(function(a,b,c,e,f,g,l){a.GoogleAnalyticsObject=f;a[f]=a[f]||function(){(a[f].q=a[f].q||[]).push(arguments)};a[f].l=1*new Date;g=b.createElement(c);l=b.getElementsByTagName(c)[0];g.async=1;g.src=e;l.parentNode.insertBefore(g,l);ga("create",d.ga,"auto",{name:"206tracker"});ga("206tracker.require","displayfeatures");ga("206tracker.send",
"pageview")})(window,document,"script","//www.google-analytics.com/analytics.js","ga")}},I={init:function(){for(var a=0;a<d.connatix.placements.length;a++){var b=d.connatix.placements[a],c=h.getAdUnitById(b.div);if("undefined"!==typeof c&&null!==c&&h.isVisible(c)){var e=document.createElement("script");e.type="text/javascript";e.src="//cdn.connatix.com/min/connatix.renderer.infeed.min.js";e.setAttribute("data-connatix-token",b.id);b.wait&&1===b.wait&&(e.setAttribute("data-connatix-waitforpath","data-connatix-waitforpath"),
e.setAttribute("data-connatix-waitforposition","data-connatix-waitforposition"),e.setAttribute("async","async"));b.append&&1===b.append?c.appendChild(e):document.getElementsByTagName("head")[0].appendChild(e)}}}},J={init:function(){var a=window,b;a:{var c,d,f=document.cookie.split(";");for(b=0;b<f.length;b++)if(c=f[b].substr(0,f[b].indexOf("=")),d=f[b].substr(f[b].indexOf("=")+1),c=c.replace(/^\s+|\s+$/g,""),"crtg_rta"==c){b=unescape(d);break a}b=""}a.crtg_content=b;b=Math.floor(99999999999*Math.random());
a=location.protocol+"//rtax.criteo.com/delivery/rta/rta.js?netId="+escape("4808");a+="&cookieName="+escape("crtg_rta");a=a+("&rnd="+b)+("&varName="+escape("crtg_content"));b=document.createElement("script");b.type="text/javascript";b.src=a;b.async=!0;0<document.getElementsByTagName("head").length?document.getElementsByTagName("head")[0].appendChild(b):0<document.getElementsByTagName("body").length&&document.getElementsByTagName("body")[0].appendChild(b);h.showMessage("Criteo Called: "+a)}},n={ready:!1,
init:function(){window.googletag=window.googletag||{};window.googletag.cmd=window.googletag.cmd||[];if("undefined"===typeof googletag||"undefined"!==typeof googletag&&"undefined"===typeof googletag.version){var a=document.createElement("script");a.type="text/javascript";a.src="//www.googletagservices.com/tag/js/gpt.js";a.async=!0;document.getElementsByTagName("head")[0].appendChild(a)}if("undefined"!==typeof q&&0<q.length)for(a=0;a<q.length;a++)(function(a){window.googletag.cmd.push(function(){googletag.pubads().setTargeting(a[0],
a[1])})})(q[a]);"undefined"!==typeof window.twoOhSixPageUrl&&null!==window.twoOhSixPageUrl&&("/"===window.twoOhSixPageUrl.charAt(0)?window.googletag.cmd.push(function(){googletag.pubads().set("page_url",document.location.protocol+"//"+window.location.host+window.twoOhSixPageUrl)}):window.googletag.cmd.push(function(){googletag.pubads().set("page_url",window.twoOhSixPageUrl)}));window.googletag.cmd.push(function(){googletag.pubads().collapseEmptyDivs();(void 0===d.sra||void 0!==d.sra&&1===parseInt(d.sra))&&
googletag.pubads().enableSingleRequest();googletag.pubads().addEventListener("slotRenderEnded",function(a){var b=a.slot.getSlotElementId(),f=a.slot.getAdUnitPath(),g=document.getElementById(b),l=(new Date).getTime(),z=l-parseInt(g.getAttribute("data-tpd-start"));g.setAttribute("data-tpd-loaded","true");g.setAttribute("data-tpd-end",l);a.isEmpty||(l=a.size[1],g.setAttribute("data-tpd-width",a.size[0]),g.setAttribute("data-tpd-height",l));if(parent===self){null!==g.getAttribute("data-tpd-refresh")&&
"true"===g.getAttribute("data-tpd-refresh")&&(g.setAttribute("data-tpd-viewed","false"),d.rf&&0<parseInt(d.rf)&&(x=d.rf),setInterval(function(){h.isAdExpired(b)},1E3));if(a.isEmpty)g.setAttribute("data-tpd-empty","true");else if(g.setAttribute("data-tpd-empty","false"),"fixed"===h.getStyleProperty(g,"position")&&"320"===g.getAttribute("data-tpd-width")&&"50"===g.getAttribute("data-tpd-height")){l=document.createElement("a");l.setAttribute("href","#");l.setAttribute("class","tpd-close-btn");l.onclick=
function(){g.parentNode.removeChild(g);document.cookie="tpd-close-"+b+"=true;path=/";return!1};var p=document.createElement("img");p.setAttribute("src","http://s.206ads.com/images/closeButton.png");l.appendChild(p);g.appendChild(l)}d.logging&&1===parseInt(d.logging)&&window._LTracker.push({type:"adResponse",siteId:window.twoOhSixId,url:top.document.URL,divId:b,slotId:f,blank:a.isEmpty?"true":"false",duration:z,userAgent:navigator.userAgent});h.showMessage("The Publisher Desk: Ad response complete for: "+
b);a.isEmpty&&h.showMessage("The Publisher Desk: WARNING: Ad response for "+b+" is empty");h.showMessage("The Publisher Desk: Ad response was "+z+" milliseconds for: "+b)}});"undefined"===typeof window.crtg_content&&(window.crtg_content="");var a=window.crtg_content.split(";");a.pop();0<a.length?function(a){window.googletag.cmd.push(function(){googletag.pubads().setTargeting("crtRTA",a)})}(a):h.showMessage("Criteo crtg_content variable is empty");googletag.enableServices()});n.ready=!0},defineAds:function(){for(var a=
d.gpt.slots,b=0;b<a.length;b++){var c=a[b],e=[];c.div&&""!==c.div&&(e=h.getAdUnitsById(c.div));c.label&&""!==c.label&&0===e.length&&(e=h.getAdUnitsById(c.label));for(var f=0;f<e.length;f++){var g=e[f];null!==g&&"undefined"!==typeof g&&h.isVisible(g)&&!h.inCookie("tpd-close-"+c.div)&&("2.0"===d.version&&(adId=g.getAttribute("data-tpd-id"),g.setAttribute("id",adId+"-"+(Date.now()+1E3*b+Math.floor(100*Math.random())))),function(a,b){window.googletag.cmd.push(function(){var c=googletag.defineSlot(a.id,
a.sz,b.id).addService(googletag.pubads());a.label&&c.setTargeting("position",[a.label]);a.sticky&&1===parseInt(a.sticky)&&c.setTargeting("unit",["sticky"]);a.st&&c.setTargeting("strnativekey",a.st);if(d.pbjs&&1===parseInt(d.pbjs)){var e=pbjs.getAdserverTargeting();if(e[a.div]&&"undefined"!==typeof e[a.div])for(var f in e[a.div])c.setTargeting(f,e[a.div][f])}if("undefined"!==typeof window.progKeyValueMap){var g=a.id.replace(/^\/[0-9]+\//,""),h=null;for(f in window.progKeyValueMap)if(f.split("@")[0]===
g)if(e=window.progKeyValueMap[f].split(";"),null===h)h=f;else{var m=window.progKeyValueMap[h].split(";");parseFloat(e[3])>parseFloat(m[3])&&(h=f)}null!==h&&(e=window.progKeyValueMap[h].split(";"),c.pubads().setTargeting(e[4],e[5]),c.pubads().setTargeting(e[0],e[1]),c.pubads().setTargeting(e[2],e[3]))}})}(c,g),parent===self&&(1===c.rf&&g.setAttribute("data-tpd-refresh","true"),h.showMessage("The Publisher Desk: Ad slot "+c.id+" defined for: "+c.div)))}}},displayAds:function(){for(var a=d.gpt.slots,
b=[],c=0;c<a.length;c++){var e=a[c],f=[];e.div&&""!==e.div&&(f=h.getAdUnitsById(e.div));e.label&&""!==e.label&&0===f.length&&(f=h.getAdUnitsById(e.label));for(e=0;e<f.length;e++){var g=f[e];null!==g&&"undefined"!==typeof g&&h.isVisible(g)&&function(a){window.googletag.cmd.push(function(){window.googletag.display(a.id);b.push({divId:a.getAttribute("data-tpd-id")||a.getAttribute("data-ad-id")});d.ga&&"undefined"!==typeof ga&&ga("206tracker.send","event","ad","called",a.id);parent===self&&(a.setAttribute("data-tpd-start",
(new Date).getTime()),h.showMessage("The Publisher Desk: Ad call has been made for: "+a.id))})}(g)}}window.pm_exec=1;d.logging&&1===parseInt(d.logging)&&window._LTracker.push({type:"request",url:top.document.URL,adsCalled:b,screen:{width:h.getBrowserWidth(),height:h.getBrowserHeight()},userAgent:navigator.userAgent})}},K={init:function(){var a=document.createElement("script");a.type="text/javascript";a.async="true";a.src="//cloudfront.loggly.com/js/loggly.tracker.js";document.getElementsByTagName("head")[0].appendChild(a);
window._LTracker=window._LTracker||[];window._LTracker.push({logglyKey:"1667eaf8-f7c2-46d1-8dde-e7cf790d02b0",sendConsoleErrors:!1})}},r={loaded:!1,init:function(){r.prep();r.load()},load:function(){if(!r.loaded){var a=document.createElement("script");a.type="text/javascript";a.async="async";a.src="//widgets.outbrain.com/outbrain.js";document.getElementsByTagName("head")[0].appendChild(a);r.loaded=!0}},insert:function(){"undefined"!==typeof OBR&&OBR.extern.researchWidget()},prep:function(a){var b;
null!==a&&"undefined"!==typeof a?a instanceof Array?b=a:a instanceof Object&&(b=[a]):"2.0"===d.version?b=h.getElementsByClassName("tpd-box"):(b=[],b.push(document.getElementById("bottom_teasers")),b.push(document.getElementById("contextual-a")),b.push(document.getElementById("contextual-b")));if(b)for(a=0;a<b.length;a++){var c=b[a];if(null!==c&&"undefined"!==typeof c&&h.isVisible(c))for(var e=c.getAttribute("id")||c.getAttribute("data-tpd-id")||c.getAttribute("data-ad-id"),f=0;f<d.outbrain.placements.length;f++){var g=
d.outbrain.placements[f];if(g.div==e)for(var l=0;l<g.widgets.length;l++){var m=document.createElement("div");1===g.widgets[l].mobile?m.setAttribute("class","tpd-mobile"):m.setAttribute("class","tpd-desktop");c.appendChild(m);if(null!==m&&"undefined"!==typeof m&&h.isVisible(m)){var p=document.createElement("div");p.setAttribute("class","OUTBRAIN");p.setAttribute("data-src",document.URL);p.setAttribute("data-widget-id",g.widgets[l].widgetId);p.setAttribute("data-ob-template",g.widgets[l].template);
m.appendChild(p)}}}}}},v={gptInit:!1,init:function(){window.pbjs=window.pbjs||{};window.pbjs.que=window.pbjs.que||[];setTimeout(function(){!0!==v.gptInit&&(n.init(),n.defineAds(),n.displayAds())},1E3);(function(){var a=document.createElement("script");a.type="text/javascript";a.async="true";a.src="//acdn.adnxs.com/prebid/prebid.js";document.getElementsByTagName("head")[0].appendChild(a)})();window.pbjs.que.push(function(){for(var a=[],b=0;b<d.gpt.slots.length;b++){var c=d.gpt.slots[b],e={};e.code=
c.label||c.div;e.sizes=c.sz;e.bids=[];if(window.location.search&&-1<window.location.search.indexOf("tpd_appnexus=1")&&"askdrmanny.com"==window.twoOhSixId&&("ad-728x90-a"==c.div||"ad-300x250-a"==c.div||"ad-300x250-b"==c.div)){var f={bidder:"appnexus"};"ad-729x90-a"==c.div?f.params={placementId:5823281}:"ad-300x250-a"==c.div?f.params={placementId:5823300}:"ad-300x250-b"==c.div&&(f.params={placementId:5823309});e.bids.push(f)}c.rubcion&&(f={bidder:"rubicon"},f.params={accountId:"11250",siteId:d.rubicon,
zoneId:c.rubicon},e.bids.push(f));c.sovrn&&(f={bidder:"sovrn"},f.params={tagid:c.sovrn},e.bids.push(f));a.push(e)}0<a.length&&(window.pbjs.addAdUnits(a),window.pbjs.bidderSettings={standard:{adserverTargeting:[{key:"hb_bidder",val:function(a){return a.bidderCode}},{key:"hb_adid",val:function(a){return a.adId}},{key:"hb_pb",val:function(a){return a.pbMg}}]}},window.pbjs.requestBids({bidsBackHandler:function(a){m.prebidComplete(a)}}))})}},L={init:function(){for(var a=0;a<d.pubexchange.placements.length;a++){var b=
d.pubexchange.placements[a],c=h.getAdUnitById(b.div);if(null!==c&&"undefined"!==typeof c){var e=document.createElement("div");e.setAttribute("id",b.id);c.appendChild(e);if(document.getElementById("pubexchange-jssdk"))break;c=document.createElement("script");c.id="pubexchange-jssdk";c.async="true";c.src="//cdn.pubexchange.com/modules/partner/"+b.site;b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(c,b)}}}},M={init:function(){var a=document.createElement("img");a.setAttribute("src",
"//pixel.quantserve.com/pixel/p-dTdeRsE4NP1z8.gif");a.setAttribute("width",1);a.setAttribute("height",1);document.body.appendChild(a)}},N={init:function(){var a=document.createElement("script");a.src="//native.sharethrough.com/assets/sfp.js";document.getElementsByTagName("head")[0].appendChild(a)}},O={init:function(){if(d.swoop.domain&&"undefined"!==typeof d.swoop.domain){var a=window.document;if(!a.getElementById("swoop_sdk")){var b=a.location.protocol+"//ardrone.swoop.com/",a=a.createElement("script");
a.type="text/javascript";a.src=b+"js/spxw.js";a.id="swoop_sdk";a.setAttribute("data-domain",d.swoop.domain);a.setAttribute("data-serverbase",b);document.getElementsByTagName("head")[0].appendChild(a)}}}},u={loaded:!1,init:function(){if(!u.loaded){window._taboola=window._taboola||[];_taboola.push({article:"auto"});var a=document.createElement("script");a.async=1;a.src="//cdn.taboola.com/libtrc/bjpenn/loader.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b);for(a=0;a<
d.taboola.placements.length;a++)b=h.getAdUnitById(d.taboola.placements[a].div),u.insert(b);u.loaded=!0}},insert:function(a){var b;null!==a&&"undefined"!==typeof a&&(a instanceof Array?b=a:a instanceof Object&&(b=[a]));if(b)for(a=0;a<b.length;a++){var c=b[a];if(null!==c&&"undefined"!==typeof c&&h.isVisible(c)){var e=c.getAttribute("id")||c.getAttribute("data-tpd-id")||c.getAttribute("data-ad-id");for(a=0;a<d.taboola.placements.length;a++){var f=d.taboola.placements[a];if(f.div==e)for(var g=0;g<f.widgets.length;g++){var l=
f.widgets[g],m=document.createElement("div"),p=l.container+"-"+(Date.now()+1E3*a);m.setAttribute("id",p);c.appendChild(m);_taboola.push({mode:l.mode,container:p,placement:l.placement,target_type:l.target_type})}}_taboola.push({flush:!0})}}}},P={init:function(){for(var a=0;a<d.teads.placements.length;a++){var b=d.teads.placements[a],c=document.createElement("script");c.type="text/javascript";c.src="//as.ebz.io/api/choixPubJS.htm?pid="+b.id+"&screenLayer=1&mode=NONE&home="+b.url;document.body.appendChild(c)}}},
Q={init:function(){for(var a=0;a<d.triplelift.placements.length;a++){var b=d.triplelift.placements[a],c=h.getAdUnitById(b.div);if(null!==c&&"undefined"!==typeof c){var e=document.createElement("script");e.type="text/javascript";e.src="//ib.3lift.com/ttj?inv_code="+b.id;c.appendChild(e)}}}},R={init:function(){window.unruly=window.unruly||{};window.unruly["native"]=window.unruly["native"]||{};window.unruly["native"].siteId=parseInt(d.unruly.placementId);var a=document.createElement("script");a.src=
"//video.unrulymedia.com/native/native-loader.js";document.body.appendChild(a);h.showMessage("The Publisher Desk: Unruly inserted")}},A={init:function(){var a=["//mpp.vindicosuite.com/conv/m=1;t=21419;ts=<rnd>"],b=function(){var a="";try{if(window===top)a=document.location.href;else if(parent.window===top)var b=document.location.ancestorOrigins,a=b&&0<b.length?b[b.length-1]:document.referrer;else(b=document.location.ancestorOrigins)&&0<b.length&&(a=b[b.length-1])}catch(c){a=""}return a},c={dsd:"",
ref:"",rnd:Math.ceil(1E6*Math.random())};try{c.dsd=encodeURIComponent(b()),c.ref=encodeURIComponent(document.referrer)}catch(d){}for(b=0;b<a.length;b++){var f=a[b];for(k in c)f=f.replace("<"+k+">",c[k]);a[b]=f}setTimeout(function(){for(var b=0;b<a.length;b++)A.d(a[b])},50)},d:function(a){var b=document.createElement("script");b.type="text/javascript";b.async=!0;b.src=a;a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)}},S={init:function(){for(var a=0;a<d.yieldmo.placements.length;a++){var b=
h.getAdUnitById(d.yieldmo.placements[a].div);if(null!==b&&"undefined"!==typeof b){var c=document.createElement("div");c.setAttribute("id",d.yieldmo.placements[a].id);c.setAttribute("class","ym");b.appendChild(c);void 0===window._ym?(window._ym="",b=document.createElement("script"),b.type="text/javascript",b.async=!0,b.src="//static.yieldmo.com/ym.min.js",document.getElementsByTagName("head")[0].appendChild(b)):window._ym instanceof String||void 0===window._ym.chkPls||window._ym.chkPls()}}}},T={init:function(){for(var a=
0;a<d.zergnet.placements.length;a++){var b=d.zergnet.placements[a],c=h.getAdUnitById(b.div);if(null!==c&&"undefined"!==typeof c){var e="undefined"!==typeof b.inf?b.inf:0,f=document.createElement("div");1===e?f.setAttribute("class","zergnet-widget"):f.setAttribute("id","zergnet-widget-"+b.id);c.appendChild(f);c=document.createElement("script");c.type="text/javascript";c.async=!0;c.src=1===e?"//www.zergnet.com/zerg-inf.js?id="+b.id:"//www.zergnet.com/zerg.js?id="+b.id;b=document.getElementsByTagName("script")[0];
b.parentNode.insertBefore(c,b)}}}};m.config=function(a){d=a;"undefined"!==typeof window.twoOhSixDataVersion&&(d.version=window.twoOhSixDataVersion);window.location.search&&-1<window.location.search.indexOf("tpd_data_version")&&(a=window.location.search.match(/tpd_data_version=([^&]*)/))&&"undefined"!==typeof a&&1<a.length&&(d.version=a[1]);h.domReady(function(){if(!t){t=!0;window.twoOhSixCmd=window.twoOhSixCmd||[];if(0<window.twoOhSixCmd.length)for(var a=0;a<window.twoOhSixCmd.length;a++)window.twoOhSixCmd[a]();
window.twoOhSixCmd.push=function(a){return a()};if(parent===self){h.showMessage("The Publisher Desk: DOM Ready");if(d.css){var a=document.createElement("style"),c=d.css.replace(/\\'/g,"'");a.setAttribute("type","text/css");a.styleSheet?a.styleSheet.cssText=c:(c=document.createTextNode(c),a.appendChild(c));document.getElementsByTagName("head")[0].appendChild(a)}d.js&&(a=document.createElement("script"),c=d.js.replace(/\\'/g,"'"),a.setAttribute("type","text/javascript"),document.all&&!document.addEventListener?
a.text=c:(c=document.createTextNode(c),a.appendChild(c)),document.getElementsByTagName("head")[0].appendChild(a));d.ga&&H.init();d.logging&&1===parseInt(d.logging)&&K.init();d.criteo&&1===parseInt(d.criteo)&&J.init();d.a9&&1===parseInt(d.a9)&&D.init();d.st&&1===parseInt(d.st)&&N.init();M.init();A.init()}d.gpt&&(d.pbjs&&1===parseInt(d.pbjs)?v.init():(n.init(),n.defineAds(),n.displayAds()));parent===self&&(d.outbrain&&r.init(),d.connatix&&I.init(),d.adsnative&&E.init(),d.adsense&&G.init(),d.adsupply&&
F.init(),d.zergnet&&T.init(),d.pubexchange&&L.init(),d.swoop&&O.init(),d.taboola&&u.init(),d.teads&&P.init(),d.triplelift&&Q.init(),d.unruly&&R.init(),d.yieldmo&&S.init())}})};m.insertAds=function(a){if(t){var b=null;"undefined"!==typeof a?a instanceof Array?b=a:a instanceof Object&&(b=[a]):b=h.getAdUnits();if(null!==b&&"undefined"!==typeof b){n.ready||n.init();document.URL!==y&&(y=document.URL,window.googletag.cmd.push(function(){googletag.pubads().updateCorrelator()}));for(var c=0;c<b.length;c++){var e=
b[c];if((e.hasAttribute("data-ad-id")||e.hasAttribute("data-tpd-id"))&&!e.hasAttribute("data-tpd-start")&&h.isVisible(e))for(var f=e.getAttribute("data-ad-id")||e.getAttribute("data-tpd-id"),g=0;g<d.gpt.slots.length;g++){var l=d.gpt.slots[g];if(l.div===f||l.label===f){var q=f+"-"+(Date.now()+1E3*c+Math.floor(100*Math.random()));e.setAttribute("id",q);(function(a,b){window.googletag.cmd.push(function(){var c=googletag.defineSlot(a.id,a.sz,b).addService(googletag.pubads());a.label&&c.setTargeting("position",
[a.label]);a.sticky&&1===parseInt(a.sticky)&&c.setTargeting("slot",["sticky"]);googletag.display(b)})})(l,q);parent===self&&(e.setAttribute("data-tpd-start",(new Date).getTime()),h.showMessage("The Publisher Desk: Ad call has been made for: "+e.id))}}}}}else window.twoOhSixCmd=window.twoOhSixCmd||[],window.twoOhSixCmd.push(function(){m.insertAds(a)})};m.insertContextualAds=function(a){t?(d.outbrain&&(r.init(),r.prep(a),r.insert()),d.taboola&&(u.init(),u.insert(a))):(window.twoOhSixCmd=window.twoOhSixCmd||
[],window.twoOhSixCmd.push(function(){m.insertContextualAds(a)}))};m.insertNativeAds=function(a){if(t){var b=null;"undefined"!==typeof a?a instanceof Array?b=a:a instanceof Object&&(b=[a]):"2.0"===d.version?b=h.getElementsByClassName("tpd-box tpd-native"):(b=[],b.push(document.getElementById("native-a")),b.push(document.getElementById("native-b")),b.push(document.getElementById("native-c")),b.push(document.getElementById("native-d")),b.push(document.getElementById("ad-native-a")),b.push(document.getElementById("ad-native-b")),
b.push(document.getElementById("ad-native-c")),b.push(document.getElementById("ad-native-d")));if(null!==b&&"undefined"!==typeof b)for(var c=0;c<b.length;c++){var e=b[c];if(null!==e&&h.isVisible(e))for(var f=e.getAttribute("id")||e.getAttribute("data-ad-id"),g=0;g<d.adsnative.placements.length;g++){var l=d.adsnative.placements[g];if(l.div===f){var n=f+"-"+(Date.now()+1E3*c);e.setAttribute("id",n);e.hasAttribute("class")?e.setAttribute("class",e.getAttribute("class")+" an-container"):e.setAttribute("class",
"an-container");e.setAttribute("data-an-id",l.id);var p=new AdsNative(l.id);p.fetchAd(function(a){a&&p.displayAd(n)})}}}}else window.twoOhSixCmd=window.twoOhSixCmd||[],window.twoOhSixCmd.push(function(){m.insertNativeAds(a)})};m.refreshAds=function(a){if(t){var b=[],c=[];null!==a&&"undefined"!==typeof a?a instanceof Array?b=a:a instanceof Object&&(b=[a]):b=h.getAdUnits();for(var e=0;e<b.length;e++){var f=b[e];if(null!==f)for(var g=f.getAttribute("data-ad-id")||f.getAttribute("data-tpd-id")||f.getAttribute("id"),
l=0;l<d.gpt.slots.length;l++)if(d.gpt.slots[l].div===g){if(f.firstChild)for(;f.firstChild;)f.removeChild(f.firstChild);if(f.hasAttribute("id")){var n=f.getAttribute("id");f.setAttribute("data-tpd-id",n.replace(/\-[0-9]{10,}$/,""));f.removeAttribute("id");f.removeAttribute("data-tpd-loaded");f.removeAttribute("data-tpd-start");f.removeAttribute("data-tpd-end");f.removeAttribute("data-tpd-viewed");f.removeAttribute("style");c.push(f)}}}0<c.length&&m.insertAds(c)}else window.twoOhSixCmd=window.twoOhSixCmd||
[],window.twoOhSixCmd.push(function(){m.refreshAds(a)})};m.sendPageView=function(){d.ga&&"undefined"!==typeof ga&&ga("206tracker.send",{hitType:"pageview",page:window.location.pathname,title:document.title});"undefined"!==typeof _qevents&&_qevents.push({qacct:"p-dTdeRsE4NP1z8"})};m.getTargeting=function(){return q};m.getTargetingValue=function(a){for(var b=m.getTargeting(),c=0;c<b.length;c++)if(b[c][0]===a)return b[c][1];return null};m.pmComplete=function(){"undefined"===typeof window.pm_exec&&(n.init(),
n.defineAds(),n.displayAds(),window.pm_exec=1)};m.prebidComplete=function(a){console.log(a);v.gptInit=!0;n.init();n.defineAds();n.displayAds()};m.setTargeting=function(a,b){for(var c=0;c<q.length;c++)q[c][0]==a&&q.splice(c,1);q.push([a,b])};m.setTargetingArray=function(a){q=a};window.location.search&&-1<window.location.search.indexOf("tpd_debug=1")&&(w=!0);"undefined"===typeof window.twoOhSixId?console.log("The Publisher Desk: Fatal Error: window.twoOhSixId needs to be defined."):!0===window.twoOhSixLoaded?
console.log("The Publisher Desk: Warning: init.js has already been called on this page."):(h.showMessage("The Publisher Desk: init.js loaded"),B(window.twoOhSixId))})();
