document.write("<"+"script language=\"JavaScript\">\n");
document.write("var zflag_nid=\"2486\"; var zflag_width=\"728\"; var zflag_height=\"90\"; var zflag_sz=\"14\"; var zflag_$=\"2392843\"; \n");
document.write("<"+"/script>\n");
document.write("<"+"script language=\"JavaScript\" src=\"http://xp2.zedo.com/jsc/xp2/fo.js\"><"+"/script>");
document.write("<"+"script type=\"text/javascript\">\n");
document.write("  setTimeout(function() {\n");
document.write("    var iframe = document.createElement('iframe');\n");
document.write("    var xpr9190 = \"http\";\n");
document.write("    if (window.location.protocol == 'https:') xpr9190 += \"s\";\n");
document.write("    iframe.id = iframe.tagName+\"_\"+(Math.random() * 1000000000);\n");
document.write("    iframe.style.display = \"block\";\n");
document.write("    iframe.style.width = \"0px\";\n");
document.write("    iframe.style.height = \"0px\";\n");
document.write("    iframe.src = xpr9190 + \"://sync.rhythmxchange.com/usersync2/rmp?redir=\" + xpr9190 + \"%3A%2F%2Frtb.1rx.io%2Fcookiesync%2F1.0%2Fhtml%3FdspName%3D1rx%26userid%3D%5BRX_UUID%5D\";\n");
document.write("    if ((document.body === undefined) || (document.body == null )) {  \n");
document.write("      var iframeHtml = iframe.outerHTML || (function(n){ /**/\n");
document.write("          var div = document.createElement('div');\n");
document.write("          div.appendChild( n.cloneNode(true) );\n");
document.write("          return div.innerHTML;\n");
document.write("      })(iframe);\n");
document.write("      document.write(iframeHtml);\n");
document.write("    } else {\n");
document.write("      /**/\n");
document.write("      document.body.appendChild(iframe);\n");
document.write("    }\n");
document.write("  }, (Math.floor(Math.random() * 5)+1));\n");
document.write("<"+"/script>");
