(function(){var g=!0,i=!1,j;
function k(a){function c(){f||(f=g,e?b.f.ga=g:b.V(a))}var b=this,e=i,f=i;b.va=a.useFlashFallback===i?i:!b.sa;b.s=a.statBaseURL;b.C=a.guid||a.GUID;b.z=a.confID;b.t=a.viewableConversion;b.w=a.api&&a.api.bridge!==a.api.fallbackAPI;if(b.t){for(var d=a.viewableImpressionURL,h=[{param:"ft_creative",value:a.creativeID},{param:"ft_configuration",value:a.confID},{param:"ft_parent",value:window["ftTimestamp_"+a.pID]||""},{param:"ft_id",value:a.ftId||""},{param:"ft_custom",value:window["ftCustom_"+a.pID]||""},
{param:"ft_section",value:window["ftSection_"+a.pID]||""}],m=h.length;m--;)d=a.insertParam(d,h[m]);b.I="&"===d[d.length-1]?d.substring(0,d.length-1):d}b.b=a.viewableImpressionThreshold;b.H=0;b.Aa=i;b.G=a.viewableImpressionTime;b.F=i;b.Z=i;b.o=a.customDefinition;b.l=0;b.$=i;b.O=i;b.width=parseInt(a.width,10);b.height=parseInt(a.height,10);b.target=b.g?null:window.parent.document.getElementById(a.divID)||window.frameElement;b.k=b.D=b.visibility.m;b.A=0;b.W=(new Date).getTime();b.X=(new Date).getTime();
b.a={visible:0,r:0,hidden:0,Y:0};b.c=g;b.dispatchEvent=function(b,c){a.dispatchEvent(b,c)};if(a.fver&&a.minflashversion)this.P=!!a.fver();else{h=i;if(this.v)for(d=10;3<=d;d--)h=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+d),h=!!parseFloat(h.GetVariable("$version").match(/\b\d+\b/g).join("."));else"undefined"!=typeof navigator.plugins["Shockwave Flash"]&&(h=!!parseFloat(navigator.plugins["Shockwave Flash"].description.substring(15)));this.P=h}b.g&&(window.$sf&&window.$sf.ext?b.p=b.ta:"undefined"!==
typeof window.mozInnerScreenY?(b.S=b.ja,b.U=b.ka):b.P&&!b.L&&b.va?(b.B={},e=g,b.f={ga:i},b.i=[],window.ftPagefoldFlashListener=function(c){c=c.split("-");b.oa(c[0],parseInt(c[1],10),a)},b.p=b.pa,b.ia()):(b.d(this.event.fa),!b.Z&&b.t&&b.ma(),b.dispatchEvent("advisibility",i)));a.addEventListener("adonpage",c);a.addEventListener("backup",c)}
function l(a){var c="";this.s=a.statBaseURL;this.C=a.guid;this.z=a.confID;this.L=/fox/i.test(navigator.appVersion);c=this.g?window.document.referrer:window.parent.document.location;c=escape(String(c).substr(0,200));this.d("314",c)}
function n(){this.z=this.C=this.s="";this.ra=window!=top;this.g=i;if(this.ra)try{window.parent.document.getElementsByTagName("head")[0].appendChild(window.parent.document.createElement("script"))}catch(a){this.g=g}this.L=/fox/.test(navigator.userAgent);this.v=/MSIE/.test(navigator.userAgent);this.sa=/Safari/.test(navigator.userAgent)&&!/Chrome/.test(navigator.userAgent)}k.prototype=new n;j=k.prototype;
j.event={ea:"301",da:"302",K:"303",ca:"304",aa:"305",ba:"306",J:"307",fa:"308",za:"310",ya:"311",xa:"312"};j.visibility={h:2,n:1,m:0};j.M=[50,175,300,600,1200,3E3];
j.V=function(a){var c=this,b=this.p(),e=this.event.ca,f,d,h;"undefined"!==typeof document.hidden?(f="hidden",d="visibilitychange"):"undefined"!==typeof document.Ba?(f="mozHidden",d="mozvisibilitychange"):"undefined"!==typeof document.Ca?(f="msHidden",d="msvisibilitychange"):"undefined"!==typeof document.Ea&&(f="webkitHidden",d="webkitvisibilitychange");"undefined"===typeof f&&(h=c.g?window:window.parent);1===b&&!c.o?e=this.event.ea:0<b&&(e=this.event.da);this.d(e);this.k=this.D=this.T(b);/mobile/i.test(navigator.userAgent)===
i?this.e():!a.api||"loading"!==a.api.getState()?this.N(a,h,f,d):a.api.addEventListener("ready",function(){c.N(a,h,f,d)})};
j.e=function(){var a=this,c=(new Date).getTime(),b=c-this.W,e=c-this.X,f=this.p(),d=this.T(f);a.c&&(this.dispatchEvent("advisibility",100*f),1==f?this.a.visible+=e:0<f?this.a.r+=e:this.a.hidden+=e,this.o&&(d===this.visibility.h?this.l+=e:this.l<this.G&&(this.l=0),!this.$&&this.l>=this.G&&(this.D===this.visibility.n?this.d(this.event.K):this.d(this.event.J),this.$=g)),d>this.k&&this.ua(d),this.A<this.M.length&&this.j(b)>=this.M[this.A]&&(this.la(),this.W=c,this.A++),a.t&&(!this.F&&this.I)&&(this.H=
f>=this.b?this.H+e:0,this.H>=this.G&&this.na()),this.X=c);(!a.w||a.w&&(a.t&&!a.F||!a.O))&&a.c&&setTimeout(function(){a.e()},249)};j.N=function(a,c,b,e){function f(){d.c=!document[b];d.c&&d.e()}var d=this;d.w?a.api.isViewable?d.e():a.api.addEventListener("viewablechange",function(){d.e()}):(b?(d.q(document,e,f),d.c=!document[b]):(d.q(c,"focus",function(){d.c||(d.c=g,d.e())}),d.q(c,"blur",function(){d.c=i})),d.e())};
j.la=function(){var a=[this.j(this.a.visible)];a.push(this.j(this.a.r));a.push(this.j(this.a.hidden));a.push(this.j(this.a.Y));this.d("310",a.join("x"));this.a.visible=0;this.a.r=0;this.a.hidden=0;this.a.Y=0;this.O=g};j.na=function(){(new Image).src=this.I;this.F=g};j.ma=function(){(new Image).src=this.I.replace(/;202;pixel/,";270;pixel");this.Z=g};
j.ua=function(a){var c;this.k===this.visibility.m?a===this.visibility.n?c=this.event.aa:a===this.visibility.h&&(c=this.event.ba):this.k===this.visibility.n&&(a===this.visibility.h&&!this.o)&&(c=this.event.K,this.D===this.visibility.m&&(c=this.event.J));this.k=a;"undefined"!==typeof c&&this.d(c)};j.p=function(){var a=this.S(),c=this.U();return this.ha(a,c)};j.ta=function(){return window.$sf.ext.inViewPercentage()/100};j.S=function(){return{x:this.R("Left",this.target),y:this.R("Top",this.target)}};
j.R=function(a,c){var b="offset"+a,e=c,f=null!==e?e[b]:0;for("Top"!==a&&"Left"!==a&&this.error("1st argument must be 'Top' or 'Left'");null!==e&&null!==e.offsetParent;)e=e.offsetParent,f+=e[b];return f};
j.U=function(){var a={scrollLeft:0,scrollTop:0,height:0,width:0},c=window.parent;this.g||(c.innerWidth?(a.width=c.innerWidth,a.height=c.innerHeight,a.scrollLeft=c.pageXOffset,a.scrollTop=c.pageYOffset):c.document.documentElement&&c.document.documentElement.clientHeight?(a.width=c.document.documentElement.clientWidth,a.height=c.document.documentElement.clientHeight,a.scrollLeft=c.document.documentElement.scrollLeft,a.scrollTop=c.document.documentElement.scrollTop):c.document.body&&(a.width=c.document.body.clientWidth,
a.height=c.document.body.clientHeight,a.scrollLeft=c.document.body.scrollLeft,a.scrollTop=c.document.body.scrollTop));return a};j.ha=function(a,c){var b=0,e=0,b=Math.max(a.y,c.scrollTop),f=Math.min(a.y+this.height,c.scrollTop+c.height),e=Math.max(a.x,c.scrollLeft),d=Math.min(a.x+this.width,c.scrollLeft+c.width),b=this.Q(f-b,this.height),e=this.Q(d-e,this.width);return b*e};
j.T=function(a){var c=this.visibility.m;this.o&&a>=this.b?c=this.visibility.h:1===a?c=this.visibility.h:0<a&&(c=this.visibility.n);return c};j.ja=function(){return{x:window.mozInnerScreenX,y:window.mozInnerScreenY}};j.ka=function(){return{scrollLeft:window.screenX,scrollTop:window.screenY,height:window.outerHeight,width:window.outerWidth}};j.pa=function(){var a=0,c=0,b;for(b in this.B)a+=300>this.B[b]?1:0;return c=0.5===this.b?1>a?0:5>a?0.1:9>a?this.b:1:1>a?0:8>a?0.1:12>a?this.b:1};
j.oa=function(a,c,b){var e=0;this.B[a]=c;this.f[a]=g;for(var f in this.f)this.f[f]||e++;0===e&&(this.V(b),this.f.Da=i)};
j.ia=function(){function a(a){return""+Math.round(a)}function c(a){var b="position: absolute; top: "+a.top+"px;",c=this.qa(a.id),b=b+(" width: "+this.u.width+"px;"),b=b+(" height: "+this.u.height+"px;"),b=b+(" left : "+a.left+"px; z-index: -1;");this.v?(a=e.replace("@STYLE@",b).replace("@FLASH@",c),document.body.insertAdjacentHTML("afterbegin",a)):(a=document.createElement("div"),a.style.cssText=b,a.innerHTML=c,document.body.appendChild(a))}function b(){for(var a=0,b=f.i.length;a<b;a++)f.f[f.i[a].id]=
i,c.call(f,f.i[a])}var e='<div style="@STYLE@">@FLASH@</div>',f=this,d=Math.sqrt(this.b),h=[a(this.width*(1-d)),a(this.width*(1-this.b)),a(this.width*this.b),a(this.width*d)],d=[a(this.height*(1-d)),a(this.height*(1-this.b)),a(this.height*this.b),a(this.height*d)];this.i=[{id:"0",left:"0",top:d[0]},{id:"1",left:"0",top:d[3]},{id:"2",left:h[0],top:"0"},{id:"3",left:h[0],top:""+(this.height-1)},{id:"4",left:h[1],top:d[1]},{id:"5",left:h[1],top:d[2]},{id:"6",left:h[2],top:d[1]},{id:"7",left:h[2],top:d[2]},
{id:"8",left:h[3],top:"0"},{id:"9",left:h[3],top:""+(this.height-1)},{id:"10",left:""+(this.width-1),top:d[0]},{id:"11",left:""+(this.width-1),top:d[3]}];0.5===this.b&&(this.i=[{id:"0",left:"0",top:d[0]},{id:"1",left:"0",top:d[3]},{id:"2",left:h[0],top:"0"},{id:"3",left:h[0],top:+(this.height-1)},{id:"4",left:""+this.width/2,top:""+this.height/2},{id:"5",left:h[3],top:"0"},{id:"6",left:h[3],top:""+(this.height-1)},{id:"7",left:""+(this.width-1),top:d[0]},{id:"8",left:""+(this.width-1),top:d[3]}]);
document.body?b():this.q(document,"readystatechange",function(){document.body&&b()})};
j.qa=function(a){var c=this.u,b=c.name+a,e;e="<OBJECT "+(this.v?'classid = "clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"':'data="'+c.path+'" type="application/x-shockwave-flash"');e=e+(' ID="'+b+'" name="'+b+'"')+(' width="'+c.width+'" height="'+c.height+'" style="float:left;">');e+='<PARAM NAME=movie VALUE="'+c.path+'"/>';e+='<PARAM NAME=FlashVars VALUE="identifier='+a+'"/>';e+='<PARAM NAME=quality VALUE="autohigh"/>';e+='<PARAM NAME=wmode VALUE="'+c.wa+'"/>';e+='<PARAM NAME="allowScriptAccess" value="always"/>';
e+='<PARAM NAME="allowFullScreen" value="true"/>';return e+="</OBJECT>"};j.u={path:("https:"===window.location.protocol?"https://secure":"http://cdn")+".flashtalking.com/pageFold/pagefold.swf",name:"ftPF",width:1,height:2,wa:"transparent"};j.Q=function(a,c){return Math.max(Math.ceil(10*(a/c))/10,0)};j.j=function(a){return Math.ceil(a/100)};l.prototype=new n;
n.prototype.d=function(a,c){var b=[""+this.s+this.z];b.push(a);b.push("0");b.push(this.C);b.push(this.random());c&&b.push(c);this.s&&((new Image).src=b.join("-"))};n.prototype.random=function(a){return Math.floor(Math.random()*(a||1E9))};n.prototype.error=function(){};n.prototype.q=function(a,c,b){"function"===typeof a.addEventListener?a.addEventListener(c,b,i):a.attachEvent("on"+c,b)};window.ftPageFold_v3=function(a){new k(a);a.campaignID&&27400>parseInt(a.campaignID,10)&&new l(a)};}());
