(function(){function t(a){var b=document.createElement("script"),c="//",c=window.location.search&&-1<window.location.search.indexOf("tpd_test=1")?c+"beta-s.206ads.com":c+"s.206ads.com";b.src=c+"/js/data/"+a+".js?r="+Math.random();b.type="text/javascript";document.getElementsByTagName("head")[0].appendChild(b);window.twoOhSixLoaded=!0}var k=window.twoOhSix={},l=[],e={},p=!1,q=!1,r=15E3,h={domReady:function(a){"interactive"===document.readyState||"complete"===document.readyState?a():document.addEventListener?
(document.addEventListener("DOMContentLoaded",a,!1),window.addEventListener("load",a,!1)):document.onreadystatechange=function(){"interactive"!==document.readyState&&"complete"!==document.readyState||a()}},getAdUnitById:function(a){var b=h.getAdUnits();if("2.0"===e.version)for(var c=0;c<b.length;c++){if(b[c].getAttribute("data-tpd-id")===a)return b[c]}else return document.getElementById(a)},getAdUnits:function(){return h.getElementsByClassName("2.0"===e.version?"tpd-box":"ad gpt")},getAdUnitsById:function(a){var b=
[],c=h.getAdUnits();if("2.0"===e.version)for(var d=0;d<c.length;d++)c[d].getAttribute("data-tpd-id")===a&&b.push(c[d]);else(a=document.getElementById(a))&&null!==a&&"undefined"!==typeof a&&b.push(a);return b},getBrowserHeight:function(){var a=window,b=document.documentElement,c=document.getElementsByTagName("body")[0];return a.innerHeight||b.clientHeight||c.clientHeight},getBrowserWidth:function(){var a=window,b=document.documentElement,c=document.getElementsByTagName("body")[0];return a.innerWidth||
b.clientWidth||c.clientWidth},getElementsByClassName:function(a){if(document.getElementsByClassName)return document.getElementsByClassName(a);var b=[],c=document.getElementsByTagName("div"),e=c.length;a=new RegExp("(^|\\s)"+a+"(\\s|$)");var f,g;for(g=f=0;f<e;f++)a.test(c[f].className)&&(b[g]=c[f],g++);return b},getParameterByName:function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec(location.search);return null===a?"":decodeURIComponent(decodeURIComponent(a[1].replace(/\+/g,
" ")))},getStyleProperty:function(a,b){if(window.getComputedStyle)return window.getComputedStyle(a,null).getPropertyValue(b);if(a.currentStyle)return a.currentStyle[b]},getUUID:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)})},hasClass:function(a,b){return 0<=a.getAttribute("class").indexOf(b)},inCookie:function(a){return-1<document.cookie.indexOf(a)},isAdExpired:function(a){var b=a.getAttribute("data-tpd-end");
if("undefined"!==typeof b){var c=new Date;h.isElementInViewport(a)&&("true"===a.getAttribute("data-tpd-viewed")?parseInt(b)<c.getTime()-r&&k.refreshAds([a]):a.setAttribute("data-tpd-viewed","true"))}},isElementInViewport:function(a){for(var b=a.offsetTop,c=a.offsetLeft,e=a.offsetWidth,f=a.offsetHeight;a.offsetParent;)a=a.offsetParent,b+=a.offsetTop,c+=a.offsetLeft;return b<window.pageYOffset+window.innerHeight&&c<window.pageXOffset+window.innerWidth&&b+f>window.pageYOffset&&c+e>window.pageXOffset},
isVisible:function(a){var b=window.getComputedStyle(a),c=b.getPropertyValue("display"),b=b.getPropertyValue("visibility");return"none"!==c&&"hidden"!==b&&(0<a.offsetWidth||0<a.offsetHeight)},showMessage:function(a){p&&console.log(a)}},u={init:function(){if(e.adsnative){window._AdsNativeOpts={blockAdLoad:!0,onready:function(){k.insertNativeAds()}};var a=document.createElement("script");a.setAttribute("type","text/javascript");a.setAttribute("src","//static.adsnative.com/static/js/render.v1.js");document.body.appendChild(a)}}},
v={init:function(){if(e.adsupply.guid){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src="//cdn.engine.4dsply.com/Scripts/infinity.js.aspx?guid="+e.adsupply.guid;a.id="infinity";a.setAttribute("data-guid",e.adsupply.guid);a.setAttribute("data-version","async");var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}}},w={init:function(){for(var a=0;a<e.connatix.placements.length;a++){var b=e.connatix.placements[a],c=h.getAdUnitById(b.div);if("undefined"!==
typeof c&&null!==c&&h.isVisible(c)){var d=document.createElement("script");d.type="text/javascript";d.src="//cdn.connatix.com/min/connatix.renderer.infeed.min.js";d.setAttribute("data-connatix-token",b.id);b.wait&&1===b.wait&&(d.setAttribute("data-connatix-waitforpath","data-connatix-waitforpath"),d.setAttribute("data-connatix-waitforposition","data-connatix-waitforposition"),d.setAttribute("async","async"));b.append&&1===b.append?c.appendChild(d):document.getElementsByTagName("head")[0].appendChild(d)}}}},
x={init:function(){(function(a,b,c,d,f,g,h){a.GoogleAnalyticsObject=f;a[f]=a[f]||function(){(a[f].q=a[f].q||[]).push(arguments)};a[f].l=1*new Date;g=b.createElement(c);h=b.getElementsByTagName(c)[0];g.async=1;g.src=d;h.parentNode.insertBefore(g,h);ga("create",e.ga,"auto",{name:"206tracker"});ga("206tracker.require","displayfeatures");ga("206tracker.send","pageview")})(window,document,"script","//www.google-analytics.com/analytics.js","ga")}},y={init:function(){if("undefined"===typeof googletag||"undefined"!==
typeof googletag&&void 0===typeof googletag.version){window.googletag={};window.googletag.cmd=[];var a=document.createElement("script");a.type="text/javascript";a.src="//www.googletagservices.com/tag/js/gpt.js";a.async=!0;var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}a=e.gpt.slots;if("undefined"!==typeof l&&0<l.length)for(b=0;b<l.length;b++)(function(a){window.googletag.cmd.push(function(){googletag.pubads().setTargeting(a[0],a[1])})})(l[b]);for(b=0;b<a.length;b++)for(var c=
a[b],d=h.getAdUnitsById(c.div),f=0;f<d.length;f++){var g=d[f];null!==g&&"undefined"!==typeof g&&h.isVisible(g)&&!h.inCookie("tpd-close-"+c.div)&&("2.0"===e.version&&(adId=g.getAttribute("data-tpd-id"),g.setAttribute("id",adId+"-"+(Date.now()+1E3*b))),function(a,b){window.googletag.cmd.push(function(){googletag.defineSlot(a.id,a.sz,b.id).addService(googletag.pubads())})}(c,g),parent===self&&(1===c.rf&&g.setAttribute("data-tpd-refresh","true"),h.showMessage("The Publisher Desk: Ad slot "+c.id+" defined for: "+
c.div)))}"undefined"!==typeof window.twoOhSixPageUrl&&null!==window.twoOhSixPageUrl&&("/"===window.twoOhSixPageUrl.charAt(0)?window.googletag.cmd.push(function(){googletag.pubads().set("page_url",document.location.protocol+"//"+window.location.host+window.twoOhSixPageUrl)}):window.googletag.cmd.push(function(){googletag.pubads().set("page_url",window.twoOhSixPageUrl)}));window.googletag.cmd.push(function(){googletag.pubads().collapseEmptyDivs();googletag.pubads().addEventListener("slotRenderEnded",
function(a){var b=a.slot.getSlotElementId(),c=a.slot.getAdUnitPath(),d=document.getElementById(b),f=(new Date).getTime(),g=f-parseInt(d.getAttribute("data-tpd-start"));d.setAttribute("data-tpd-loaded","true");d.setAttribute("data-tpd-end",f);a.isEmpty||(f=a.size[1],d.setAttribute("data-tpd-width",a.size[0]),d.setAttribute("data-tpd-height",f));if(parent===self){null!==d.getAttribute("data-tpd-refresh")&&"true"===d.getAttribute("data-tpd-refresh")&&(d.setAttribute("data-tpd-viewed","false"),e.rf&&
0<parseInt(e.rf)&&(r=e.rf),setInterval(function(){h.isAdExpired(b)},1E3));if(a.isEmpty)d.setAttribute("data-tpd-empty","true");else if(d.setAttribute("data-tpd-empty","false"),"fixed"===h.getStyleProperty(d,"position")){f=document.createElement("a");f.setAttribute("href","#");f.setAttribute("class","tpd-close-btn");f.onclick=function(){d.parentNode.removeChild(d);document.cookie="tpd-close-"+b+"=true;path=/";return!1};var m=document.createElement("img");m.setAttribute("src","http://s.206ads.com/images/closeButton.png");
f.appendChild(m);d.appendChild(f)}e.logging&&1===parseInt(e.logging)&&window._LTracker.push({type:"adResponse",siteId:window.twoOhSixId,url:top.document.URL,divId:b,slotId:c,blank:a.isEmpty?"true":"false",duration:g,userAgent:navigator.userAgent});h.showMessage("The Publisher Desk: Ad response complete for: "+b);a.isEmpty&&h.showMessage("The Publisher Desk: WARNING: Ad response for "+b+" is empty");h.showMessage("The Publisher Desk: Ad response was "+g+" milliseconds for: "+b)}});googletag.enableServices()});
for(var m=[],b=0;b<a.length;b++)for(c=a[b],d=h.getAdUnitsById(c.div),f=0;f<d.length;f++)g=d[f],null!==g&&"undefined"!==typeof g&&h.isVisible(g)&&function(a){window.googletag.cmd.push(function(){googletag.display(a.id);m.push({divId:a.getAttribute("data-tpd-id")||a.getAttribute("data-ad-id")});e.ga&&"undefined"!==typeof ga&&ga("206tracker.send","event","ad","called",a.id);parent===self&&(a.setAttribute("data-tpd-start",(new Date).getTime()),h.showMessage("The Publisher Desk: Ad call has been made for: "+
a.id))})}(g);e.logging&&1===parseInt(e.logging)&&window._LTracker.push({type:"request",url:top.document.URL,adsCalled:m,screen:{width:h.getBrowserWidth(),height:h.getBrowserHeight()},userAgent:navigator.userAgent})}},z={init:function(){var a=document.createElement("script");a.type="text/javascript";a.async="true";a.src="//cloudfront.loggly.com/js/loggly.tracker.js";document.getElementsByTagName("head")[0].appendChild(a);window._LTracker=window._LTracker||[];window._LTracker.push({logglyKey:"1667eaf8-f7c2-46d1-8dde-e7cf790d02b0",
sendConsoleErrors:!1})}},n={init:function(){n.prep();n.load()},load:function(){var a=document.createElement("script");a.type="text/javascript";a.async="async";a.src="//widgets.outbrain.com/outbrain.js";document.getElementsByTagName("head")[0].appendChild(a)},insert:function(){"undefined"!==typeof OBR&&OBR.extern.researchWidget()},prep:function(a){var b;null!==a&&"undefined"!==typeof a?a instanceof Array?b=a:a instanceof Object&&(b=[a]):"2.0"===e.version?b=h.getElementsByClassName("tpd-box"):(b=[],
b.push(document.getElementById("bottom_teasers")),b.push(document.getElementById("contextual-a")),b.push(document.getElementById("contextual-b")));if(b)for(a=0;a<b.length;a++){var c=b[a];if(null!==c&&"undefined"!==typeof c&&h.isVisible(c))for(var d=c.getAttribute("id")||c.getAttribute("data-tpd-id")||c.getAttribute("data-ad-id"),f=0;f<e.outbrain.placements.length;f++){var g=e.outbrain.placements[f];if(g.div==d)for(var m=0;m<g.widgets.length;m++){var k=document.createElement("div");1===g.widgets[m].mobile?
k.setAttribute("class","tpd-mobile"):k.setAttribute("class","tpd-desktop");c.appendChild(k);if(null!==k&&"undefined"!==typeof k&&h.isVisible(k)){var l=document.createElement("div");l.setAttribute("class","OUTBRAIN");l.setAttribute("data-src",document.URL);l.setAttribute("data-widget-id",g.widgets[m].widgetId);l.setAttribute("data-ob-template",g.widgets[m].template);k.appendChild(l)}}}}}},A={init:function(){for(var a=0;a<e.pubexchange.placements.length;a++){var b=e.pubexchange.placements[a],c=h.getAdUnitById(b.div);
if(null!==c&&"undefined"!==typeof c){var d=document.createElement("div");d.setAttribute("id",b.id);c.appendChild(d);if(document.getElementById("pubexchange-jssdk"))break;c=document.createElement("script");c.id="pubexchange-jssdk";c.async="true";c.src="//cdn.pubexchange.com/modules/partner/"+b.site;b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(c,b)}}}},B={init:function(){var a=document.createElement("img");a.setAttribute("src","//pixel.quantserve.com/pixel/p-dTdeRsE4NP1z8.gif");
a.setAttribute("width",1);a.setAttribute("height",1);document.body.appendChild(a)}},C={init:function(){window._taboola=window._taboola||[];_taboola.push({article:"auto"});var a=document.createElement("script");a.async=1;a.src="//cdn.taboola.com/libtrc/206-technobuffalo/loader.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b);for(a=0;a<e.taboola.placements.length;a++){var b=e.taboola.placements[a],c=h.getAdUnitById(b.div);if(null!==c&&"undefined"!==typeof c)for(var d=
0;d<b.widgets.length;d++){var f=b.widgets[d],g=document.createElement("div");g.setAttribute("id",f.container);c.appendChild(g);_taboola.push({mode:f.mode,container:f.container,placement:f.placement,target_type:f.target_type})}}_taboola.push({flush:!0})}},D={init:function(){for(var a=0;a<e.teads.placements.length;a++){var b=e.teads.placements[a],c=document.createElement("script");c.type="text/javascript";c.src="//as.ebz.io/api/choixPubJS.htm?pid="+b.id+"&screenLayer=1&mode=NONE&home="+b.url;document.body.appendChild(c)}}},
E={init:function(){for(var a=0;a<e.triplelift.placements.length;a++){var b=e.triplelift.placements[a],c=h.getAdUnitById(b.div);if(null!==c&&"undefined"!==typeof c){var d=document.createElement("script");d.type="text/javascript";d.src="//ib.3lift.com/ttj?inv_code="+b.id;c.appendChild(d)}}}},F={init:function(){for(var a=0;a<e.yieldmo.placements.length;a++){var b=h.getAdUnitById(e.yieldmo.placements[a].div);if(null!==b&&"undefined"!==typeof b){var c=document.createElement("div");c.setAttribute("id",
e.yieldmo.placements[a].id);c.setAttribute("class","ym");b.appendChild(c);void 0===window._ym?(window._ym="",b=document.createElement("script"),b.type="text/javascript",b.async=!0,b.src="//static.yieldmo.com/ym.min.js",document.getElementsByTagName("head")[0].appendChild(b)):window._ym instanceof String||void 0===window._ym.chkPls||window._ym.chkPls()}}}},G={init:function(){for(var a=0;a<e.zergnet.placements.length;a++){var b=e.zergnet.placements[a],c=h.getAdUnitById(b.div);if(null!==c&&"undefined"!==
typeof c){var d="undefined"!==typeof b.inf?b.inf:0,f=document.createElement("div");1===d?f.setAttribute("class","zergnet-widget"):f.setAttribute("id","zergnet-widget-"+b.id);c.appendChild(f);c=document.createElement("script");c.type="text/javascript";c.async=!0;c.src=1===d?"//www.zergnet.com/zerg-inf.js?id="+b.id:"//www.zergnet.com/zerg.js?id="+b.id;b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(c,b)}}}};k.config=function(a){e=a;"undefined"!==typeof window.twoOhSixDataVersion&&
(e.version=window.twoOhSixDataVersion);h.domReady(function(){if(!q){q=!0;if("undefined"!==typeof window.twoOhSixCmd&&0<window.twoOhSixCmd.length)for(var a=0;a<window.twoOhSixCmd.length;a++)window.twoOhSixCmd[a]();if(parent===self){h.showMessage("The Publisher Desk: Loaded");if(e.css){var a=document.createElement("style"),c=e.css.replace(/\\'/g,"'");a.setAttribute("type","text/css");a.styleSheet?a.styleSheet.cssText=c:(c=document.createTextNode(c),a.appendChild(c));document.getElementsByTagName("head")[0].appendChild(a)}e.js&&
(a=document.createElement("script"),c=e.js.replace(/\\'/g,"'"),a.setAttribute("type","text/javascript"),document.all&&!document.addEventListener?a.text=c:(c=document.createTextNode(c),a.appendChild(c)),document.getElementsByTagName("head")[0].appendChild(a));e.ga&&x.init();e.logging&&1===parseInt(e.logging)&&z.init();B.init()}e.gpt&&y.init();parent===self&&(e.outbrain&&n.init(),e.connatix&&w.init(),e.adsnative&&u.init(),e.adsupply&&v.init(),e.zergnet&&G.init(),e.pubexchange&&A.init(),e.taboola&&C.init(),
e.teads&&D.init(),e.triplelift&&E.init(),e.yieldmo&&F.init())}})};k.insertAds=function(a){var b=null;"undefined"!==typeof a?a instanceof Array?b=a:a instanceof Object&&(b=[a]):b=h.getAdUnits();if(null!==b&&"undefined"!==typeof b)for(a=0;a<b.length;a++){var c=b[a];if((c.hasAttribute("data-ad-id")||c.hasAttribute("data-tpd-id"))&&!c.hasAttribute("data-tpd-start")&&h.isVisible(c))for(var d=c.getAttribute("data-ad-id")||c.getAttribute("data-tpd-id"),f=0;f<e.gpt.slots.length;f++){var g=e.gpt.slots[f];
if(g.div===d){var k=d+"-"+(Date.now()+1E3*a);c.setAttribute("id",k);window.googletag.pubads().display(g.id,g.sz,k);parent===self&&(c.setAttribute("data-tpd-start",(new Date).getTime()),h.showMessage("The Publisher Desk: Ad call has been made for: "+c.id))}}}};k.insertContextualAds=function(a){e.outbrain&&(n.prep(a),n.insert())};k.insertNativeAds=function(a){var b=null;"undefined"!==typeof a?a instanceof Array?b=a:a instanceof Object&&(b=[a]):"2.0"===e.version?b=h.getElementsByClassName("tpd-box tpd-native"):
(b=[],b.push(document.getElementById("native-a")),b.push(document.getElementById("native-b")));if(null!==b&&"undefined"!==typeof b)for(a=0;a<b.length;a++){var c=b[a];if(null!==c&&h.isVisible(c)){var d=c.getAttribute("id")||c.getAttribute("data-ad-id"),f=d+"-"+(Date.now()+1E3*a);c.setAttribute("id",f);c.hasAttribute("class")?c.setAttribute("class",c.getAttribute("class")+" an-container"):c.setAttribute("class","an-container");for(var g=0;g<e.adsnative.placements.length;g++){var k=e.adsnative.placements[g];
if(k.div===d){c.setAttribute("data-an-id",k.id);var l=new AdsNative(k.id);l.fetchAd(function(a){a&&l.displayAd(f)})}}}}};k.refreshAds=function(a){var b=[],c=[];null!==a&&"undefined"!==typeof a?a instanceof Array?b=a:a instanceof Object&&(b=[a]):b=h.getAdUnits();for(a=0;a<b.length;a++){var d=b[a];if(null!==d)for(var f=d.getAttribute("data-ad-id")||d.getAttribute("data-tpd-id"),g=0;g<e.gpt.slots.length;g++)if(e.gpt.slots[g].div===f){if(d.firstChild)for(;d.firstChild;)d.removeChild(d.firstChild);if(d.hasAttribute("id")){var l=
d.getAttribute("id");d.setAttribute("data-tpd-id",l.replace(/\-[0-9]{10,}$/,""));d.removeAttribute("id");d.removeAttribute("data-tpd-loaded");d.removeAttribute("data-tpd-start");d.removeAttribute("data-tpd-end");d.removeAttribute("data-tpd-viewed");d.removeAttribute("style");c.push(d)}}}0<c.length&&k.insertAds(c)};k.sendPageView=function(){e.ga&&"undefined"!==typeof ga&&ga("206tracker.send",{hitType:"pageview",page:window.location.pathname,title:document.title});"undefined"!==typeof _qevents&&_qevents.push({qacct:"p-dTdeRsE4NP1z8"})};
k.getTargeting=function(){return l};k.getTargetingValue=function(a){for(var b=k.getTargeting(),c=0;c<b.length;c++)if(b[c][0]===a)return b[c][1];return null};k.setTargeting=function(a,b){l.push([a,b])};k.setTargetingArray=function(a){l=a};window.location.search&&-1<window.location.search.indexOf("tpd_debug=1")&&(p=!0);"undefined"===typeof window.twoOhSixId?console.log("The Publisher Desk: Fatal Error: window.twoOhSixId needs to be defined."):!0===window.twoOhSixLoaded?console.log("The Publisher Desk: Warning: init.js has already been called on this page."):
t(window.twoOhSixId)})();
