(function(){var g=void 0,h=true,i=null,j=false,k,l=this;function m(a,b){function c(){}c.prototype=b.prototype;a.U=b.prototype;a.prototype=new c;a.prototype.constructor=a};var aa=/[?&]__cb_debug=([^&]+)/i,ba={scroll:5E3,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3},ca={scroll:2E4,keydown:5E3,mousemove:5E3,resize:5E3,mousedown:5E3,focus:5E3,pageload:5E3},da=/:\/\/static2\.chartbeat.com\/js\/chartbeat(_[a-z]+)?\.js$/;function ea(a,b){var c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}function fa(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function ga(a,b){var c="",d=ha(encodeURIComponent(a));d.splice(b||5,d.length);q(d,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",d;a>0;)d=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(d)+b,a>>>=6;a=b}c+=a});return c}
function ha(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,n=3285377520,p=[],o,w,z,L,M,Z=Math.ceil((a.length/4+2)/16),W=[Z],A=0,x;A<Z;A++){W[A]=[];for(o=0;o<16;o++)W[A][o]=a.charCodeAt(A*64+o*4)<<24|a.charCodeAt(A*64+o*4+1)<<16|a.charCodeAt(A*64+o*4+2)<<8|a.charCodeAt(A*64+o*4+3)}A=(a.length-1)*8;a=Z-1;W[a][14]=Math.floor(A/Math.pow(2,32));W[a][15]=A&4294967295;for(A=0;A<Z;A++){for(x=0;x<16;x++)p[x]=W[A][x];
for(x=16;x<80;x++)p[x]=(p[x-3]^p[x-8]^p[x-14]^p[x-16])<<1|(p[x-3]^p[x-8]^p[x-14]^p[x-16])>>>31;a=c;o=d;w=e;z=f;L=n;for(x=0;x<80;x++)M=Math.floor(x/20),M=(a<<5|a>>>27)+(M==0?o&w^~o&z:M==1?o^w^z:M==2?o&w^o&z^w&z:o^w^z)+L+b[M]+p[x]&4294967295,L=z,z=w,w=o<<30|o>>>2,o=a,a=M;c=c+a&4294967295;d=d+o&4294967295;e=e+w&4294967295;f=f+z&4294967295;n=n+L&4294967295}return[c,d,e,f,n]}
function ia(a){var b=l.navigator,c=l.window.screen,d=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];q(b.plugins,function(a){d.push(a.name+a.description+a.filename+a[0].type)});b=l.performance;d=d.concat([b&&b.now?b.now():"",document.title,l.location.href,r(),fa()]);return d.concat(a||[]).join()}function s(a,b,c){var d=Array.prototype.slice,e=d.call(arguments,2);return function(){return a.apply(b,e.concat(d.call(arguments)))}}
function t(a){return typeof a!=="undefined"}function u(a){return a.replace(/^www\./,"")}function v(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)}function ja(a,b){var c=l;c.removeEventListener?c.removeEventListener(a,b,j):c.detachEvent&&c.detachEvent("on"+a,b)}function y(a){return typeof a==="number"}function B(a){return typeof a==="string"}function ka(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}
function r(){return(new Date).getTime()}function la(a){return encodeURIComponent(a)}function C(a){return!!a&&a.constructor===Object}function ma(a,b){if(!C(a)||!C(b))return a===b;var c=0,d=h;q(a,function(a,e){c++;return d=a===b[e]});if(!d)return j;var e=0;q(b,function(){e++});return c===e}function q(a,b){if(C(a)===h)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===j)break}}
function na(a,b){var c=[];q(a,function(a,e){var f=b(a,e);c.push(f)});return c}function oa(a,b){for(var c=0,d=a.length;c<d;c++)if(b(a[c]))return c;return-1}function pa(a){if(C(a)===j)return"";var b=[];q(a,function(a,d){b.push(encodeURIComponent(d)+"::"+encodeURIComponent(a))});return b.join("&")}function qa(a){B(a)||(a="");var b={};q(a.split("&"),function(a){a=a.split("::");a.length===2&&(b[decodeURIComponent(a[0])]=decodeURIComponent(a[1]))});return b}
function ra(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,e=b.length;d<=e;d++)c[d]=[d];for(var f=0,n=a.length;f<=n;f++)c[0][f]=f;for(var p,o,w,d=1;d<=e;d++)for(f=1;f<=n;f++)p=d-1,o=f-1,w=c[p][o],b.charAt(p)==a.charAt(o)?c[d][f]=w:(o=c[d][o]+1,p=c[p][f]+1,w+=2,c[d][f]=Math.min(o,p,w));return c[b.length][a.length]}var sa;function ta(){}var ua=l.setInterval,va=l.clearInterval,wa=l.setTimeout,D=l.clearTimeout;
function xa(a,b){var c={};q(b,function(b,e){c[b]=s(a[e],a)});return c}function ya(a){var b=[];if(!C(a))return b;for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b}function za(a){switch(a){case g:return"undefined";case "":return"empty";default:return a}};function Aa(a,b,c){b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");for(var d=[],b=c.getElementsByTagName(b),c=b.length;c--;)b[c].getAttribute(a)&&d.push(b[c]);return d}function E(a,b){var c=i;b&&(c=b.getAttribute(a));if(c===i){var d=Aa(a,"*",b);d.length!==0&&(c=d[0].getAttribute(a))}return c}
function Ba(a,b,c){c=c||"";if(a===g)a=j;else{var d;if(!(d=c===""&&a.getAttribute(b)))if(d=a.getAttribute(b))d=a.getAttribute(b)===c;a=d?a:a===document.body?j:Ba(a.parentNode,b,c)}return a}function Ca(a,b,c){a="page"+a+"Offset";b="scroll"+b;if(c&&(c=Aa("data-cb-scroll-element"))&&c.length)return c[0][b];if(y(l[a]))return l[a];else if(document.body&&document.body[b])return document.body[b];else if(document.documentElement[b])return document.documentElement[b];return 0}
function Da(a){var b=document,b=b[b.compatMode==="CSS1Compat"?"documentElement":"body"]["client"+a]||0;window["inner"+a]&&(b=Math.min(window["inner"+a],b));return b}function Ea(){return Da("Height")}function Fa(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}
function Ga(a,b,c){a.ownerDocument||(a=a.correspondingUseElement);if(!a||!a.ownerDocument)return i;var d=a.ownerDocument.documentElement,e=0,f=t(c)?c+1:-1;B(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==d&&e!==f;){if(c(a))return a;a=a.parentNode;e++}return i}function Ha(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}
function Ia(a){a=a||window.event;return!a?i:Ga(a.target||a.srcElement,Ha,10)}function Ja(a,b){var c=document.createElement(a);q(b,function(a,b){c.setAttribute(b,a)});return c}function Ka(a){var b=t(g)?g:{};b.src=a;a=Ja("script",b);a.setAttribute("type","text/javascript");b=document.head||document.getElementsByTagName("head")[0];t(g)?g.appendChild(a):b&&b.appendChild(a)}
function La(){if(t(Ma))return Ma;var a;a:{a=document.getElementsByTagName("script");for(var b=a.length-1;b>-1;b--)if(da.test(a[b].getAttribute("src"))){a=a[b];break a}a=g}return Ma=t(a)}var Ma;function Na(){this.Y={};this.Hb=1}k=Na.prototype;k.M=function(a,b,c){this.Hb++;this.Y[a]=this.Y[a]||{};this.Y[a][this.Hb]=[b,c];return this.Hb};k.T=function(a){if(B(a))this.Y[a]=g,delete this.Y[a];else if(y(a)){var b=h;q(this.Y,function(c){q(c,function(d,e){if(parseInt(e,10)===a)return c[e]=g,delete c[e],b=j});return b})}};k.S=function(a,b){if(this.Y[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];q(this.Y[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
k.addEventListener=function(a,b){var c=this.M(a,b);b._cbEventId=c};k.removeEventListener=function(a,b){this.Y[a]&&this.Y[a][b._cbEventId]&&this.Y[a][b._cbEventId][0]===b&&this.T(b._cbEventId)};var F=new Na,Oa="o",Pa={M:Oa,T:"f"},Qa="a";var G={};
G.q=function(){G.ub?G.Ua("pageload"):(G.pc=[{target:l,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:l,event:"resize"},{target:document.body,event:"mousedown"}],G.eb=i,G.la=i,G.tb={},G.sb={},G.cc={},G.fb={},q(G.pc,function(a){var b=a.event;v(a.target,b,function(a){G.Ua.call(G,b,a)})}),F.M("f",function(){G.Ua("focus")}),G.Ua("pageload"),v(document.body,"click",function(a){(a=Ia(a))&&F.S("c",a)},h),v(document.body,"contextmenu",function(a){(a=Ia(a))&&
F.S("r",a)}),G.ub=h)};G.uc=function(){var a,b=G.cc.keydown;if(b===g)return j;b=r()-b;return b<=(a||15E3)&&b>=0};G.Da=function(a,b){var c=G.fb[a];if(!c)return"";var b=b||r(),d,e=0;q(c,function(a){d=Math.floor((b-a)/1E3);d>=0&&d<16&&(e|=1<<d)});c=("0000"+e.toString(16)).slice(-4);return c=="0000"?"":c};G.Yc=function(){G.fb={}};G.Nb=100;
G.Ua=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}G.cd(a);if(G.eb===i)G.kc(a);else if(!G.la||ba[G.la]<ba[a]||ca[G.la]<ca[a])G.la=a};G.cd=function(a){var b=r();G.cc[a]=b;var c=G.fb[a];c?c.length<2?c.push(b):c[c.length-2]>b-1E3?c[c.length-1]=b:c.push(b):c=[b];c.length>32&&c.shift();G.fb[a]=c};G.kc=function(a){G.eb=wa(G.yc,G.Nb);F.S(Qa);G.tb[a]!==i&&D(G.tb[a]);G.sb[a]!==i&&D(G.sb[a]);G.ic(a,G.tb,ba,"i");G.ic(a,G.sb,ca,"j")};
G.ic=function(a,b,c,d){b[a]=wa(function(){D(b[a]);delete b[a];var c=j;q(b,function(){c=h;return j});c||F.S(d)},c[a]+G.Nb)};G.yc=function(){D(G.eb);G.eb=i;if(G.la)G.kc(G.la),G.la=i};var Ra,Sa,Ta,Ua,Va;(function(){var a,b;q(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof l.document[a]==="boolean")return b=c,j});b!==g&&(Ua=a,Va=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),Ta=b+"visibilitychange")})();var Wa=j;function Xa(){Wa=Va&&l.document[Va]==="prerender"?h:j}function Ya(){Sa=h;F.S("f")}function Za(){Sa=j;F.S("b")}
function $a(a,b,c){l.addEventListener?l.addEventListener(a,c,j):l.document.attachEvent&&l.document.attachEvent(b,c)}function ab(){var a=h;l.document.hasFocus&&(a=l.document.hasFocus());var b=j;Ua&&(b=l.document[Ua]);return a&&!b}function bb(){ab()?Ya():Za()}function cb(a){Xa();if(Wa){var b=j,c=function(){b||(Xa(),Wa||(b=h,a(),l.window.setTimeout(function(){l.document.removeEventListener(Ta,c,j)},100)))};l.document.addEventListener(Ta,c,j)}else a()};function H(){this.k=l._sf_async_config||{};this.Tb=s(this.gc,this)}H.prototype.q=function(){this.Cb=0};H.prototype.gc=function(){};H.prototype.Ka=function(a){Wa||ea(a,this.Tb)};H.prototype.ba=function(){this.Tb=i};function db(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace("+"," "),q(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function eb(a,b){var c="",d=l.location.href.split("?");if(d.length){var d=db(d[1]),e=b||a;d[e]&&(c=d[e])}return c}function fb(a,b){return!b?h:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function gb(a,b){var c=[];q(b,function(b){var e=a[b];t(e)&&(Object.prototype.toString.call(e)==="[object Array]"?q(e,function(a){c.push(b+"="+a)}):C(e)?q(e,function(a,b){c.push(b+"="+a)}):((e+"").length||b=="r")&&c.push(b+"="+e))});c.push("_");return c.join("&")}
function hb(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),d=l.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0)if(a.indexOf("//")===0)a=d.protocol+a;else if(a.indexOf("/")===0)var e=fb(d.protocol,d.port)?"":d.port,a=d.protocol+"//"+d.hostname+(e?":"+e:"")+a;else{var e=document.baseURI||d.href,f=e.indexOf("?");f===-1&&(f=e.indexOf("#"));if(f===-1)f=e.length;f=e.lastIndexOf("/",f);a=f===-1?"/"+a:e.substr(0,f)+"/"+
a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=d.hostname;if(b.protocol==="")b.protocol=d.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(fb(b.protocol,b.port)||b.port==="0")b.port="";return b}
function ib(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash}function jb(){var a=0,b=(l.location.search||"").match(aa);b&&b[1]&&(a=parseInt(b[1],10));return a};var kb="adIdentifier";function I(a,b,c){a[b]=a[b]||c}function lb(a,b){for(var c=l[a]||[];c.length;)b(c.shift());l[a]={push:b}}function mb(a){q(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=db(b.src.split("?")[1]),I(a,"uid",b.uid),I(a,"domain",b.domain),j})}function nb(a,b){return a[b]?encodeURIComponent(a[b]):""}function ob(a){var b={};q(a,function(a,d){d.charAt(0)=="_"&&(b[d]=a)});return b};function pb(a){var b=a===document.documentElement?a.scrollHeight:a.offsetHeight,c=a.offsetWidth;if(b<=1||c<=1){var d=qb(a,["overflow","overflow-x","overflow-y"]);d.overflow==="hidden"||d["overflow-x"]==="hidden"||d["overflow-y"]==="hidden"||q(a.getElementsByTagName("iframe"),function(a){var d=a.offsetHeight,a=a.offsetWidth;if(d>1&&a>1)return b=d,c=a,j})}return{height:b,width:c}}function rb(a){a=pb(a);return a.height*a.width}
function sb(a){var b;"contains"in document.documentElement&&!document.documentElement.contains(a)?b=j:(b=pb(a),b=b.height>1&&b.width>1);if(!b)return j;b=qb(a,["visibility","display","overflow","opacity"]);if(b.visibility=="hidden"||b.display=="none"||b.opacity=="0")return j;if(b.overflow=="hidden"&&(a.offsetHeight==0||a.offsetWidth==0))return j;b=h;for(var c=a.parentElement;c&&b;){var d;if(c.scrollHeight===c.clientHeight&&c.scrollWidth===c.clientWidth)d=j;else{var e=qb(c,["overflow","overflow-x",
"overflow-y"]);d=e.overflow;var f=e["overflow-x"],e=e["overflow-y"];d=d==="auto"||d==="scroll"||f==="auto"||f==="scroll"||e==="auto"||e==="scroll"}d&&(b=tb(a,c));c=c.parentElement}return b&&tb(a,i)}function tb(a,b){var c,d;if(b){var e=pb(b);c=e.width;d=e.height}else c=Da("Width"),d=Ea();var f=pb(a),e=f.height,f=f.width,n=ub(a,b),p=n.y,n=n.x;c=Math.min(n+f,f,c,c-n);d=Math.min(p+e,e,d,d-p);if(c<0||d<0)return j;e*=f;return c*d>=(e>=242500?0.3:0.5)*e}
function ub(a,b,c){var d=a.offsetLeft,e=a.offsetTop,f=vb(a);d+=f.x;e+=f.y;for(var n=j,p=c?0:Ca("X","Left",g),o=c?0:Ca("Y","Top",g),f=a.offsetParent;a&&a!==b&&a!==document.body;){if(a===f)f=vb(a),d+=a.offsetLeft+f.x,e+=a.offsetTop+f.y,f=a.offsetParent;c||(d-=a.scrollLeft,e-=a.scrollTop);if(qb(a,["position"]).position==="fixed"){n=h;break}a=a.parentElement}c||(d-=b?b.scrollLeft:p,e-=b?b.scrollTop:o);n&&(d+=p,e+=o);return{x:d,y:e}}
function qb(a,b){var c={},d,e;l.getComputedStyle?d=l.getComputedStyle(a,i):a.currentStyle?e="currentStyle":a.style&&(e="style");q(b,function(b){c[b]=d?d[b]||d.getPropertyValue(b):a[e][b]});return c}var wb=/matrix(3d)?\((.*)\)/;function vb(a){var b={x:0,y:0},a=qb(a,["transform"]).transform;if(!B(a))return b;var c=a.match(wb);if(!c)return b;var a=c[2].split(", "),d;t(c[1])?(c=12,d=13):(c=4,d=5);b.x=parseInt(a[c],10);b.y=parseInt(a[d],10);return b};var J={},xb={nb:"g"};J.Ob={IDLE:0,rc:1,qc:2,La:3};J.sc={IDLE:0,rc:1,qc:2,La:3};J.Z=0;J.$=0;J.q=function(){if(!J.ub)F.M(Qa,J.Ic,J),F.M("i",J.Nc,J),F.M("f",J.Kc,J),F.M("b",J.Jc,J),F.M("j",J.Mc,J),J.ub=h};J.nb=function(){return J.Z};J.Hc=function(){return J.$};J.Ic=function(){J.Z===1?J.ja(3):J.Z===0&&J.ja(2);J.$===1?J.ia(3):J.$===0&&J.ia(2)};J.Nc=function(){J.Z===3?J.ja(1):J.Z===2&&J.ja(0)};J.Mc=function(){J.$===3?J.ia(1):J.$===2&&J.ia(0)};
J.Kc=function(){(J.Z===0||J.Z===2)&&J.ja(3);(J.$===0||J.$===2)&&J.ia(3)};J.Jc=function(){J.Z===3?J.ja(2):J.Z===1&&J.ja(0);J.$===3?J.ia(2):J.$===1&&J.ia(0)};J.ja=function(a){J.Z=a;F.S("s",a)};J.ia=function(a){J.$=a;F.S("x",a)};function yb(a,b){this.qb=a||g;this.Ja=b||g;this.ga=this.N=0;this.Xb=s(this.Rc,this);this.Fb=this.aa=i}k=yb.prototype;k.q=function(){this.ga=this.N=0;this.aa=i;this.Fb=F.M("s",this.Ea,this);this.Ea(J.nb())};k.Ea=function(a){va(this.aa);this.aa=i;if(a===J.Ob.La)this.aa=ua(this.Xb,1E3)};k.Rc=function(){if(this.qb===g||this.qb())this.N++,this.ga++,this.Ja&&this.Ja()};k.terminate=function(){va(this.aa);this.aa=i;F.T(this.Fb)};k.ba=function(){this.terminate();this.Ja=this.qb=g};function zb(){H.call(this);this.Ib=s(this.Ib,this);this.Qb=0;this.kb=Ab;this.q()}m(zb,H);zb.prototype.q=function(){zb.U.q.call(this);this.Qb++;this.F={};this.F.siteId="";this.mb=j;this.Pb=Bb;this.Sb=this.oc=j;this.Kb={};this.mc=j;this.gb=0;this.za=i;this.gd=F.M("s",this.Wb,this);this.Wb(J.nb())};var Ab=0,Bb=0;k=zb.prototype;k.Wb=function(a){if(this.za!==i)va(this.za),this.za=i;this.gb=0;if(a===J.Ob.La)this.za=ua(this.Ib,100)};
k.Ib=function(){if(sb(this.Na.Q)){if(this.gb++,this.gb>=10)this.mc=h,Cb(this),F.S("p")}else this.gb=0;this.Ac&&this.Ac.update()};function Cb(a){F.T(a.gd);va(a.za);a.za=i}k.$a=function(a){if(a.exclude)this.mb=h;this.Sb=!!a.dynamicLogic;this.F=a;F.S("p");if(a=a.vizu)this.oc=h,this.Kb=qa(a),F.S("z",this.Kb,this.Na.da.N)};
function Db(a){var b=encodeURIComponent(a.an),c=a.aE,d=a.ax,e=a.ay,f=a.aw,n=a.ah,p=encodeURIComponent(a.av||""),o=encodeURIComponent(a.ac||""),w=encodeURIComponent(a.aP||""),z=encodeURIComponent(a.aS||""),L=encodeURIComponent(a.aH||""),M=encodeURIComponent(a.aW||""),Z=encodeURIComponent(a.aL||""),W=a.ao,A=a.aR,x=a.am,zc=a.aV?"1":"0";a.exclude&&(o="");return b+"="+[c,d,e,f,n,o,p,W+"."+A,zc,w,z,L,M,Z,x].join("::")}
k.ma=function(a,b){a.siteId=E("data-cb-site-id",b)||"";a.dynamicLogic=E("data-cb-dynamic-logic-id",b)||"";if(E("data-cb-exclude",b))this.mb=h;return a};k.refresh=function(){Cb(this);this.q()};k.ba=function(){zb.U.ba.call(this);Cb(this)};function K(a){this.P=a;this.qa=a.getAttribute("data-cb-ad-id")||a.id||"";this.ob=1;var b=this;this.da=new yb(function(){Eb(b);return sb(b.Q)},s(this.Ja,this));Fb&&this.Ma();this.q()}var Fb;K.prototype.Ja=function(){F.S("e",this);if(this.G){var a=this.G;a.oc&&F.S("z",a.Kb,1)}this.Pa&&this.Pa.update()};
K.prototype.q=function(){this.F={};this.F.campaignId="";this.F.creativeId="";this.F.placementId="";this.F.server_height="";this.F.server_width="";this.F.lineId="";this.Q=this.P;this.Ta=this.vb=this.rb=this.xb=j;this.fa={};this.fa.iab=j;this.fa.frame=j;this.fa.roadblock=j;Eb(this);this.da.q()};K.prototype.Ma=function(){var a=this;this.Pa=new Fb(this.qa,function(){return{adContainer:a.P,creativeContainer:a.Q,creativeScenarios:a.fa,adData:Gb(a)}})};
var Hb={300:{250:1,600:1,1050:1},180:{150:1},160:{600:1},728:{90:1},970:{90:1,66:1,250:1,415:1,550:1},120:{60:1},88:{31:1},62:{88:1},196:{31:1}};
function Eb(a){var b=l._sf_async_config;if(b&&(b=b.creativeDetection,b===j||B(b)&&b!=="iab"))return;var c=rb(a.P);if(a.Q!==a.P)if(b=rb(a.Q),b>c||b===0)a.Q=a.P;else if(b>0)return;q(["iframe","embed","object","img","div"],function(b){q(a.P.getElementsByTagName(b),function(b){var d=pb(b);if(!(d.height*d.width>c)&&Hb[d.width]&&Hb[d.width][d.height])return a.Q=b,a.fa.iab=h,j});return a.Q===a.P})}
K.prototype.$a=function(a,b){if(a.noRefresh)this.xb=h;var c=a.roadblock;this.vb=(this.Ta=c==="master")||c==="companion";this.fa.roadblock=c||j;this.F=a;if(this.rb=!!b){if(c=l._sf_async_config)if(c=c.creativeDetection,c===j||B(c)&&c!=="iframe")return;if(rb(b)>0)this.Q=b,this.fa.frame=h}this.G&&this.G.$a(a)};function N(a,b){return a.F&&t(a.F[b])?a.F[b]:""}var O="engagedSeconds",Ib={nd:"id",md:O,jd:"campaignId",kd:"creativeId",od:"placementId",ld:"element"};
function Jb(a){var b={};b.id=a.qa;b[O]=a.da.N;b.campaignId=N(a,"campaignId");b.creativeId=N(a,"creativeId");b.placementId=N(a,"placementId");return b}
function Gb(a){var b={};b.an=a.qa;b.aE=a.da.N;if(a.Q){var c=ub(a.Q,g,h);b.ax=c.x;b.ay=c.y;c=pb(a.Q);b.aw=c.width;b.ah=c.height}b.ac=N(a,"campaignId");b.av=N(a,"creativeId");b.aP=N(a,"placementId");b.aW=N(a,"server_width");b.aH=N(a,"server_height");b.aL=N(a,"lineId");if(a.G)a=a.G,b.aV=a.mc,b.ao=a.Qb,b.aS=N(a.Na,"siteId"),b.exclude=a.mb,b.am=a.kb,b.aR=a.Pb;return b}
K.prototype.ma=function(){if(!this.rb){var a=this.P,b={};b.campaignId=E("data-cb-campaign-id",a)||"";b.creativeId=E("data-cb-creative-id",a)||"";b.placementId=E("data-cb-placement-id",a)||"";b.server_height=E("data-cb-creative-height",a)||"";b.server_width=E("data-cb-creative-width",a)||"";b.lineId=E("data-cb-line-id",a)||"";b.roadblock=E("data-cb-roadblock",a)||"";this.G&&this.G.ma(b,a);if(E("data-cb-no-refresh",a))this.xb=h;ma(b,this.F)||this.$a(b)}};
K.prototype.refresh=function(){this.da.terminate();this.G&&this.G.refresh();this.q()};K.prototype.terminate=function(){this.da&&this.da.ba();this.F=this.Q=this.P=i;this.Pa&&this.Pa.dispose();this.G&&this.G.ba()};var P={};P.xc=function(){try{P.create("_cb_test","1",1);var a=P.D("_cb_test");P.remove("_cb_test");return a==="1"}catch(b){return j}};P.D=function(a){a+="=";var b="";q(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),j});return b};
P.create=function(a,b,c){var d=l._sf_async_config;if(d&&d.noCookies)return"";d=new Date;d.setTime(r()+c*1E3);a=a+"="+b+("; expires="+d.toGMTString())+"; path=/";return document.cookie=a};P.remove=function(a){return P.D(a)?P.create(a,"",-86400):""};var Q={};Q.J=function(a){var b=l._sf_async_config;if(!a&&b&&b.noCookies)return i;if(Q.J.lb!==g)return Q.J.lb;var a=r()+"",c,d;try{if((d=l.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return Q.J.lb=d}catch(e){}return Q.J.lb=i};Q.D=function(a){var b=Q.J();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&r()>c)?(Q.remove(a),""):b.getItem(a)||""};
Q.create=function(a,b,c){var d=Q.J();if(d){var e=new Date;e.setTime(r()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",e.getTime())}catch(f){}}};Q.remove=function(a){var b=Q.J();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function Kb(a){this.Wa=a||"";this.zc=Q.J()!==i||P.xc();this.Gb=j;Lb(this)}k=Kb.prototype;k.isSupported=function(){return this.zc};
function Lb(a){if(!P.D("_cb_ls")){var b=Q.J()!==i,c=P.D("_SUPERFLY_lockout");c&&q(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_lockout",c,600,h)});var d=P.D("_chartbeat3");d&&(a.create("_v__chartbeat3",d,34128E3,h),P.remove("_chartbeat3"));b&&((b=P.D("_chartbeat2"))&&a.create("_chartbeat2",b,34128E3,h),(b=P.D("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,34128E3,h),(b=P.D("_chartbeat5"))&&a.create("_chartbeat5",b,60,h));P.create("_cb_ls","1",34128E3)}}
function Mb(a){var b=a.Gb;a.Gb=j;return b}k.create=function(a,b,c,d){a=d?a:this.Wa+a;(Q.J()?Q:P).create(a,b,c);Q.J()&&P.create(a,b,c)};k.update=function(a,b,c,d,e,f,n){a=d?a:this.Wa+a;e=B(e)?e:"::";d=(d=this.D(a,h))?d.split(e):[];if(n&&d.length){var p=n(b),o=oa(d,function(a){return n(a)===p});o!==-1&&d.splice(o,1)}d.push(b);for(y(f)&&d.length>f&&d.splice(0,d.length-f);d.length>1&&d.join(e).length>4E3;)d.shift();this.create(a,d.join(e),c,h)};
k.D=function(a,b){var a=b?a:this.Wa+a,c=(Q.J()?Q:P).D(a);if(!c&&Q.J()&&(c=P.D(a))&&P.D("_cb_ls")){this.Gb=h;var d;switch(a){case "_SUPERFLY_lockout":d=600;break;case "_chartbeat4":d=60;break;case "_cb_cp":d=60;break;case "_chartbeat3":d=34128E3;break;default:d=34128E3}Q.create(a,c,d)}return c};k.remove=function(a,b){a=b?a:this.Wa+a;(Q.J()?Q:P).remove(a);Q.J()&&P.remove(a)};function Nb(a){var b=i;if(a&&(b=Ob()))return b;var c=l.location,b=R(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),d=/&utm_[^=]+=[^&]+/ig;(c=d.exec(c.search))&&(a=a.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(c=d.exec(a))&&(a=a.replace(d,c[1]!=""?"?"+c[1]:""));return b+a}function Ob(){var a=i;q(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=hb(b.href),a=R(b.pathname)+b.search+b.hash,j});return a}
for(var Pb={},Qb=0;Qb<81;Qb++)Pb["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(Qb)]=h;function Rb(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return Pb[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function R(a){if(!B(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,Rb);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function S(a,b){var c=T();return t(b)&&!t(c[a])?b:c[a]}function T(){t(l._cb_shared)||(l._cb_shared={});return l._cb_shared};function Sb(a,b){yb.call(this,a,b)}m(Sb,yb);Sb.prototype.q=function(){this.ga=this.N=0;this.aa=i;this.Fb=F.M("x",this.Ea,this);this.Ea(J.Hc())};Sb.prototype.Ea=function(a){va(this.aa);this.aa=i;if(a===J.sc.La)this.aa=ua(this.Xb,1E3)};function U(){H.call(this);this.sa=[];this.H=new Kb(this.lc);this.H.remove("_SUPERFLY_nosample");this.O=new yb;this.pa=new Sb;this.Ab=s(this.wa,this);v(l,"unload",this.Ab);cb(s(this.q,this))}m(U,H);k=U.prototype;k.Za=h;
k.q=function(){U.U.q.call(this);this.Ra=this.ha=0;this.ka=r();this.ya=ga(Tb(this));this.xa=h;this.wb=72E5;if(this.Za){var a=+this.k.sessionLength;if(!isNaN(a))this.wb=a*6E4}a=S("d");if(!a){var a=[],b=this.H.D("_chartbeat2",h);b.length>0&&(a=b.split("."));a.length>4&&(a=[]);var b=r(),c=b-+(a[1]||0),d=b-+(a[2]||0),c=a[0]&&c>18E5&&d<2592E6?0:1;T().n=c;var d="1",e=a&&+a[2],c=a&&a[3];if(a&&e&&c)if(d=Math.abs((ka(b)-ka(e))/864E5)){d=Math.min(d,16)-1;for(e="";d--;)e+=0;d=(c+e+"1").slice(-16)}else d=c;c=
d;a[0]||(a[0]=this.k.utoken||ga(Tb(this),3),a[1]=b);a[2]=b;a[3]=c;this.k.utoken=this.na;this.H.create("_chartbeat2",a.join("."),34128E3,h);T().d=a}this.rd=a.join(".");var f;c=+a[1];d=+a[2];if((b=a[3])&&c&&d)f=(Math.min((Math.abs((ka(d)-ka(c))/864E5)||0)+1,16,b.length)-1).toString(16),f+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.Vb=f;this.Tc=S("n",1);this.na=a[0];this.O.q();this.pa.q();J.q();G.q();Ra||(Sa=ab(),Ta&&l.document.addEventListener&&l.document.addEventListener(Ta,bb,j),$a("focus",
"onfocusin",Ya),$a("blur","onfocusout",Za),Sa&&Ya(),Ra=h);this.Ha=0;this.ib=F.M(Qa,this.zb,this)};k.oa=function(){if(!this.H.D("_SUPERFLY_lockout")&&!Wa)this.Sc?this.ab():(this.Sc=h,!l._sf_async_config&&!l._cbq?(this.Va=s(this.ab,this),v(l,"load",this.Va)):this.ab())};k.ab=function(){var a=l._sf_startpt,b=l._sf_endpt;if(y(a))this.Bb=y(b)?b-a:r()-a;G.q();a=s(this.Ia,this);this.Yb=ua(a,15E3);this.Ia()};
k.Ia=function(){var a=this.O.ga,a=this.k.reading&&+this.k.reading||a>0;if(this.Ra<this.ha&&!a)this.Ra++;else{var b;if(sa===g)b=l.navigator.userAgent,sa=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=sa;b&&!a?this.Ra++:(a?this.ha=0:Ub(this),this.Ra=0,this.sa.push(0),this.sa.length>18&&this.sa.shift(),this.Za&&r()-this.ka>=this.wb?this.terminate():this.ca())}};
function Vb(a){var b={};b.g=a.k.uid;b.g0=nb(a.k,"sections");b.g1=nb(a.k,"authors");b.g2=nb(a.k,"zone");b.g3=nb(a.k,"sponsorName");b.g4=nb(a.k,"type");!a.k.noCookies&&a.H.isSupported()?b.n=a.Tc:b.nc=1;b.c=Math.round((r()-a.ka)/600)/100;b.E=a.O.N;b.EE=a.pa.N;var c=Wb(a);a.Ha=Math.max(a.Ha,c);b.x=c;b.m=a.Ha;b.y=Fa("Height");b.o=Fa("Width");b.w=Ea();b.b=a.Bb?a.Bb:"";if(a.Vb)b.f=a.Vb;b[""]=ob(a.k);b.t=a.ya;b.V=78;b.tz=(new Date).getTimezoneOffset();b.sn=a.Cb;return b}
k.gc=function(){this.sa.push(1);var a=0;q(this.sa,function(b){a+=b});a<3?(this.xa=h,Ub(this)):(this.terminate(),this.H.create("_SUPERFLY_lockout","1",600))};k.wa=function(){};k.zb=function(){var a=Wb(this);this.Ha=Math.max(this.Ha,a)};function Wb(a){return Ca("Y","Top",!!a.k.scrollElement)}function Ub(a){var b=a.ha,b=b?Math.min(b*2,16):1;a.ha=b}k.ra=function(){this.wa();this.terminate()};k.bb=function(){this.q();this.oa()};
function Xb(a){if(a.k.virtualReferrer)return h;a=(document.referrer||"").indexOf("://"+l.location.hostname+"/");return a!=-1&&a<9}function Yb(a){a=a.k.virtualReferrer;if(!a&&(a=document.referrer||"")){var b=hb(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=R(b.pathname),a=ib(b)}return encodeURIComponent(a)}function Zb(a){a=a.k.title.slice(0,100);return encodeURIComponent(a)}function Tb(a){a=[Yb(a),Fa("Width"),Fa("Height")];return ia(a)}
function $b(a){var b=[],c=a.H.D("_chartbeat4");c&&(q(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.H.remove("_chartbeat4"));return b}k.terminate=function(){this.O.terminate();this.pa.terminate();F.T(this.ib);this.Va!==g&&ja("load",this.Va);va(this.Yb);T().d=g;T().n=g};k.ba=function(){this.terminate();ja("unload",this.Ab);this.Ab=this.Va=this.H=this.sa=this.k=i;this.O.ba();this.O=i;this.pa.ba();this.pa=i;U.U.ba.call(this)};function V(){this.Db=[];this.lc="_p_";this.Za=this.Zb=j;v(l,"beforeunload",s(this.Wc,this));U.call(this)}m(V,U);
V.prototype.q=function(){V.U.q.call(this);var a=l.location;I(this.k,"pingServer","ping.chartbeat.net");I(this.k,"title",document.title);I(this.k,"domain",a.hostname);this.k.domain=u(this.k.domain);I(this.k,"domainAd",this.k.domain);I(this.k,"path",Nb(!!this.k.useCanonical));I(this.k,"engaged",j);this.ea=this.k[kb]||"data-cb-ad-id";this.ta=this.$b=0;this.Gc=function(){var a=r()-this.$b;if(a<500){this.ta&&D(this.ta);var c=s(this.ca,this);this.ta=wa(c,500-a)}else this.xa||this.ca()};this.Fc=F.M("p",
this.Gc,this);this.hd=F.M("z",this.dd,this);if(this.k.krux&&!this.Zb)ea("http://beacon.krzd.net/usermatch.gif?partner=chartbeat&partner_uid="+this.na),this.Zb=h;this.Db=[]};V.prototype.Wc=function(){ac(this);this.ca(h)};V.prototype.wa=function(){this.H.update("_chartbeat4",["t="+this.ya,"E="+this.O.N,"ad="+la(bc(this,h)),"x="+Wb(this),"c="+Math.round((r()-this.ka)/600)/100,"y="+Fa("Height"),"w="+Ea()].join("&"),60,g,g,1)};function cc(a){return encodeURIComponent("ads."+a.k.domainAd)}
function bc(a,b){var c=[];a.Aa&&q(a.Aa.X,function(a){a=Gb(a);(!b||!(a.aw<=1&&a.ah<=1))&&c.push(Db(a))});return c.concat(a.Db).join("&")}var dc="h,p,u,d,g,g0,g1,g2,g3,g4,n,nc,f,c,x,m,y,o,w,j,E,v,r,vp,b,t,V,i,tz,l,,ad,z,zz,sn".split(",");k=V.prototype;
k.ca=function(a){this.Cb++;var b=Vb(this),c=l.location;b.h=cc(this);b.p=encodeURIComponent(this.k.path);b.u=this.na;b.d=la(u(c.hostname));Xb(this)?b.v=Yb(this):b.r=Yb(this);b.ad=la(bc(this));this.$b=r();this.ta&&D(this.ta);Nb(!!this.k.useCanonical);if(this.xa)this.xa=j,b.i=Zb(this);this.k.virtualReferrer&&(b.vp=1);var c=this.k.pingServer,d=0;a?b.zz=1:(b.z=$b(this),d=Math.round((this.ha+2)*15E3/1E3));b.j=d;b.l=Mb(this.H)?1:"";this.O.ga=0;this.Ka("https://"+c+"/ping/ad?"+gb(b,dc))};
k.zb=function(){V.U.zb.call(this);ec(this.Aa)};k.Xa=function(a,b){a.G.Pb=b;var c=Gb(a);this.Db.push(Db(c));a.refresh()};k.dd=function(a,b){for(var c=qa(this.H.D("_chartbeat7")),d=parseInt(c[a.vzcid],10)||0,e={1:h,5:h,15:h,30:h,60:h,100:h};b--;)if(d++,e[d+""]){var f=a,n=d+"second"+(d!==1?"s":""),p=ga(fa());ea("http://ohlone.vizu.com/a.gif?vzcid="+f.vzcid+"&vzadid="+n+"&vzsid="+f.vzsid+"&ord="+p)}c[a.vzcid]=d;this.H.create("_chartbeat7",pa(c),7862400)};
function ac(a){a.Aa&&q(a.Aa.X,function(a){if(a.G.Sb)a=a.G,ea("//secure.insightexpressai.com/adServer/cb.gif?bannerid="+a.F.dynamicLogic+"&siteID="+a.F.siteId+"&placementID="+a.F.placementId+"&creativeID="+a.F.creativeId+"&inViewTime="+a.Na.da.N+"&vendor=cb")})}k.terminate=function(){F.T(this.Fc);F.T(this.hd);this.Qa&&F.T(this.Qa);D(this.ta);V.U.terminate.call(this)};function fc(){this.X=[];this.k=l._sf_async_config||{};this.ea=this.k[kb]||"data-cb-ad-id";"postMessage"in window&&v(window,"message",s(this.Pc,this));if(jb()>0){var a=s(this.Ma,this);T().a=a;var a="ad_debug",b="//static.chartbeat.com";La()&&(b="//static2.chartbeat.com");b=[b,"js"];La()&&(a+="dev");b.push("chartbeat_"+a+".js");Ka(b.join("/"))}this.Ya=[];cb(s(this.q,this))}k=fc.prototype;
k.q=function(a){this.k=l._sf_async_config||{};a?this.B.q():(this.B=new V,this.B.Aa=this);this.Ba={};this.Ga=0;if((a=this.k.engagedAdFilters)&&a.length){var b=this;q(a,function(a){b.Oa(a)})}this.ma();this.Qa=F.M("e",this.Bc,this);try{l.googletag.pubads().addEventListener("slotRenderEnded",s(this.Lc,this))}catch(c){}};k.Lc=function(a){if(this.Ya.length)try{q(this.Ya,s(function(b,d){var e=b.pb;a.slot===e&&(e.setTargeting("_cbr",gc),b.ob>=100||(b.ob+=1),this.Ya.splice(d,1))},this))}catch(b){}};
function hc(){var a=Aa("id^=google_ads_iframe","div");return na(a,function(a){return a.parentNode})}function ic(a){var b=j;q(a.X,function(a){if(a.Ta)return b=h,j});return b}k.Ma=function(a,b){var c=xa(F,Pa),d=xa(J,xb),e=s(function(){return{engagedAdFilters:this.Ba,maxEngagedAdSpecificity:this.Ga}},this);a.injectDependencies(c,d,e);b.injectDependencies(c);this.Rb=new a;Fb=b;q(this.X,function(a){a.Ma()})};
function ec(a){var b=Aa(a.ea,"div");b.length||(b=hc());b=Aa(a.B.ea,"div");q(b,function(b){if(!jc(a,b)){var d=new K(b);d.G=new zb;d.G.Na=d;a.X.push(d);d.ma();if(b=E("data-cb-engaged-seconds",b))d=Jb(d),d[O]=parseInt(b,10),a.Oa(d)}})}function jc(a,b){var c;q(a.X,function(a){if(a.qa===b||a.P===b)return c=a,j});return c}
k.ma=function(){var a=S("c"),b=this;ec(b);q(b.X,function(c){c.ma();var d=c.qa;if(a&&a[d]){var e=-1;q(a[d],function(a,d){if(a.e===c.P)return a.c(b.B?b.B.ya:"1",b.B?cc(b.B):"1"),e=d,j});e>-1&&a[d].splice(e,1)}})};k.Pc=function(a){this.bc(B(a.data)?qa(a.data):{},a.source)};
k.bc=function(a,b){if(a.cbType!=="campaignMessage")return j;var c=b;if(c.parent!=window){for(var d=0;c.parent!=window&&d<10;)c=c.parent,d++;if(d>=10)return j}ec(this);var d=document.getElementsByTagName("iframe"),e=g;q(d,function(a){if(a.contentWindow===c)return e=a,j});if(!e)return j;var f,n,d=this.B?this.B.ea:"id^=google_ads_iframe";f=e.getAttribute(d);n=e;if(f===i){n=Ba(e,d);if(!n)return j;f=n.getAttribute(d)}var p=g;q(this.X,function(a){if(f===a.qa&&n===a.P)return p=a,j});if(p===g)return j;p.$a(a,
e);if(d=a[O]){var o=Jb(p);o[O]=parseInt(d,10);this.Oa(o)}d=["cbdata::ack",this.B?this.B.ya:"1",this.B?cc(this.B):"1"].join("::");"postMessage"in b&&b.postMessage(d,"*");return d};
k.Oa=function(a){if(a&&y(a[O])&&!isNaN(a[O])){var b={};q(Ib,function(c){if(B(a[c])||c===O)b[c]=a[c]});var c=ya(b).length;this.Ga=Math.max(this.Ga,c);this.Ba[c]=this.Ba[c]||[];var c=this.Ba[c],d=j;q(c,function(a){var c=h;q(a,function(a,d){if(d!==O)return c=b[d]===a});(d=c)&&(a[O]=b[O]);return!d});d||c.unshift(b);this.Rb&&this.Rb.update()}};k.oa=function(){this.B.oa()};
k.Xc=function(a,b){if(!a)return j;var c=l.document.getElementById(b);if(!c)return j;var d;c.getAttribute(this.B.ea)&&(d=jc(this,c));var e=this;if(!d){var f=Aa(this.B.ea,"div",c);q(f,function(a){if(d=jc(e,a))return j})}d||(c=Ba(c,this.B.ea))&&(d=jc(this,c));if(!d)return j;d.pb=a;return h};
k.Bc=function(a){if(a&&this.Ga!==0){var b=a.pb,c=this.k.engagedAdCallback;b&&!c&&(c=ta);if(c)for(var d=this,e=Jb(a),f=e[O],n=this.Ga,p=j;n>0&&!p;)q(this.Ba[n]||[],function(o){p=h;q(o,function(a,b){if(b!==O)return p=a===e[b]});if(p){o=o[O];if(o===-1)return j;if(o===f)e.element=a.P,c(e,f),b&&a.xb==j&&(a.vb?kc(d,a):lc(d,a));return j}}),n--}};k.Xa=function(a){if(a&&(a=jc(this,a)))this.B.Xa(a,1),a.G.kb=1};var gc="0";
function lc(a,b){a.B.Xa(b,2);var c=b.pb;try{c.setTargeting("_cbr",b.ob),a.Ya.push(b),l.googletag.pubads().refresh([c]),b.G.kb=2}catch(d){}}function kc(a,b){(b.Ta||!ic(a))&&q(a.X,function(b){b.vb&&lc(a,b)})}fc.prototype.ra=function(){this.B.wa();this.terminate()};fc.prototype.bb=function(){this.q(h);this.B.oa()};fc.prototype.terminate=function(){this.ib&&F.T(this.ib);this.B&&this.B.terminate();this.Qa&&F.T(this.Qa);q(this.X,function(a){a.terminate()});this.X=[];this.k=i};if(!l.pSUPERFLY_pub){var X=new fc,mc={addEngagedAdFilter:s(X.Oa,X),refreshAd:s(X.Xa,X),updateCampaignData:s(X.ma,X),registerGptSlot:s(X.Xc,X)};mc.evps=s(X.ra,X);mc.svps=s(X.bb,X);"postMessage"in window!==h&&(mc.loadCampaign=s(X.bc,X));l.pSUPERFLY_pub=mc;X.oa()};function nc(a){for(var b=S("m")||[];b.length;)a(b.shift());a={push:a};T().m=a};function oc(){var a=l.location.href,a=a.replace(/-{2,}/g,"-"),a=hb(a);a.pathname=R(a.pathname);return a}
function pc(a){var b=P.D("_chartbeat6");if(!b)return i;var b=b.split("::"),c,d;if(b.length===1)c=b[0].split(","),d=0;else{var e,f=oc(),n=ib(f);q(b,function(a,b){var f=a.split(","),o=ra(n,decodeURIComponent(f[0]));if(o===0)return c=f,d=b,j;if(e===g||o<e)e=o,c=f,d=b})}b.splice(d,1);a="_chartbeat6="+b.join("::")+qc(a);document.cookie=a;var a=[],b=decodeURIComponent(c[0]),f=decodeURIComponent(c[1]),p=c[2];c.splice(0,3);for(var o=c.length/2,w=0;w<o;w++)a.push({pd:b,origin:f,va:p,Cc:c[w*2],ed:c[w*2+1]});
return a}function qc(a){var b="",c;if(!C(a))return b;a.ec&&(c=new Date,c.setTime(c.getTime()+a.ec),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function rc(a){var b=a.topStorageDomain,a=a.domain,c=l.location.hostname;return b?b:sc(c,a)?a:c.replace(/^www\./,"")}function sc(a,b){if(a===b)return h;for(var c=b.split("."),d=a.split(".");c.length;){if(d.length===0)return j;if(c.pop()!==d.pop())return j}return h}
function tc(a,b,c,d){this.Ec=a;this.Dc=b;this.fd=c;this.va=d};function uc(a,b){for(var c=b||document.documentElement,d=[],e=i,f=a,n,p,o,w,z,L;f&&f!==c;){n=f.nodeName.toLowerCase();e=f;p=e.nodeName;if((f=f.parentNode)&&f!==document.documentElement){o=f.children;w=0;for(z=0,L=o.length;z<L;z++){if(e===o[z]){n+="["+(1+z-w)+"]";break}o[z].nodeName!==p&&w++}}d.unshift(n)}return d.join("/")};function vc(){this.lc="_t_";U.call(this)}m(vc,U);k=vc.prototype;
k.q=function(){vc.U.q.call(this);mb(this.k);var a=l.location;I(this.k,"mabServer","mabping.chartbeat.net");I(this.k,"title",document.title);I(this.k,"domain",a.hostname);I(this.k,"path",Nb(!!this.k.useCanonical));this.Fa=u(a.hostname);this.k.domain=u(this.k.domain);this.bd=rc(this.k);this.Ca=this.Sa=j;this.Ub=[];var b=this,a=pc({domain:"."+this.bd,ec:6E4,path:"/"});if(a!==i)this.Sa=h,q(a,function(a){b.Ub.push(new tc(a.origin,a.Cc,a.ed,a.va))});this.fc=0;this.cb=i;nc(s(this.Qc,this))};
k.ca=function(){var a=this.O.N,b=wc(this),c,d=this;this.Sa&&q(this.Ub,function(e){c=b+"&x="+e.Dc+"&v="+e.fd+"&ml="+e.va+"&xo="+e.Ec+"&e="+a;d.Ka(c)});!this.Ca&&this.cb&&xc(this,this.cb);this.Ca=h};k.ab=function(){var a=l._sf_startpt,b=l._sf_endpt;if(y(a))this.Bb=y(b)?b-a:r()-a;G.q();if(this.Sa)a=s(this.Ia,this),this.Yb=ua(a,500);this.Ia()};k.Ia=function(){var a,b;this.Ca?(a=this.O.N,b=this.fc*15,a-b>=15&&(this.ca(),this.fc+=1),a>=45&&this.terminate()):this.ca()};
function wc(a){var b=a.k;return(l.location.protocol||"http:")+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&d="+encodeURIComponent(a.Fa)+"&u="+a.na+"&c="+Math.round((r()-a.ka)/600)/100}k.wa=function(){};k.$c=function(a){var b=a.d,c=i;b!==i&&(c={jc:b.s,va:b.g,dc:b.m});a={status:a.s,data:c,code:a.c,message:a.m};this.Ca?xc(this,a):this.cb=a};
function xc(a,b){var c=wc(a),d=b.status,e=b.data;if(d=="s"&&e!==i){var f=s(a.Ka,a);C(e.jc)&&q(e.jc,function(a,b){f(c+"&x="+b+"&v="+a+"&ml="+e.va+"&e=-1")});Object.prototype.toString.call(e.dc)==="[object Array]"&&q(e.dc,function(a){f(c+"&me=3&ml="+e.va+"&x="+a)})}else d=="e"&&a.Ka(c+"&me="+b.code)}k.Qc=function(a,b){for(var c=0,d=arguments.length;c<d;c++){var a=arguments[c],e=a.shift();e==="t"?this.$c.apply(this,a):e==="v"&&this.Zc.apply(this,a)}};k.ra=function(){T().m=[];t(this.Jb)&&this.Jb();vc.U.ra.call(this)};
k.Zc=function(a){this.Jb=a};k.terminate=function(){this.Jb=this.qd=g;this.cb=i;this.Ca=this.Sa=g;vc.U.terminate.call(this)};if(!l.pSUPERFLY_mab){var yc=new vc,Ac={};Ac.evps=s(yc.ra,yc);Ac.svps=s(yc.bb,yc);l.pSUPERFLY_mab=Ac;yc.oa()};var Bc,Cc,Dc;function Ec(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0&&(a=a.substr(16),Fc(),a!=="NONE"))){var a=a.indexOf("HUD2.")===0?a.substr(5):"OLD",b="https://static.chartbeat.com/js/inpage.js";a!=="OLD"&&(b="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+a+".js");Ka(b)}}function Fc(){D(Cc);Cc=g;ja("message",Ec);Dc&&Dc.parentNode&&Dc.parentNode.removeChild(Dc);Dc=g};function Gc(){var a=l._sf_async_config&&l._sf_async_config.domain;if(a&&!Bc){Bc=h;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);v(l,"message",Ec);Cc=wa(Fc,1E4);var b=t(g)?g:{};b.src=a;a=Ja("iframe",b);a.style.display="none";t(g)?g.appendChild(a):document.body&&document.body.appendChild(a);Dc=a}}
function Hc(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=Q.J(h),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),Gc(),ja("message",Hc))}};function Y(){"postMessage"in window&&v(l,"message",s(this.Oc,this));U.call(this);lb("_cbq",s(this.hc,this))}m(Y,U);
Y.prototype.q=function(){Y.U.q.call(this);var a=this.na;T().u=a;a=this.ya;T().t=a;this.jb=i;mb(this.k);a=l.location;I(this.k,"pingServer","ping.chartbeat.net");I(this.k,"title",document.title);I(this.k,"domain",a.hostname);this.k.path=this.k.path?R(this.k.path):Nb(!!this.k.useCanonical);this.Fa=u(a.hostname);this.k.domain=u(this.k.domain);this.vc=F.M("c",this.Uc,this);this.wc=F.M("r",this.Vc,this);this.ua=i};Y.prototype.tc=function(a){this.jb=a};
Y.prototype.wa=function(){this.H.update("_chartbeat4",["t="+this.ya,"E="+this.O.N,"EE="+this.pa.N,"x="+Wb(this),"c="+Math.round((r()-this.ka)/600)/100,"y="+Fa("Height"),"w="+Ea()].join("&"),60,g,g,1)};var Ic="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,t,V,z,i,L,tz,l,,sn,C,eS,eM,eD,eK,eR,EE".split(",");k=Y.prototype;
k.ca=function(a){this.Cb++;var b=Vb(this),c=this.O.ga;b.h=encodeURIComponent(this.k.domain);b.p=encodeURIComponent(this.k.path);b.u=this.na;b.d=encodeURIComponent(this.Fa);b.j=Math.round((this.ha+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;var d=b.c*6E4+this.ka;b.eD=G.Da("mousedown",d);b.eM=G.Da("mousemove",d);b.eK=G.Da("keydown",d);b.eR=G.Da("resize",d);b.eS=G.Da("scroll",d);G.Yc();G.uc()?b.W=1:this.k.reading&&+this.k.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=Xb(this);if(this.xa){this.xa=j;if(c)this.ua=Jc(this);
b.i=Zb(this);d=this.k.hudTrackable;d!==g&&(b.L=d?"1":"0");this.k.alias&&(b.PA=encodeURIComponent(this.k.alias))}if(c){if(this.ua){if(b.v=encodeURIComponent(this.ua.path),b.K=Kc(this.ua),this.ua.yb>1)b.l1=this.ua.yb}else b.v=Yb(this);this.k.virtualReferrer&&(b.vp=1)}else b.r=Yb(this);c=za(b.v);T().v=c;c=za(b.r);T().r=c;b.A=this.jb?this.jb:"";b._c=eb("utm_campaign",this.k.campaignTag);b._m=eb("utm_medium",this.k.mediumTag);b.z=$b(this);b.C=this.k.mobileApp?1:"";b.KK=a?Kc(a):"";b.l=Mb(this.H)?1:"";this.O.ga=
0;this.Ka((l.location.protocol||"http:")+"//"+this.k.pingServer+"/ping?"+gb(b,Ic))};
k.Oc=function(a){var b=this.k;if(a.origin==="http://"+(b.playerdomain||this.Fa)){var c=a.data;if(B(c)&&c.indexOf("cbqpush::")===0)a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.hc(a));else if(c=="cbdata?"){var c="&u="+S("u"),d="&t="+S("t"),e="&v="+S("v"),f="&r="+S("r"),b="domain="+encodeURIComponent(b.domain)+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b.path)+"&title="+Zb(this)+"&referrer="+Yb(this)+"&internal="+(Xb(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.Fa)+
c+d+e+f+"&utoken="+this.na;a.source.postMessage(b,"*")}}};k.hc=function(a){a[0]==="_demo"&&this.k._demo?this.k._demo=this.k._demo+"%2C"+a[1]:this.k[a[0]]=a[1];this.ha=0};function Lc(a){a=a.replace(/-{2,}/g,"-");a=hb(a);a.pathname=R(a.pathname);return a}k.Uc=function(a){Mc(this,a,"c")};k.Vc=function(a){Mc(this,a,"r")};
function Mc(a,b,c){if(a.Za&&r()-a.ka>=a.wb)a.terminate();else{var d=b.href||"",d=Lc(d);if(d.protocol.indexOf("http")===0){var e=d.hostname!==l.location.hostname,d=ib(d),f=Ga(b,function(a){return a.id}),n=uc(b,f),p;f?(n&&(n="/"+n),n="*[@id='"+f.id+"']"+n,p=uc(b)):p=n;f=ga(n);p=ga(p);b=ub(b,g,h);c={left:b.x,top:b.y,path:a.k.path,href:d,Mb:f,hb:p,Lb:n,Eb:c,yb:0};a.ca(c);e||a.H.update("_chartbeat5",Nc(c),60,j,g,5,function(a){a=a.split(",");return a[2]+","+a[3]})}}}
function Kc(a){return[a.left,a.top,a.Mb,encodeURIComponent(a.Lb),a.Eb,encodeURIComponent(a.href),a.hb].join("::")}function Nc(a){var b=encodeURIComponent(a.Lb),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.Mb,b,a.Eb,a.hb].join(",")}
function Jc(a){var b=a.H.D("_chartbeat5");if(!b)return i;var c=b.split("::"),b=c.length,d,e;if(b===1)d=c[0].split(","),e=0;else{var f,n=Lc(l.location.href),p=ib(n);q(c,function(a,b){var c=a.split(","),n=ra(p,decodeURIComponent(c[3]));if(n===0)return d=c,e=b,j;if(f===g||n<f)f=n,d=c,e=b})}c.splice(e,1);a.H.create("_chartbeat5",c.join("::"),60);(a=d[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),href:decodeURIComponent(d[3]),Mb:d[4]||
"",Lb:a,hb:d.length>7?d[7]:"",Eb:d.length>6?d[6]:"c",yb:b}}k.terminate=function(){F.T(this.vc);F.T(this.wc);Y.U.terminate.call(this)};if(!l.pSUPERFLY){var Oc=new Y,Pc={};l.pSUPERFLY=Pc;var Qc=l.pSUPERFLY_mab,$=l.pSUPERFLY_pub,Rc=[];Qc&&Rc.push(Qc);if($)Rc.push($),$.addEngagedAdFilter&&(Pc.addEngagedAdFilter=$.addEngagedAdFilter),$.refreshAd&&(Pc.refreshAd=$.refreshAd),$.registerGptSlot&&(Pc.registerGptSlot=$.registerGptSlot),lb("_cba",function(a){a()});Pc.virtualPage=function(a,b){if(!Wa){var c=l._sf_async_config;c.virtualReferrer=l.location.protocol+"//"+c.domain+c.path;c.path=R(a);b&&(c.title=b);Oc.ra();q(Rc,function(a){a.evps()});
Oc.bb();q(Rc,function(a){a.svps()})}};Pc.activity=s(Oc.tc,Oc);Oc.oa();var Sc=Q.J(h);if(Sc)if(Sc.getItem("_cb_ip")){var Tc=l.location;(!/^(.+[.])?chartbeat\.com$/.test(Tc.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(Tc.pathname))||Gc()}else v(l,"message",Hc)};})();
