STRUQ=STRUQ||{};
(function(a){function b(){this.list=this.next=null}function c(){this.n=this.b=this.e=0;this.t=null}function d(a,d,f,e,g,h){this.BMAX=16;this.N_MAX=288;this.status=0;this.root=null;this.m=0;var l=Array(this.BMAX+1),m,n,p,r,k,v,w,q=Array(this.BMAX+1),y,t,x,u=new c,z=Array(this.BMAX);r=Array(this.N_MAX);var C,E=Array(this.BMAX+1),D,A,G;G=this.root=null;for(k=0;k<l.length;k++)l[k]=0;for(k=0;k<q.length;k++)q[k]=0;for(k=0;k<z.length;k++)z[k]=null;for(k=0;k<r.length;k++)r[k]=0;for(k=0;k<E.length;k++)E[k]=
0;m=256<d?a[256]:this.BMAX;y=a;t=0;k=d;do l[y[t]]++,t++;while(0<--k);if(l[0]==d)this.root=null,this.status=this.m=0;else{for(v=1;v<=this.BMAX&&0==l[v];v++);w=v;h<v&&(h=v);for(k=this.BMAX;0!=k&&0==l[k];k--);p=k;h>k&&(h=k);for(D=1<<v;v<k;v++,D<<=1)if(0>(D-=l[v])){this.status=2;this.m=h;return}if(0>(D-=l[k]))this.status=2,this.m=h;else{l[k]+=D;E[1]=v=0;y=l;t=1;for(x=2;0<--k;)E[x++]=v+=y[t++];y=a;k=t=0;do 0!=(v=y[t++])&&(r[E[v]++]=k);while(++k<d);d=E[p];E[0]=k=0;y=r;t=0;r=-1;C=q[0]=0;x=null;for(A=0;w<=
p;w++)for(a=l[w];0<a--;){for(;w>C+q[1+r];){C+=q[1+r];r++;A=(A=p-C)>h?h:A;if((n=1<<(v=w-C))>a+1)for(n-=a+1,x=w;++v<A&&!((n<<=1)<=l[++x]);)n-=l[x];C+v>m&&C<m&&(v=m-C);A=1<<v;q[1+r]=v;x=Array(A);for(n=0;n<A;n++)x[n]=new c;G=null==G?this.root=new b:G.next=new b;G.next=null;G.list=x;z[r]=x;0<r&&(E[r]=k,u.b=q[r],u.e=16+v,u.t=x,v=(k&(1<<C)-1)>>C-q[r],z[r-1][v].e=u.e,z[r-1][v].b=u.b,z[r-1][v].n=u.n,z[r-1][v].t=u.t)}u.b=w-C;t>=d?u.e=99:y[t]<f?(u.e=256>y[t]?16:15,u.n=y[t++]):(u.e=g[y[t]-f],u.n=e[y[t++]-f]);
n=1<<w-C;for(v=k>>C;v<A;v+=n)x[v].e=u.e,x[v].b=u.b,x[v].n=u.n,x[v].t=u.t;for(v=1<<w-1;0!=(k&v);v>>=1)k^=v;for(k^=v;(k&(1<<C)-1)!=E[r];)C-=q[r],r--}this.m=q[1];this.status=0!=D&&1!=p?1:0}}}function g(a){for(;q<a;){var b=A,d;d=G.length==H?-1:G.charCodeAt(H++)&255;A=b|d<<q;q+=8}}function h(a){return A&P[a]}function f(a){A>>=a;q-=a}function m(a,b,d){var c,e,l;if(0==d)return 0;for(l=0;;){g(D);e=v.list[h(D)];for(c=e.e;16<c;){if(99==c)return-1;f(e.b);c-=16;g(c);e=e.t[h(c)];c=e.e}f(e.b);if(16==c)w&=32767,
a[b+l++]=r[w++]=e.n;else{if(15==c)break;g(c);y=e.n+h(c);f(c);g(C);e=I.list[h(C)];for(c=e.e;16<c;){if(99==c)return-1;f(e.b);c-=16;g(c);e=e.t[h(c)];c=e.e}f(e.b);g(c);E=w-e.n-h(c);for(f(c);0<y&&l<d;)y--,E&=32767,w&=32767,a[b+l++]=r[w++]=r[E++]}if(l==d)return d}t=-1;return l}function e(a,b,c){var e,l,k,n,r,p,w,q=Array(316);for(e=0;e<q.length;e++)q[e]=0;g(5);p=257+h(5);f(5);g(5);w=1+h(5);f(5);g(4);e=4+h(4);f(4);if(286<p||30<w)return-1;for(l=0;l<e;l++)g(3),q[J[l]]=h(3),f(3);for(;19>l;l++)q[J[l]]=0;D=7;
l=new d(q,19,19,null,null,D);if(0!=l.status)return-1;v=l.root;D=l.m;n=p+w;for(e=k=0;e<n;)if(g(D),r=v.list[h(D)],l=r.b,f(l),l=r.n,16>l)q[e++]=k=l;else if(16==l){g(2);l=3+h(2);f(2);if(e+l>n)return-1;for(;0<l--;)q[e++]=k}else{17==l?(g(3),l=3+h(3),f(3)):(g(7),l=11+h(7),f(7));if(e+l>n)return-1;for(;0<l--;)q[e++]=0;k=0}D=9;l=new d(q,p,257,K,L,D);0==D&&(l.status=1);if(0!=l.status)return-1;v=l.root;D=l.m;for(e=0;e<w;e++)q[e]=q[e+p];C=6;l=new d(q,w,0,M,N,C);I=l.root;C=l.m;return 0==C&&257<p||0!=l.status?-1:
m(a,b,c)}function p(a,b,c){var l,k;for(l=0;l<c&&(!u||-1!=t);){if(0<y){if(0!=t)for(;0<y&&l<c;)y--,E&=32767,w&=32767,a[b+l++]=r[w++]=r[E++];else{for(;0<y&&l<c;)y--,w&=32767,g(8),a[b+l++]=r[w++]=h(8),f(8);0==y&&(t=-1)}if(l==c)break}if(-1==t){if(u)break;g(1);0!=h(1)&&(u=!0);f(1);g(2);t=h(2);f(2);v=null;y=0}switch(t){case 0:k=a;var p=b+l,G=c-l,F=void 0,F=q&7;f(F);g(16);F=h(16);f(16);g(16);if(F!=(~A&65535))k=-1;else{f(16);y=F;for(F=0;0<y&&F<G;)y--,w&=32767,g(8),k[p+F++]=r[w++]=h(8),f(8);0==y&&(t=-1);k=
F}break;case 1:if(null!=v)k=m(a,b+l,c-l);else a:{k=a;p=b+l;G=c-l;if(null==x){for(var B=void 0,F=Array(288),B=void 0,B=0;144>B;B++)F[B]=8;for(;256>B;B++)F[B]=9;for(;280>B;B++)F[B]=7;for(;288>B;B++)F[B]=8;z=7;B=new d(F,288,257,K,L,z);if(0!=B.status){alert("HufBuild error: "+B.status);k=-1;break a}x=B.root;z=B.m;for(B=0;30>B;B++)F[B]=5;zip_fixed_bd=5;B=new d(F,30,0,M,N,zip_fixed_bd);if(1<B.status){x=null;alert("HufBuild error: "+B.status);k=-1;break a}n=B.root;zip_fixed_bd=B.m}v=x;I=n;D=z;C=zip_fixed_bd;
k=m(k,p,G)}break;case 2:k=null!=v?m(a,b+l,c-l):e(a,b+l,c-l);break;default:k=-1}if(-1==k)return u?0:-1;l+=k}return l}var k={PADCHAR:"=",ALPHA:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",makeDOMException:function(){try{return new DOMException(DOMException.INVALID_CHARACTER_ERR)}catch(a){var b=Error("DOM Exception 5");b.code=b.number=5;b.name=b.description="INVALID_CHARACTER_ERR";b.toString=function(){return"Error: "+b.name+": "+b.message};return b}},getbyte64:function(a,b){var d=
k.ALPHA.indexOf(a.charAt(b));if(-1===d)throw k.makeDOMException();return d},decode:function(a){a=""+a;var b=k.getbyte64,d,c,e,f=a.length;if(0===f)return a;if(0!==f%4)throw k.makeDOMException();d=0;a.charAt(f-1)===k.PADCHAR&&(d=1,a.charAt(f-2)===k.PADCHAR&&(d=2),f-=4);var l=[];for(c=0;c<f;c+=4)e=b(a,c)<<18|b(a,c+1)<<12|b(a,c+2)<<6|b(a,c+3),l.push(String.fromCharCode(e>>16,e>>8&255,e&255));switch(d){case 1:e=b(a,c)<<18|b(a,c+1)<<12|b(a,c+2)<<6;l.push(String.fromCharCode(e>>16,e>>8&255));break;case 2:e=
b(a,c)<<18|b(a,c+1)<<12,l.push(String.fromCharCode(e>>16))}return l.join("")}};window.atob||(window.atob=k.decode);var l={encode:function(a){a=a.replace(/\r\n/g,"\n");for(var b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);128>d?b+=String.fromCharCode(d):(127<d&&2048>d?b+=String.fromCharCode(d>>6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b},decode:function(a){for(var b="",d=0,c=c1=c2=0;d<a.length;)c=a.charCodeAt(d),128>c?(b+=
String.fromCharCode(c),d++):191<c&&224>c?(c2=a.charCodeAt(d+1),b+=String.fromCharCode((c&31)<<6|c2&63),d+=2):(c2=a.charCodeAt(d+1),c3=a.charCodeAt(d+2),b+=String.fromCharCode((c&15)<<12|(c2&63)<<6|c3&63),d+=3);return b}},r,w,x=null,n,z,A,q,t,u,y,E,v,I,D,C,G,H,P=[0,1,3,7,15,31,63,127,255,511,1023,2047,4095,8191,16383,32767,65535],K=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258,0,0],L=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0,99,99],M=[1,2,3,
4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577],N=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13],J=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15],O={};a.JSInflate=O;O.inflate=function(a){var b,d,c;null==r&&(r=Array(65536));q=A=w=0;t=-1;u=!1;y=E=0;v=null;G=a;H=0;b=Array(1024);for(a="";0<(d=p(b,0,b.length));)for(c=0;c<d;c++)a+=String.fromCharCode(b[c]);G=null;return l.decode(a)}})(this);var STRUQ=STRUQ||{};
STRUQ.Utils={};STRUQ.Utils.loadJSFile=function(){};STRUQ.Utils.checkType=function(){};STRUQ.Utils.returnType=function(){};STRUQ.Utils.stringToXML=function(){};STRUQ.Utils.dispatchEvent=function(){};STRUQ.Utils.addEventListener=function(){};STRUQ.Utils.removeEventListener=function(){};STRUQ.Utils.getXMLNodeByAttr=function(){};STRUQ.Utils.filterXMLElementsById=function(){};STRUQ.Utils.setAttributesToElement=function(){};STRUQ.Utils.xmlToObjectAttributes=function(){};STRUQ.Utils.wrapTextToElement=function(){};
STRUQ.Utils.has3D=function(){};STRUQ.Utils.request=function(){};STRUQ.Utils.getDomain=function(){};STRUQ.Utils.getProtocol=function(){};STRUQ.Utils.dropSnippet=function(){};STRUQ.Utils.hexToRGB=function(){};STRUQ.Utils.correctColor=function(){};STRUQ.Utils.isNumber=function(){};STRUQ.Utils.isNumber2=function(){};STRUQ.Utils.canNavigate=function(){};
(function(){STRUQ.Utils=new function(){this.loadJSFile=function(a,b,c){var d=document.createElement("script");d.type="text/javascript";STRUQ.Utils.addEventListener(d,"load",b,null,c);d.src=a;document.getElementsByTagName("body")[0].appendChild(d)};this.stringToXML=function(a){var b;window.ActiveXObject?(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="true",b.loadXML(a)):b=(new DOMParser).parseFromString(a,"text/xml");return b};this.checkType=function(a,b){return Object.prototype.toString.call(a)===
"[object "+b+"]"};this.returnType=function(a,b){return Object.prototype.toString.call(a)};this.dispatchEvent=function(a,b,c){var d;document.createEvent?(d=document.createEvent("Event"),d.identity=b.identity,c&&(d.param=c),d.initEvent(b.type,!0,!1),a.dispatchEvent(d)):document.createEventObject&&(d=document.createEventObject(),d.type=b.type,d.identity=b.identity,c&&(d.param=c),a.fireEvent("on"+b.type,d))};this.addEventListener=function(a,b,c,d,g){c&&(d||(d=!1),a.addEventListener?a.addEventListener(b,
function(a){c(a,g)},d):a.attachEvent&&"load"!=b?a.attachEvent("on"+b,function(a){c(a,g)}):a.attachEvent&&"load"==b&&a.attachEvent("onreadystatechange",function(a){c(a,g)}))};this.removeEventListener=function(a,b,c,d){a.detachEvent?a.detachEvent("on"+b,c):a.removeEventListener&&(d||(d=!1),a.removeEventListener(b,c,d))};this.getXMLNodeByAttr=function(a,b,c,d){function g(a,b,c){for(var p=0;p<a.childNodes.length;p++)if(void 0!==a.childNodes[p].tagName&&a.childNodes[p].getAttribute(b)==c)if(d)h.push(a.childNodes[p]);
else{h=a.childNodes[p];break}else 0<a.childNodes[p].childNodes.length&&g(a.childNodes[p],b,c)}d=d||!1;var h;d&&(h=[]);g(a,b,c);return h};this.filterXMLElementsById=function(a,b,c){var d=[];a=a.getElementsByTagName(b);for(b=0;b<a.length;b++)d.push(a[b]);for(a=0;a<d.length;a++)for(b=0;b<c.length;b++)d[a].getAttribute("id")==c[b]&&STRUQ.ArrayHelper.remove(d,d[a]);return d};this.setAttributesToElement=function(a,b,c){b=STRUQ.XMLHelper.attributesToObject(b);var d;a:for(d in b){var g=!1;if(c)for(var h=
0;h<c.length;h++)if(c[h]==d){g=!0;break}if(""===b[d]||g)continue a;if(-1<STRUQ.ArrayHelper.indexOf(STRUQ.vo.styleFilters,d)){a.getAttribute("style")||(a.style.position="absolute");var g=a.getAttribute("style"),f;if(-1<STRUQ.ArrayHelper.indexOf(STRUQ.vo.sizeFilters,d))f=d+":"+b[d]+"px";else if("alpha"===d)a.setAttribute("alpha",b[d]),void 0!==a.style.opacity?f="opacity:"+b[d]:void 0!==a.style.filter&&(f="filter:alpha(opacity="+100*b[d]+")");else if("rotation"===d)void 0!==a.style.msTransform?f="-ms-transform: rotate("+
b[d]+"deg)":void 0!==a.style.mozTransform?f="-moz-transform: rotate("+b[d]+"deg)":void 0!==a.style.webkitTransform?f="-webkit-transform: rotate("+b[d]+"deg)":void 0!==a.style.OTransform?f="-o-transform: rotate("+b[d]+"deg)":void 0!==a.style.transform&&(f="transform: rotate("+b[d]+"deg)");else if("txtStyle"===d||"underline"===d)f="none"!==a.style.textDecoration&&""!==a.style.textDecoration?"text-decoration:"+a.style.textDecoration:"text-decoration:","strikethrough"===b[d]&&(f+=" line-through"),"true"===
b[d]&&(f+=" underline");else if("lineHeight"===d)f="line-height: "+b[d]+"px";else if("font"===d)f='font-family: "'+b[d]+'", '+STRUQ.vo.fontWhiteList;else if("fontSize"===d)f="font-size:"+b[d]+"px";else if("fontColor"===d)f="color:"+STRUQ.Utils.hexToRGB(b[d]);else if("bold"===d&&"true"===b[d])f="font-weight:bold";else if("italic"===d&&"true"===b[d])f="font-style:italic";else if("bgColor"===d)f="1",a.style["background-color"]&&(f=a.style["background-color"].split(","),f=f[f.length-1].split(")")[0],
STRUQ.Utils.isNumber(f)||(f="1")),h=STRUQ.Utils.hexToRGB(b[d],"object"),f="background-color: rgba("+h.r+","+h.g+","+h.b+","+f+")";else if("bgAlpha"===d)a.style["background-color"]&&-1<a.style["background-color"].indexOf("rgba")?(f=a.style["background-color"].split(","),f[f.length-1]=" "+b[d]+")",f=f.join(","),f="background-color:"+f):a.style["background-color"]&&-1<a.style["background-color"].indexOf("rgb")?(f=a.style["background-color"].split("rgb")[1],f="rgba"+f.split(")")[0]+", "+b[d]+")",f="background-color:"+
f):f="background-color: rgba(255, 255, 255, "+b[d]+")";else if("borderColor"===d){f="1";a.style["border-color"]&&(f=a.style["border-color"].split(","),f=f[f.length-1].split(")")[0],STRUQ.Utils.isNumber(f)||(f="1"));var m=a.style["border-width"];if(!m||m&&-1===m.indexOf("px"))m="1px";h=STRUQ.Utils.hexToRGB(b[d],"object");f="border-style:solid; border-width:"+m+"; border-color: rgba("+h.r+","+h.g+","+h.b+","+f+")";f+="; box-sizing:border-box; -moz-box-sizing:border-box; webkit-box-sizing:border-box"}else"borderAlpha"===
d?a.style["border-color"]&&-1<a.style["border-color"].indexOf("rgba")?(f=a.style["border-color"].split(","),f[f.length-1]=" "+b[d]+")",f=f.join(","),f="border-color:"+f):a.style["border-color"]&&-1<a.style["border-color"].indexOf("rgb")?(f=a.style["border-color"].split("rgb")[1],f="rgba"+f.split(")")[0]+", "+b[d]+")",f="border-color:"+f):f="border-color: rgba(255, 255, 255, "+b[d]+")":"borderSize"===d?f="border-style:solid; border-width:"+b[d]+"px":"cornerRadius"===d?f="border-radius:"+b[d]+"px":
"vAlign"!==d&&(f=d+":"+b[d]);"[object String]"===Object.prototype.toString.apply(g)?(g+=";"+f,a.setAttribute("style",g)):"[object Object]"===Object.prototype.toString.apply(g)&&(g=f.split(":")[0],h=f.split(":")[1],a.style[g]=h)}else try{"class"===d&&(b[d]+=" "+a.getAttribute("class")),a.setAttribute(d,b[d])}catch(e){}}};this.xmlToObjectAttributes=function(a,b){for(i=0;i<b.attributes.length;i++)a[b.attributes[i].nodeName]=b.attributes[i].value};this.wrapTextToElement=function(a,b,c){a.style.position=
"absolute";a.style.overflow="hidden";a.style.visibility="hidden";b&&(a.style.width=b);c&&(a.style.height=c);var d=document.createElement("div");d.style.position="absolute";d.style.display="table-cell";d.style.visibility="hidden";d.style.fontFamily=a.style.fontFamily;d.style.fontSize=a.style.fontSize;d.style.width=a.style.width;STRUQ.MasterRenderer.container.appendChild(d);a.style.lineHeight.split("px");b=parseFloat(a.style.lineHeight);STRUQ.HTMLHelper.setText(d,"MTA");var g=d.offsetHeight+1;!isNaN(b)&&
b>g&&(g=b+1);b=Math.floor(Number(a.style.height.split("px")[0])/g)*g;a.style.height=b<g?g+"px":b+"px";STRUQ.HTMLHelper.setText(d,STRUQ.HTMLHelper.getText(a));b=Number(a.style.width.split("px")[0]);var h=Number(a.style.height.split("px")[0]);0===b&&(b=d.offsetWidth);0===h&&(h=d.offsetHeight);b=STRUQ.HTMLHelper.getText(a);b=b.length+3;for(c=0;c<b;)if(d.offsetHeight>h){c++;var f=STRUQ.HTMLHelper.getText(d);STRUQ.HTMLHelper.setText(d,f.substr(0,f.length-1))}else break;setTimeout(function(){var b=g;if(d.offsetHeight>
h)STRUQ.HTMLHelper.setText(a,STRUQ.HTMLHelper.getText(d)),STRUQ.MasterRenderer.container.removeChild(d),STRUQ.Utils.wrapTextToElement(a);else{var c=STRUQ.HTMLHelper.getText(d);" "==c.charAt(c.length-1)&&(c=c.substr(0,c.length-1));STRUQ.HTMLHelper.getText(a)!=c&&STRUQ.HTMLHelper.setText(a,c.substr(0,c.length-3)+"...");a.style.height.split("px")[0]>d.offsetHeight?(a.style.height=d.offsetHeight+"px",STRUQ.HTMLHelper.alignText(a,a.parentNode.style.height.split("px")[0])):a.style.height=void 0>b?"undefinedpx":
b+"px";a.style.visibility="visible";STRUQ.MasterRenderer.container.removeChild(d)}},200)};this.hexToRGB=function(a,b){var c,d,g;c=parseInt(STRUQ.Utils.correctColor(a).substring(0,2),16);d=parseInt(STRUQ.Utils.correctColor(a).substring(2,4),16);g=parseInt(STRUQ.Utils.correctColor(a).substring(4,6),16);return"object"==b?{r:c,g:d,b:g}:"rgba("+c+", "+d+","+g+", 1)"};this.correctColor=function(a){a="#"==a.charAt(0)?a.substring(1,7):a;return a=a.substring(0,6)};this.isNumber=function(a){return!isNaN(parseFloat(a))};
this.isNumber2=function(a){return-1==String(a+1).indexOf(a)?!0:!1};this.canNavigate=function(){for(var a=!0,b=0;b<STRUQ.MasterRenderer.dynamic.creatives.length;b++)a=!STRUQ.MasterRenderer.dynamic.creatives[b].animationInProgress;STRUQ.vo.zooming&&(a=STRUQ.vo.zooming=!1);return a};this.has3D=function(){var a=document.createElement("p"),b;transforms={webkitTransform:"-webkit-transform",OTransform:"-o-transform",msTransform:"-ms-transform",MozTransform:"-moz-transform",transform:"transform"};document.body.insertBefore(a,
null);for(var c in transforms)void 0!==a.style[c]&&(a.style[c]="translate3d(1px,1px,1px)",b=window.getComputedStyle(a).getPropertyValue(transforms[c]));document.body.removeChild(a);return void 0!==b&&0<b.length&&"none"!==b};this.request=function(a,b,c,d,g){c||(c="GET");if(void 0===d||null===d)d=!0;if(void 0===g||null===g)g=!0;if("Microsoft Internet Explorer"===navigator.appName&&-1===a.indexOf("http")||-1!==a.indexOf("localhost"))g=!1;if(b)for(var h in b)a=-1==a.indexOf("?")?a+("?"+h+"="+b[h]):a+
("&"+h+"="+b[h]);reqObj=new XMLHttpRequest;g&&"withCredentials"in reqObj?reqObj.open(c,a,!0):g&&"undefined"!=typeof XDomainRequest?(reqObj=new XDomainRequest,reqObj.open(c,a)):reqObj.open(c,a,d);return reqObj};this.createCORSRequest=function(a,b){var c=new XMLHttpRequest;"withCredentials"in c?c.open(a,b,!0):"undefined"!=typeof XDomainRequest?(c=new XDomainRequest,c.open(a,b)):(c=null,console.log("CORS not supported"));return c};this.dropSnippet=function(a,b){if(a){if(b)for(var c in b)a=-1==a.indexOf("?")?
a+("?"+c+"="+b[c]):a+("&"+c+"="+b[c]);document.createElement("img").src=a}};this.getStageSize=function(){return{width:window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,height:window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight}};this.getProtocol=function(){return"http:"!==window.location.protocol&&"https:"!==window.location.protocol?window.parent.location.protocol+"//":window.location.protocol+"//"};this.getDomain=function(){return STRUQ.Utils.getProtocol()+
window.location.host+"/"}}})();(function(){STRUQ.ArrayHelper=new function(){this.remove=function(a,b){var c=this.indexOf(a,b);-1<c&&a.splice(c,1)};this.indexOf=function(a,b){for(var c=0;c<a.length;c++)if(a[c]==b)return c;return-1};this.randomize=function(a){for(var b=a.length,c,d;0!==b;)d=Math.floor(Math.random()*b),--b,c=a[b],a[b]=a[d],a[d]=c;return a}}})();
(function(){STRUQ.HTMLHelper=new function(){this.setRotation=function(a,b){a.style.msTransform="rotate("+b+"deg)";a.style.mozTransform="rotate("+b+"deg)";a.style.webkitTransform="rotate("+b+"deg)";a.style.OTransform="rotate("+b+"deg)";a.style.transform="rotate("+b+"deg)"};this.setText=function(a,b){if(void 0!=a.textContent)a.textContent=b;else return a.innerText=b};this.getText=function(a){return void 0!=a.textContent?a.textContent:a.innerText};this.setAlpha=function(a,b){void 0!=a.style.opacity?
a.style.opacity=b:void 0!=a.style.filter&&(a.style.filter="alpha(opacity="+100*b+")")};this.getAlpha=function(a){if(void 0!=a.style.opacity)return a.style.opacity;if(void 0!=a.style.filter&&(a=a.style.filter.split("alpha(opacity=")[1],void 0!=a&&(a=parseInt(a.split(")")[0])/100),"[object Number]"===Object.prototype.toString.apply(a)))return a};this.getChildByAttr=function(a,b,c){for(var d=0;d<a.childNodes.length;d++)if(a.childNodes[d].getAttribute(b)==c)return a.childNodes[d]};this.getChildById=function(a,
b){for(var c=0;c<a.childNodes.length;c++)if(a.childNodes[c].getAttribute("id")==b)return a.childNodes[c]};this.checkRatio=function(a,b,c){a&&b&&c&&(maxW=b,maxH=c,b=a.width/a.height,maxW/maxH>b?(a.height=maxH,a.width=a.height*b):(a.width=maxW,a.height=maxW/b))};this.alignElement=function(a,b,c,d,g,h){if(a&&b&&c){d=d||a.parentNode;g=g||0;h=h||0;var f=a.getAttribute("align")||d.getAttribute("align")||"center";d=a.getAttribute("vAlign")||d.getAttribute("vAlign")||"top";wid=a.width||a.clientWidth;hig=
a.height||a.clientHeight;switch(f){case "left":a.style.left=g+"px";break;case "middle":case "center":a.style.left=g+(b-wid)/2+"px";break;case "right":a.style.left=g+b-wid+"px"}switch(d){case "top":a.style.top=h+"px";break;case "middle":a.style.top=h+(c-hig)/2+"px";break;case "bottom":a.style.top=h+c-hig+"px"}}};this.alignText=function(a,b,c){if(a&&b)switch(c=c||a.parentNode,c=a.getAttribute("vAlign")||c.getAttribute("vAlign")||"top",hig=a.offsetHeight&&0!=a.offsetHeight?a.offsetHeight:a.style.height.split("px")[0],
c){case "top":a.style.top="0px";break;case "middle":a.style.top=(b-hig)/2-1+"px";break;case "bottom":a.style.top=b-hig+"px"}};this.getMousePos=function(a,b,c){for(;null!=a.offsetParent;)b-=a.offsetLeft,c-=a.offsetTop,a=a.offsetParent;return{x:b,y:c}};this.draw=function(a,b,c,d,g){d=d||"#000000";b=b||100;c=c||100;g=g||0;var h=document.createElement("div");h.style.backgroundColor=d;h.style.width=b+"px";h.style.height=c+"px";switch(a){case "roundRect":h.style.webkitBorderRadius=g+"px";h.style.mozBorderRadius=
g+"px";h.style.borderRadius=g+"px";break;case "circle":h.style.webkitBorderRadius="50%",h.style.mozBorderRadius="50%",h.style.borderRadius="50%"}return h}}})();
(function(){STRUQ.URLNavigation=new function(){this.a=5;this.callURL=function(a,b,c,d,g,h){b||(b=STRUQ.vo.urlTarget);c||(c="");if(!h)for(d||(d=0),g||(g=0),a=0<a.indexOf("?")?a+"&rnd="+Math.floor(1E10*Math.random())+"&xy="+d+","+g+"&tm="+STRUQ.vo.elapsedTime:a+"?rnd="+Math.floor(1E10*Math.random())+"&xy="+d+","+g+"&tm="+STRUQ.vo.elapsedTime,d=STRUQ.vo.xmlDoc.getElementsByTagName("listener"),g=0;g<d.length;g++)STRUQ.Utils.dropSnippet(unescape(STRUQ.XMLHelper.getNodeValue(d[g])));window.open(a,b,c)}}})();
(function(){STRUQ.XMLHelper=new function(){this.attributesToObject=function(a){if(a.attributes){for(var b={},c=0;c<a.attributes.length;c++)b[a.attributes[c].nodeName]=a.attributes[c].nodeValue;return b}return a};this.hasAttribute=function(a,b){for(var c=0;c<a.attributes.length;c++)if(a.attributes[c].nodeName==b)return!0;return!1};this.getNodeValue=function(a){return a.text?a.text:a.textContent};this.loadXML=function(a,b,c){a=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");
a.onreadystatechange=b;a.open("GET",c,!1);a.send()}}})();STRUQ=STRUQ||{};STRUQ.MessageCenter={};STRUQ.MessageCenter.subscribe=function(){};STRUQ.MessageCenter.unsubscribe=function(){};STRUQ.MessageCenter.publish=function(){};STRUQ.MessageCenter.STOP_ANIMATION={};STRUQ.MessageCenter.ACTIVE={};STRUQ.MessageCenter.INACTIVE={};STRUQ.MessageCenter.TRANSITION_STARTED={};STRUQ.MessageCenter.TRANSITION_ENDED={};STRUQ.MessageCenter.NEXT={};STRUQ.MessageCenter.PREV={};STRUQ.MessageCenter.NAV_TO={};
STRUQ.MessageCenter.ZOOMING={};STRUQ.MessageCenter.DEBUG_LOG={};STRUQ.MessageCenter.GO_INACTIVE={};
(function(){STRUQ.MessageCenter=new function(){this.GO="msgGo";this.PAGE_CHANGED="msgPageChanged";this.STOP_ANIMATION="msgStopAnimation";this.ACTIVE="msgPauseAnimation";this.INACTIVE="msgResumeAnimation";this.TRANSITION_STARTED="msgTransitionStarted";this.TRANSITION_ENDED="msgTransitionEnded";this.NEXT="msgNext";this.PREV="msgPrev";this.NAV_TO="msgNavTo";this.NAV="msgNav";this.ZOOMING="msgZooming";this.DEBUG_LOG="msgDebug";this.GO_INACTIVE="msgGoInactive";var a=[];this.subscribe=function(b,c){a.push({message:b,
callback:c})};this.unsubscribe=function(b,c){for(var d=0;d<a.length;d++)if(a[d].message==b&&a[d].callback==c){a.splice(d,1);break}};this.publish=function(b,c){for(var d=0;d<a.length;d++)a[d].message==b&&a[d].callback(c)}}})();
(function(){STRUQ.ActivityMonitor=new function(){function a(){STRUQ.MessageCenter.unsubscribe(STRUQ.MessageCenter.ACTIVE,a);c("dwell")}function b(){c("nav")}function c(a){for(var b=0;b<d.length;b++)if(d[b].getAttribute("type")==a){link=d[b].getAttribute("link");break}STRUQ.Utils.dropSnippet(link,{tm:STRUQ.vo.elapsedTime})}var d;this.initialise=function(g){d=g;for(g=0;g<d.length;g++)switch(d[g].getAttribute("type")){case "dwell":STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.ACTIVE,a);break;case "nav":STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.NAV_TO,
b);STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.NEXT,b);STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.PREV,b);break;case "loading":c("loading")}}}})();STRUQ.vo=STRUQ.vo||{};STRUQ.vo.masterFolder="dynamic";STRUQ.vo.containerVersion="r1.0.4/html";STRUQ.vo.xmlDoc=null;STRUQ.vo.styleFilters="lineHeight top left width height font fontSize fontColor position rotation txtStyle vAlign display border bgColor bgAlpha alpha borderColor borderSize borderAlpha borderStyle cornerRadius bold italic italic underline".split(" ");
STRUQ.vo.sizeFilters=["top","left","width","height"];STRUQ.vo.isOperaMini=!1;STRUQ.vo.isFallback=!1;STRUQ.vo.domain=STRUQ.vo.domain||STRUQ.Utils.getDomain();STRUQ.vo.adChoices={upWidth:19,upHeight:15,overWidth:77,overHeight:15,icon:STRUQ.vo.domain+"content/assets/images/adchoices_in.png"};
STRUQ.vo.adPad={folder:STRUQ.vo.domain+"content/assets/"+STRUQ.vo.masterFolder+"/"+STRUQ.vo.containerVersion+"/adpad",closeUp:STRUQ.vo.domain+"content/assets/images/adpad/close_up.png",closeOver:STRUQ.vo.domain+"content/assets/images/adpad/close_over.png",pauseButton:STRUQ.vo.domain+"content/assets/images/adpad/pause_button.png",brandButton:STRUQ.vo.domain+"content/assets/images/adpad/brand_button.png",adChoicesButton:STRUQ.vo.domain+"content/assets/images/adpad/adChoices_button.png",adChoicesSamll:STRUQ.vo.domain+
"content/assets/images/adpad/adChoices_small.png",struqSmall:STRUQ.vo.domain+"content/assets/images/adpad/struq_small.png",bigTick:STRUQ.vo.domain+"content/assets/images/adpad/big_tick.png",bigPause:STRUQ.vo.domain+"content/assets/images/adpad/big_tick.png"};
STRUQ.vo.transitions={horizontal:STRUQ.vo.domain+"content/assets/"+STRUQ.vo.masterFolder+"/"+STRUQ.vo.containerVersion+"/js/struq/animation/Horizontal.js",vertical:STRUQ.vo.domain+"content/assets/"+STRUQ.vo.masterFolder+"/"+STRUQ.vo.containerVersion+"/js/struq/animation/Vertical.js",fade:STRUQ.vo.domain+"content/assets/"+STRUQ.vo.masterFolder+"/"+STRUQ.vo.containerVersion+"/js/struq/animation/Fade.js",through:STRUQ.vo.domain+"content/assets/"+STRUQ.vo.masterFolder+"/"+STRUQ.vo.containerVersion+"/js/struq/animation/Through.js",
flip:STRUQ.vo.domain+"content/assets/"+STRUQ.vo.masterFolder+"/"+STRUQ.vo.containerVersion+"/js/struq/animation/Flip.js",concertina:STRUQ.vo.domain+"content/assets/"+STRUQ.vo.masterFolder+"/"+STRUQ.vo.containerVersion+"/js/struq/animation/Concertina.js",horizontal3d:STRUQ.vo.domain+"content/assets/"+STRUQ.vo.masterFolder+"/"+STRUQ.vo.containerVersion+"/js/struq/animation/Horizontal3d.js",vertical3d:STRUQ.vo.domain+"content/assets/"+STRUQ.vo.masterFolder+"/"+STRUQ.vo.containerVersion+"/js/struq/animation/Vertical3d.js"};
STRUQ.vo.defaultTransition="horizontal";STRUQ.vo.transitions3D=["horizontal3d","vertical3d","flip"];STRUQ.vo.events={};STRUQ.vo.borderDefaults={color:"#CCCCCC",size:1};STRUQ.vo.fontWhiteList="Helvetica;Arial Black;Gadget;sans-serif;Verdana;Tahoma;Geneva;Times New Roman;Trebuchet MS;Comic Sans MS;Georgia;Courier New;Courier;Palatino Linotype;Book Antiqua;Palatino;Lucida Sans Unicode;Lucida Grande;Lucida Console;Monaco".split(";");STRUQ.vo.embeddedFontsList=[];STRUQ.vo.maxTime=30;
STRUQ.vo.elapsedTime=0;STRUQ.vo.localXMLTag="local";STRUQ.vo.getLocalXML="_struq_Ad_GetXml";STRUQ.vo.state="inactive";STRUQ.vo.noComponents=2;STRUQ.vo.urlTarget="_blank";(function(){STRUQ.Model=new function(){this.isValidTransition=function(a){var b=!1,c;for(c in STRUQ.vo.transitions)if(c==a){b=!0;c=0;a:for(;c<STRUQ.vo.transitions3D.length;c++)if(STRUQ.vo.transitions3D[c]==a){STRUQ.Utils.has3D()||(b=!1);break a}break}return b}}})();
(function(){STRUQ.Highlight=function(a){this.showItem=function(b){for(var c=0;c<a.items.length;c++)if(c!=b)for(var d=0;d<a.items[c].el.childNodes.length;d++)"highlight"==a.items[c].el.childNodes[d].getAttribute("interaction")&&STRUQ.HTMLHelper.setAlpha(a.items[c].el.childNodes[d],0);else for(d=0;d<a.items[c].el.childNodes.length;d++)if("highlight"==a.items[c].el.childNodes[d].getAttribute("interaction")){var g=a.items[c].el.childNodes[d].getAttribute("alpha")?a.items[c].el.childNodes[d].getAttribute("alpha"):
1;STRUQ.HTMLHelper.setAlpha(a.items[c].el.childNodes[d],g);a.items[c].el.childNodes[d].style.visibility="visible"}}}})();
(function(){STRUQ.Inactive=function(a){function b(){c.running=!1}var c=this;c._creative=a;c.crrItems;c.lastIndex;c.running=!1;this.animate=function(a,g){if(1!=c._creative.animationInProgress&&"active"!=STRUQ.vo.state&&(c.lastIndex!=a||g)&&!c.running){c.running=!0;c.lastIndex=a;null!=a&&void 0!=a&&(c.crrItems=c._creative.pages[a].el.childNodes);for(var h=0,f=0;f<c.crrItems.length;f++)for(var m=0;m<c.crrItems[f].childNodes.length;m++){var e=c.crrItems[f].childNodes[m];if(e.getAttribute("inactive")){duration=
Number(e.getAttribute("inactiveTime"))&&Number(e.getAttribute("inactiveTime"))<Number(c._creative.xmlNode.getAttribute("interval"))/c.crrItems.length/1E3?Number(e.getAttribute("inactiveTime")):Number(c._creative.xmlNode.getAttribute("interval"))/c.crrItems.length/1E3;var h=f*duration,p={},k={};switch(e.getAttribute("inactive")){case "pulsate":p.scaleX=1.15;p.scaleY=1.15;p.delay=h;k.scaleX=1;k.scaleY=1;k.delay=h+duration/2;break;case "jump":p.top=Number(e.style.top.split("px")[0])-10;p.delay=h;k.top=
Number(e.getAttribute("initT").split("px")[0]);k.delay=h+duration/2;break;case "glow":var l=e.getAttribute("inactiveColor")||"FFFFFF";p.boxShadow="inset 0px 0px 120px 0px #"+l;p.delay=h;k.boxShadow="0px 0px 0px 0px #"+l;k.delay=h+duration/2;f==c.crrItems.length-1&&(k.onComplete=b);if(null==e.lastChild||"shadowBox"!=e.lastChild.getAttribute("id")){var r=document.createElement("div");r.id="shadowBox";r.style.width=e.style.width;r.style.height=e.style.height;r.style.position="absolute";e.appendChild(r)}else r=
e.lastChild;r.style.mozBoxShadow="0px 0px 0px 0px #"+l;r.style.webkitBoxShadow="0px 0px 0px 0px #"+l;r.style.boxShadow="0px 0px 0px 0px #"+l;e=r}TweenLite.to(e,duration/2,p);TweenLite.to(e,duration/2,k)}}TweenLite.to({},0,{delay:h+duration,onComplete:b})}};this.stopInactive=function(){if(c.running){c.running=!1;for(var a=0;a<c.crrItems.length;a++)for(var b=0;b<c.crrItems[a].childNodes.length;b++){var h=c.crrItems[a].childNodes[b];if(h.getAttribute("inactive"))if("glow"==h.getAttribute("inactive")){var f=
h.getAttribute("inactiveColor")||"FFFFFF",h=h.lastChild;TweenLite.killTweensOf(h);TweenLite.to(h,duration/2,{boxShadow:"0px 0px 0px 0px #"+f})}else TweenLite.killTweensOf(h),TweenLite.to(h,duration/2,{scaleX:1,scaleY:1,left:h.getAttribute("initL").split("px")[0],top:h.getAttribute("initT").split("px")[0]})}}};STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.TRANSITION_STARTED,this.stopInactive);STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.ACTIVE,this.stopInactive)}})();
(function(){STRUQ.Rotation=function(a){this.minDegrees=parseInt(a.minDegrees);this.maxDegrees=parseInt(a.maxDegrees);this.step=a.step;this.random=a.random;this.useDropShadow=a.useDropShadow;var b=this.minDegrees,c=Math.abs(this.minDegrees-this.maxDegrees),d=c/this.step+1;this.applyRotation=function(a){var b=a.getAttribute("style"),c=0;"true"===this.random&&(c=this.rndRotation());"false"===this.random&&(c=this.nxtRotation());if("true"===this.useDropShadow){var d="";void 0!==a.style.mozTransform&&(d+=
"-moz-box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.50);");void 0!==a.style.webkitTransform&&(d+="-webkit-box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.50);");void 0!==a.style.OTransform&&(d+="box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.50);");void 0!==a.style.transform&&(d+="box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.50);");void 0!==a.style.msTransform&&(d+="box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.50);");b+=d}d="";void 0!==a.style.mozTransform&&(d+="-moz-transform: rotate("+c+"deg);-moz-backface-visibility: hidden;");
void 0!==a.style.webkitTransform&&(d+="-webkit-transform: rotate("+c+"deg);-webkit-backface-visibility: hidden;");void 0!==a.style.OTransform&&(d+="-o-transform: rotate("+c+"deg);");void 0!==a.style.transform&&(d+="transform: rotate("+c+"deg);backface-visibility: hidden;");void 0!==a.style.msTransform&&(d+="-ms-transform: rotate("+c+"deg);");b+=d;a.setAttribute("style",b)};this.rndRotation=function(){for(var a=0;0==a;)a=Math.floor(Math.random()*d)*this.step+this.minDegrees;return a};this.nxtRotation=
function(){var a=b;b+=c;c=-c;return a}}})();
(function(){STRUQ.FontLoader=new function(){function a(a){if(1<a.target.readyState&&4===a.target.readyState&&200===a.target.status){var f=document.createElement("style");f.type="text/css";f.styleSheet?f.styleSheet.cssText=a.target.responseText:f.appendChild(document.createTextNode(a.target.responseText));document.head.appendChild(f);c++;a=f.innerHTML||f.styleSheet.cssText;g.push({fontFamily:a.split("font-family:")[1].split(";")[0].split("'").join("")},{fontWeight:a.split("font-weight:")[1].split(";")[0]},{fontStyle:a.split("font-style:")[1].split(";")[0]});
c==b.length&&d()}else 1<a.target.readyState&&404===a.target.status&&(c++,c==b.length&&d())}var b,c,d,g;this.loadFonts=function(h,f,m){c=0;d=f;g=m||STRUQ.vo.embeddedFontsList;b=h;for(h=0;h<b.length;h++)f=b[h],m=new XMLHttpRequest,m.onreadystatechange=a,m.open("GET",f),m.send()}}})();
(function(){STRUQ.Preloader=function(a){function b(){var a=s0.style.backgroundColor,c=STRUQ.ArrayHelper.indexOf(g,s0.style.backgroundColor);c+1<g.length?c++:c=0;c=g[c];TweenLite.to(s0,.1,{backgroundColor:"#CCCCCC"});TweenLite.to(s1,.1,{backgroundColor:a});TweenLite.to(s1,.1,{delay:.1,backgroundColor:"#CCCCCC"});TweenLite.to(s2,.1,{delay:.1,backgroundColor:a});TweenLite.to(s2,.1,{delay:.2,backgroundColor:"#CCCCCC"});TweenLite.to(s3,.1,{delay:.2,backgroundColor:a});TweenLite.to(s3,.1,{delay:.3,backgroundColor:"#CCCCCC"});
TweenLite.to(s0,.1,{delay:.3,backgroundColor:c,onComplete:b})}var c=a,d=document.createElement("div"),g="rgb(218, 33, 39);rgb(255, 188, 32);rgb(143, 199, 62);rgb(33, 151, 212);rgb(199, 29, 92);rgb(91, 58, 153)".split(";");d.id="preloader";d.style.position="absolute";d.style.width="42px";d.style.height="42px";d.style.left=.5*(Number(c.style.width.split("px")[0])-42)+"px";d.style.top=.5*(Number(c.style.height.split("px")[0])-42)+"px";c.appendChild(d);for(a=0;4>a;a++)this["s"+a]=document.createElement("div"),
this["s"+a].style.position="absolute",this["s"+a].style["float"]="left",this["s"+a].style.width="15px",this["s"+a].style.height="15px",0==a?(s0=this["s"+a],this["s"+a].style.backgroundColor=g[0]):this["s"+a].style.backgroundColor="#CCCCCC",1==a?(s1=this["s"+a],this["s"+a].style.left="20px"):2==a?(s2=this["s"+a],this["s"+a].style.top="20px",this["s"+a].style.left="20px"):3==a&&(s3=this["s"+a],this["s"+a].style.top="20px"),d.appendChild(this["s"+a]);d.style.display="none";this.show=function(){d.style.display=
"block";b()};this.hide=function(){d.style.display="none";TweenLite.killTweensOf(s0);TweenLite.killTweensOf(s1);TweenLite.killTweensOf(s2);TweenLite.killTweensOf(s3)};this.remove=function(){c.removeChild(d);d.removeChild(s0);s0=null;d.removeChild(s1);s1=null;d.removeChild(s2);s2=null;d.removeChild(s3);c=d=s3=null}}})();
(function(){STRUQ.TransitionLoader=new function(){function a(a,d){g++;g==b.length&&c()}var b,c,d=!1,g;this.loadTransitions=function(h,f){b=h;c=f;for(var m=g=0;m<b.length;m++){var e=b[m],p=!1,k;a:for(k in STRUQ.vo.transitions)if(k==e){p=!0;break a}if(!p){if(d)break;else d=!0;e=STRUQ.vo.defaultTransition}STRUQ.Utils.loadJSFile(STRUQ.vo.transitions[e]+"?"+STRUQ.vo.revision,a)}}}})();
(function(){STRUQ.Background=function(a){this.xmlNode=a;this.el;this.el=STRUQ.ObjectFactory.getObject("item",a,STRUQ.MasterRenderer.container).el;this.el.id="background";this.el.setAttribute("type","creative")}})();
(function(){STRUQ.Config=function(a,b){function c(a){a=a.currentTarget?a.currentTarget:a.srcElement;a==g?(g.style.display="none",h.style.display="block"):a==h&&(g.style.display="block",h.style.display="none")}function d(b){new STRUQ["AdPad"+STRUQ.vo.adWidth+"x"+STRUQ.vo.adHeight](a.getElementsByTagName("oo")[0])}var g=document.createElement("img"),h=document.createElement("img"),f=a.getElementsByTagName("adchoice")[0];a.getElementsByTagName("oo")[0]?(f=STRUQ.Utils.getProtocol()+STRUQ.vo.adPad.folder+
"/StruqAdPad"+STRUQ.vo.adWidth+"x"+STRUQ.vo.adHeight+".js?"+STRUQ.vo.revision,STRUQ.Utils.loadJSFile(f,d)):f&&(g.id="adChoiceUp",g.style.visibility="hidden",g.onload=function(){g.style.visibility="visible"},g.src=f.getAttribute("inurl"),g.style.cursor="pointer",g.style.position="absolute",g.style.zIndex="999999",g.style.display="block",g.style.top="0px",g.style.left=STRUQ.vo.adWidth-STRUQ.vo.adChoices.upWidth+"px",g.style.border=0,STRUQ.MasterRenderer.container.appendChild(g),h.id="adChoiceOver",
h.src=f.getAttribute("outurl"),h.style.cursor="pointer",h.style.position="absolute",h.style.zIndex="999999",h.style.display="none",h.style.top="0px",h.style.left=STRUQ.vo.adWidth-STRUQ.vo.adChoices.overWidth+"px",h.style.border=0,STRUQ.MasterRenderer.container.appendChild(h));STRUQ.Utils.addEventListener(g,"mouseover",c);STRUQ.Utils.addEventListener(h,"mouseout",c);STRUQ.Utils.addEventListener(h,"click",function(b){window.open(a.getElementsByTagName("adchoice")[0].getAttribute("openurl"),STRUQ.vo.urlTarget)},
!1)}})();
(function(){STRUQ.Countdown=function(a,b){function c(a){if(STRUQ.vo.elapsedTime>=STRUQ.vo.maxTime)clearInterval(A);else{var b=(new Date).getTime();difference=Math.round(w-b);0>difference&&(difference=0);dayTime=0<e.day?Math.floor(difference/864E5):0;hourTime=0<e.hour?Math.floor(difference/36E5-24*dayTime):0;minuteTime=0<e.minute?difference-(864E5*dayTime+36E5*hourTime):0;minuteTime=Math.floor(minuteTime/6E4);secondTime=0<e.second?difference-(864E5*dayTime+36E5*hourTime+6E4*minuteTime):0;secondTime=
Math.floor(secondTime/1E3);if(0==e.day||p&&0==dayTime)STRUQ.HTMLHelper.getChildById(n,"day")&&(STRUQ.HTMLHelper.getChildById(n,"day").style.visibility="hidden"),STRUQ.HTMLHelper.getChildById(n,"dayTag")&&(STRUQ.HTMLHelper.getChildById(n,"dayTag").style.visibility="hidden");if(0==e.hour||k&&0==hourTime&&0==dayTime)STRUQ.HTMLHelper.getChildById(n,"hour")&&(STRUQ.HTMLHelper.getChildById(n,"hour").style.visibility="hidden"),STRUQ.HTMLHelper.getChildById(n,"hourTag")&&(STRUQ.HTMLHelper.getChildById(n,
"hourTag").style.visibility="hidden");if(0==e.minute||l&&0==minuteTime&&0==hourTime&&0==dayTime)STRUQ.HTMLHelper.getChildById(n,"minute")&&(STRUQ.HTMLHelper.getChildById(n,"minute").style.visibility="hidden"),STRUQ.HTMLHelper.getChildById(n,"minuteTag")&&(STRUQ.HTMLHelper.getChildById(n,"minuteTag").style.visibility="hidden");if(0==e.second||r&&0==secondTime&&0==minuteTime&&0==hourTime&&0==dayTime)STRUQ.HTMLHelper.getChildById(n,"second")&&(STRUQ.HTMLHelper.getChildById(n,"second").style.visibility=
"hidden"),STRUQ.HTMLHelper.getChildById(n,"secondTag")&&(STRUQ.HTMLHelper.getChildById(n,"secondTag").style.visibility="hidden");(!STRUQ.HTMLHelper.getChildById(n,"day")||STRUQ.HTMLHelper.getChildById(n,"day")&&"hidden"==STRUQ.HTMLHelper.getChildById(n,"day").style.visibility)&&(!STRUQ.HTMLHelper.getChildById(n,"hour")||STRUQ.HTMLHelper.getChildById(n,"hour")&&"hidden"==STRUQ.HTMLHelper.getChildById(n,"hour").style.visibility)&&(!STRUQ.HTMLHelper.getChildById(n,"minute")||STRUQ.HTMLHelper.getChildById(n,
"minute")&&"hidden"==STRUQ.HTMLHelper.getChildById(n,"minute").style.visibility)&&(!STRUQ.HTMLHelper.getChildById(n,"second")||STRUQ.HTMLHelper.getChildById(n,"second")&&"hidden"==STRUQ.HTMLHelper.getChildById(n,"second").style.visibility)&&(n.style.visibility="hidden");dayTime=2==e.day&&2>String(dayTime).length?"0"+dayTime:String(dayTime);hourTime=2==e.hour&&2>String(hourTime).length?"0"+hourTime:String(hourTime);minuteTime=2==e.minute&&2>String(minuteTime).length?"0"+minuteTime:String(minuteTime);
secondTime=2==e.second&&2>String(secondTime).length?"0"+secondTime:String(secondTime);d(a)}}function d(a){var b,c,d;a?a&&"flip"==String(h.getAttribute("animation"))&&(d=String(h.getAttribute("animation"))):d=String(h.getAttribute("animation"));for(a=0;a<z.length;a++)if(b=z[a],c=this[b.getAttribute("id")+"Time"],Number(STRUQ.HTMLHelper.getText(b))!=Number(c)||""==STRUQ.HTMLHelper.getText(b))switch(d){case "scroll":(function(a,b){TweenLite.to(a,x/2,{top:Number(a.getAttribute("initT").split("px")[0])+
10,alpha:0,ease:Quad.easeIn,onComplete:function(){a.style.top=Number(a.getAttribute("initT").split("px")[0])-10+"px";STRUQ.HTMLHelper.setAlpha(a,0);STRUQ.HTMLHelper.setText(a.firstChild,b);TweenLite.to(a,x/2,{delay:x/2,top:Number(a.getAttribute("initT").split("px")[0]),alpha:1,ease:Quad.easeOut})}})})(b,c);break;case "fade":(function(a,b){TweenLite.to(a,x/2,{alpha:0,ease:Quad.easeIn,onComplete:function(){STRUQ.HTMLHelper.setAlpha(a,0);STRUQ.HTMLHelper.setText(a.firstChild,b);TweenLite.to(a,x/2,{delay:x/
2,alpha:1,ease:Quad.easeOut})}})})(b,c);break;default:Number(STRUQ.HTMLHelper.getText(b))==Number(c)&&""!=STRUQ.HTMLHelper.getText(b)||STRUQ.HTMLHelper.setText(b.firstChild,c)}}function g(a){a.preventDefault();STRUQ.URLNavigation.callURL((a.currentTarget?a.currentTarget:a.srcElement).getAttribute("href"),STRUQ.vo.urlTarget,null,a.pageX,a.pageY)}var h=a,f=b.el||b,m=a.getAttribute("format")||"dd:hh:mm:ss",m=[m.match(/d/g),m.match(/h/g),m.match(/m/g),m.match(/s/g)],e={};e.day=m[0]?m[0].length:0;e.hour=
m[1]?m[1].length:0;e.minute=m[2]?m[2].length:0;e.second=m[3]?m[3].length:0;var m=a.getAttribute("hideOnExpire")||"",p=-1<m.indexOf("d")||-1<m.indexOf("D")?!0:!1,k=-1<m.indexOf("h")||-1<m.indexOf("H")?!0:!1,l=-1<m.indexOf("m")||-1<m.indexOf("M")?!0:!1,r=-1<m.indexOf("s")||-1<m.indexOf("S")?!0:!1,w=(new Date(h.getAttribute("date"))).getTime(),x=Number(h.getAttribute("animationTime"));if(!x||.5<x)x=.75;var n=document.createElement("div");n.className="elementHover";var z=h.getElementsByTagName("element");
if(z)for(m=0;m<z.length;m++)STRUQ.ObjectFactory.getObject(z[m].getAttribute("type"),z[m],n,"countdown");z=[];STRUQ.HTMLHelper.getChildById(n,"day")&&z.push(STRUQ.HTMLHelper.getChildById(n,"day"));STRUQ.HTMLHelper.getChildById(n,"hour")&&z.push(STRUQ.HTMLHelper.getChildById(n,"hour"));STRUQ.HTMLHelper.getChildById(n,"minute")&&z.push(STRUQ.HTMLHelper.getChildById(n,"minute"));STRUQ.HTMLHelper.getChildById(n,"second")&&z.push(STRUQ.HTMLHelper.getChildById(n,"second"));c(!0);var A=setInterval(c,1E3);
n.style.position="absolute";STRUQ.Utils.setAttributesToElement(n,h);n.setAttribute("initT",n.style.top);n.setAttribute("initL",n.style.left);h.getAttribute("href")&&""!=h.getAttribute("href")&&(n.style.cursor="pointer",STRUQ.Utils.addEventListener(n,"click",g,!1),STRUQ.Utils.addEventListener(n,"touchend",g,!1));f.appendChild(n);this.xmlNode=h;this.parent=f;this.el=n}})();
(function(){STRUQ.Creative=function(a){var b={navTarget:"item"},c={minDegrees:0,maxDegrees:0,step:0,random:"true",useDropShadow:"true"},d=document.createElement("div"),g={},h=[],f=[],m=0;d.className="creativeHover";this.xmlNode=a;this.el=d;this.layout=b;this.transition=g;this.pages=h;this.items=f;this.animationInProgress=!1;this.navigated=function(a,b){for(var c=f[b].el.childNodes,d=0;d<c.length;d++)"video"==c[d].getAttribute("type")&&"playAll"==c[d].getAttribute("videoBehaviour")&&STRUQ.elementToObject(c[d]).play();
m=a;l&&l.showItem(b);r&&r.animate(a)};this.navigating=function(a){a=f[a].el.childNodes;for(var b=0;b<a.length;b++)"video"==a[b].getAttribute("type")&&STRUQ.elementToObject(a[b]).pause()};this.rotation=null;STRUQ.Utils.xmlToObjectAttributes(b,a.getElementsByTagName("layout")[0]);0<a.getElementsByTagName("rotation").length&&(STRUQ.Utils.xmlToObjectAttributes(c,a.getElementsByTagName("rotation")[0]),this.rotation=new STRUQ.Rotation(c));c=a.getElementsByTagName("elements")[0].getElementsByTagName("element")[0];
b.top=c.getAttribute("top");b.left=c.getAttribute("left");c=null;(function(c){d.style.position="absolute";d.style.top=b.top+"px";d.style.left=b.left+"px";d.setAttribute("id",a.getAttribute("id"));d.setAttribute("type","creative");c.appendChild(d)})(STRUQ.MasterRenderer.container);b.autoMask&&"true"==b.autoMask&&(d.style.overflow="hidden",d.style.width=Number(b.width)*Number(b.cols)+Number(b.spacing)*(Number(b.cols)-1)+"px",d.style.height=Number(b.height)*Number(b.rows)+Number(b.spacing)*(Number(b.rows)-
1)+"px");for(var c=a.getElementsByTagName("item"),e=g=0;e<c.length;e++){var p,k;0==e%(b.cols*b.rows)&&(p=STRUQ.ObjectFactory.getObject("page",null,this),p.el.style.width=Number(b.cols)*(Number(b.width)+Number(b.spacing))+"px",p.el.setAttribute("index",e),h.push(p),0<e&&(p.el.style.display="none"));parseInt(b.cols);parseInt(b.width);parseInt(b.spacing);0==e%parseInt(b.cols)&&0<e&&g++;g==parseInt(b.rows)&&(g=0);parseInt(b.height);parseInt(b.spacing);k=STRUQ.ObjectFactory.getObject("item",c[e],p.el,
{spacing:parseInt(b.spacing),width:parseInt(b.width),height:parseInt(b.height),index:e,productMatrix:b.productMatrix,rotation:this.rotation});f.push(k)}if(STRUQ.Utils.getXMLNodeByAttr(c[0],"interaction","highlight")){var l=new STRUQ.Highlight(this);l.showItem(0)}for(h=0;h<c[0].childNodes.length;h++)if(void 0!=c[0].childNodes[h].tagName&&c[0].childNodes[h].getAttribute("inactive")&&""!=c[0].childNodes[h].getAttribute("inactive")){var r=new STRUQ.Inactive(this);r.animate(0);break}h=a.getElementsByTagName("transition")[0]&&
void 0!=a.getElementsByTagName("transition")[0].getAttribute("type")&&""!=a.getElementsByTagName("transition")[0].getAttribute("type")?a.getElementsByTagName("transition")[0].getAttribute("type"):STRUQ.vo.defaultTransition;h=h.charAt(0).toUpperCase()+h.substr(1,h.length-1);STRUQ[h]&&(g=new STRUQ[h](this));STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.GO_INACTIVE,function(){r&&r.animate(m,!0)})}})();
(function(){STRUQ.Div=function(a,b){this.el;this.el=document.createElement("div");this.el.style.position="absolute";b.appendChild(this.el);return this.el}})();(function(){STRUQ.Dynamic=function(a){this.creatives=[];a=STRUQ.Utils.filterXMLElementsById(a,"creative",["background","nav"]);for(var b=0;b<a.length;b++){var c=STRUQ.ObjectFactory.getObject("creative",a[b]);this.creatives.push(c)}}})();
(function(){STRUQ.Image=function(a,b){function c(){clearInterval(e)}function d(a,b,c,d){a.onload=function(){var b=Number(c.getAttribute("imgScale")),e=Number(c.getAttribute("width")),f=Number(c.getAttribute("height")),g=e,h=f;if(0==f||""==f||void 0==f)d.style.width=a.width+"px",f=a.height;if(0==e||""==e||void 0==e)d.style.height=a.height+"px",e=a.width;c.getAttribute("imgScale")&&(g=e*b,h=f*b);STRUQ.HTMLHelper.checkRatio(a,g,h);STRUQ.HTMLHelper.alignElement(a,e,f,d);d.lastChild&&"border"==d.lastChild.getAttribute("id")?
d.insertBefore(a,d.lastChild):d.appendChild(a);for(b=0;b<d.childNodes.length;b++)if("shadowBox"==d.childNodes[b].getAttribute("id")){d.appendChild(d.childNodes[b]);break}a.style.left=Number(a.style.left.split("px")[0])+Number(c.getAttribute("imgX"))+"px";a.style.top=Number(a.style.top.split("px")[0])+Number(c.getAttribute("imgY"))+"px";if(c.getAttribute("interaction")&&"rollover"==c.getAttribute("interaction")&&""!=c.getAttribute("nav")||!c.getAttribute("interaction"))d.style.visibility="visible"};
b.match(/%%.*%%/)&&(b="");a.src=b}function g(a){STRUQ.URLNavigation.callURL((a.currentTarget?a.currentTarget:a.srcElement).getAttribute("href"),STRUQ.vo.urlTarget,null,a.pageX,a.pageY)}this.xmlNode;this.parent;this.parentEl;this.el;this.strings;this.time;this.xmlNode=a;b&&(this.parent=b);this.parentEl=this.parent.el?this.parent.el:this.parent;this.strings=(this.strings=STRUQ.XMLHelper.getNodeValue(this.xmlNode))?this.strings.split("|"):[this.strings];this.el=document.createElement("div");this.el.className=
"elementHover";for(var h=0;h<this.strings.length;h++){var f=document.createElement("img");f.style.position="absolute";f.style.border=0;this.xmlNode.getAttribute("align")?f.setAttribute("align",this.xmlNode.getAttribute("align")):f.setAttribute("align","center");this.xmlNode.getAttribute("vAlign")?f.setAttribute("vAlign",this.xmlNode.getAttribute("vAlign")):f.setAttribute("vAlign","top");this.el.style.visibility="hidden";0<h&&(f.style.display="none");d(f,this.strings[h],this.xmlNode,this.el)}if(1<
this.strings.length){this.time=this.xmlNode.getAttribute("alternateTime")||1E3;var m=this;m.pos=0;var e=setInterval(function(){m.el.getElementsByTagName("img")[m.pos].style.display="none";m.pos+1<=m.strings.length-1?m.pos++:m.pos=0;m.el.getElementsByTagName("img")[m.pos].style.display="block"},this.time);STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.STOP_ANIMATION,c)}(function(a){a.el.style.position="absolute";STRUQ.Utils.setAttributesToElement(a.el,a.xmlNode,"borderColor borderSize borderAlpha borderStyle bgColor bgAlpha cornerRadius".split(" "));
a.el.setAttribute("initT",a.el.style.top);a.el.setAttribute("initL",a.el.style.left);var b=a.xmlNode.getAttribute("bgColor"),c=a.xmlNode.getAttribute("bgAlpha"),d=a.xmlNode.getAttribute("borderColor"),e=a.xmlNode.getAttribute("borderSize"),f=a.xmlNode.getAttribute("borderAlpha"),h=a.xmlNode.getAttribute("cornerRadius");if(b){var m=document.createElement("div");m.id="background";m.style.position="absolute";m.style.width=a.xmlNode.getAttribute("width")+"px";m.style.height=a.xmlNode.getAttribute("height")+
"px";m.style.backgroundColor="#"+b;m.style.borderRadius=h+"px";m.style.mozBorderRadius=h+"px";m.style.webkitBorderRadius=h+"px";m.style.pointerEvents="none";STRUQ.HTMLHelper.setAlpha(m,c);a.el.appendChild(m)}if(d||e)b=document.createElement("div"),b.id="border",b.style.position="absolute",b.style.width=a.xmlNode.getAttribute("width")+"px",b.style.height=a.xmlNode.getAttribute("height")+"px",b.style.borderStyle="solid",b.style.borderColor="#"+d,b.style.borderWidth=e+"px",b.style.borderRadius=h+"px",
b.style.mozBorderRadius=h+"px",b.style.webkitBorderRadius=h+"px",b.style.boxSizing="border-box",b.style.MozBoxSizing="border-box",b.style.webkitBoxSizing="border-box",b.style.pointerEvents="none",STRUQ.HTMLHelper.setAlpha(b,f),a.el.appendChild(b);a.xmlNode.getAttribute("masked")&&"true"==a.xmlNode.getAttribute("masked")&&(a.el.style.overflow="hidden",a.el.style.borderRadius=h+"px");a.xmlNode.getAttribute("href")&&""!=a.xmlNode.getAttribute("href")&&(a.el.style.cursor="pointer",STRUQ.Utils.addEventListener(a.el,
"click",g,!1),STRUQ.Utils.addEventListener(a.el,"touchend",g,!1));a.parentEl.appendChild(a.el)})(this)}})();
(function(){STRUQ.Item=function(a,b,c){function d(a){var b=a.currentTarget?a.currentTarget:a.srcElement;if("this"==b.getAttribute("nav")&&"mouseover"==a.type&&STRUQ.Utils.canNavigate()){var c="item"==b.getAttribute("type")?b.getAttribute("index"):b.parentNode.getAttribute("index");STRUQ.MessageCenter.publish(STRUQ.MessageCenter.NAV_TO,{itemPos:c})}if("item"==b.getAttribute("type"))for(c=0;c<b.childNodes.length;c++){var d;"parent"==b.childNodes[c].getAttribute("interactionTarget")&&(d=b.childNodes[c],
"mouseover"==a.type?(STRUQ.HTMLHelper.setAlpha(d,d.getAttribute("alpha")?d.getAttribute("alpha"):1),d.style.visibility="visible","video"==d.getAttribute("type")&&STRUQ.elementToObject(d).play()):"mouseout"==a.type&&(STRUQ.HTMLHelper.setAlpha(d,0),d.style.visibility="hidden"))}else if("self"!=b.getAttribute("interactionTarget"))if("mouseout"!=a.type&&"touchend"!=a.type||"video"!=b.getAttribute("type"))for(c=0;c<b.parentNode.childNodes.length;c++)b.parentNode.childNodes[c].getAttribute("interactionTarget")==
b.getAttribute("id")&&(d=b.parentNode.childNodes[c],"mouseover"==a.type||"touchend"==a.type?"zoom"!=d.getAttribute("type")?(STRUQ.HTMLHelper.setAlpha(d,d.getAttribute("alpha")?d.getAttribute("alpha"):1),d.style.visibility="visible","video"==d.getAttribute("type")&&STRUQ.elementToObject(d).play()):"zoom"==d.getAttribute("type")&&"true"==d.getAttribute("canShow")&&STRUQ.elementToObject(d).show():"mouseout"==a.type&&"zoom"!=d.getAttribute("type")&&(STRUQ.HTMLHelper.setAlpha(d,0),d.style.visibility="hidden"));
else STRUQ.elementToObject(b).pause();else"self"==b.getAttribute("interactionTarget")&&("mouseover"==a.type?"zoom"==b.getAttribute("type")?STRUQ.elementToObject(b).show():(a=b.getAttribute("alpha")?b.getAttribute("alpha"):1,STRUQ.HTMLHelper.setAlpha(b,a),"video"==b.getAttribute("type")&&STRUQ.elementToObject(b).play()):"mouseout"==a.type&&("zoom"==b.getAttribute("type")?STRUQ.elementToObject(b).hide():STRUQ.HTMLHelper.setAlpha(b,0)))}this.xmlNode=[];this.el;this.parent=b;this.index=c?c.index:-1;this.width=
c?c.width:STRUQ.vo.adWidth;this.height=c?c.height:STRUQ.vo.adHeight;this.spacing=c?c.spacing:0;this.rotation=c?c.rotation:null;c=a.getElementsByTagName("element");for(a=0;a<c.length;a++)this.xmlNode.push(c[a]);c=null;this.el=document.createElement("div");this.el.style.position="relative";this.el.style.cssFloat="left";this.el.style["float"]="left";this.el.style.styleFloat="left";this.el.style.marginRight=this.spacing+"px";this.el.style.marginBottom=this.spacing+"px";this.el.style.width=this.width+
"px";this.el.style.height=this.height+"px";b.appendChild(this.el);this.el.className="creativeHover";this.el.setAttribute("type","item");this.el.setAttribute("index",this.index);this.rotation&&this.rotation.applyRotation(this.el);for(a=0;a<this.xmlNode.length;a++){if("item"==this.xmlNode[a].parentNode.tagName||"elements"==this.xmlNode[a].parentNode.tagName)var g=STRUQ.ObjectFactory.getObject(this.xmlNode[a].getAttribute("type"),this.xmlNode[a],this);g&&("this"==g.el.getAttribute("nav")&&"rollover"==
g.el.getAttribute("interaction")?STRUQ.Utils.addEventListener(g.el,"mouseover",d):"rollover"==g.el.getAttribute("interaction")?(g.xmlNode.getAttribute("interactionTarget")||(g.xmlNode.setAttribute("interactionTarget","self"),g.el.setAttribute("interactionTarget","self")),STRUQ.HTMLHelper.setAlpha(g.el,0),"self"==g.el.getAttribute("interactionTarget")?(STRUQ.Utils.addEventListener(g.el,"mouseover",d),STRUQ.Utils.addEventListener(g.el,"mouseout",d)):"parent"==g.el.getAttribute("interactionTarget")?
(this.el.getAttribute("iparentFlag")||(STRUQ.Utils.addEventListener(this.el,"mouseover",d),STRUQ.Utils.addEventListener(this.el,"mouseout",d),this.el.setAttribute("iparentFlag","true")),g.el.style.visibility="hidden"):g.el.getAttribute("interactionTarget")&&(b=STRUQ.HTMLHelper.getChildByAttr(this.el,"id",g.el.getAttribute("interactionTarget")),STRUQ.vo.isTouchDevice?STRUQ.Utils.addEventListener(b,"click",d):(STRUQ.Utils.addEventListener(b,"mouseover",d),"zoom"==g.el.getAttribute("type")||"video"==
g.el.getAttribute("type")?STRUQ.Utils.addEventListener(g.el,"mouseout",d):STRUQ.Utils.addEventListener(b,"mouseout",d)),g.el.style.visibility="hidden")):"highlight"==g.el.getAttribute("interaction")&&(STRUQ.HTMLHelper.setAlpha(g.el,0),this.el.getAttribute("ihighlightFlag")||(STRUQ.Utils.addEventListener(this.el,"mouseover",d),this.el.setAttribute("ihighlightFlag","true")),this.el.setAttribute("nav","this")),void 0!=g.xmlNode.getAttribute("mask")&&""!=g.xmlNode.getAttribute("mask")&&((b=STRUQ.Utils.getXMLNodeByAttr(g.xmlNode.parentNode,
"id",g.xmlNode.getAttribute("mask")))?g.el.style.clip="rect("+b.getAttribute("top")+"px,"+b.getAttribute("width")+"px,"+b.getAttribute("height")+"px,"+b.getAttribute("left")+"px)":console.log('Error 010: there is not mask with the id "'+g.xmlNode.getAttribute("mask")+'"')),"playFirst"==g.el.getAttribute("videoBehaviour")||"playAll"==g.el.getAttribute("videoBehaviour")&&"video"==g.el.getAttribute("type"))&&("parent"!=g.el.getAttribute("interactionTarget")&&"self"!=g.el.getAttribute("interactionTarget")&&
STRUQ.Utils.addEventListener(g.el,"mouseout",d),0==this.index&&g.play())}}})();
(function(){STRUQ.Nav=function(a){function b(a){STRUQ.Utils.canNavigate()&&STRUQ.MessageCenter.publish(STRUQ.MessageCenter.NEXT,a)}function c(a){STRUQ.Utils.canNavigate()&&STRUQ.MessageCenter.publish(STRUQ.MessageCenter.PREV,a)}function d(a){"touchstart"==a.type&&1==a.changedTouches.length&&(a.preventDefault(),g=Number(a.changedTouches[0].clientX),h=Number(a.changedTouches[0].clientY));if("touchend"==a.type){1==a.changedTouches.length&&(f=Number(a.changedTouches[0].clientX),m=Number(a.changedTouches[0].clientY));
if(20<Math.abs(f-g)){a.stopPropagation();if(f>g){c();return}if(f<g){b();return}}else if(20<Math.abs(m-h)){a.stopPropagation();if(m>h){c();return}if(m<h){b();return}}"prev"===a.target.parentNode.id?c():b()}}var g=0,h=0,f=0,m=0;STRUQ.vo.isTouchDevice&&(STRUQ.Utils.addEventListener(STRUQ.MasterRenderer.container,"touchstart",d,!0),STRUQ.Utils.addEventListener(STRUQ.MasterRenderer.container,"touchend",d,!0));if(a){for(var e=a.getElementsByTagName("elements")[0].getElementsByTagName("element"),p=0;p<e.length;p++){var k=
STRUQ.ObjectFactory.getObject(e[p].getAttribute("type"),e[p],STRUQ.MasterRenderer.container);if("rollover"==k.xmlNode.getAttribute("interaction")){var l=function(a){a=a.currentTarget?a.currentTarget:a.srcElement;if(0==STRUQ.HTMLHelper.getAlpha(a)){var b=a.getAttribute("alpha")?a.getAttribute("alpha"):1;STRUQ.HTMLHelper.setAlpha(a,b)}else STRUQ.HTMLHelper.setAlpha(a,0)};STRUQ.HTMLHelper.setAlpha(k.el,0);STRUQ.Utils.addEventListener(k.el,"mouseover",l);STRUQ.Utils.addEventListener(k.el,"mouseout",l)}k.el.style.cursor=
"pointer";k.el.style.zIndex=999999;"prev"==k.xmlNode.getAttribute("nav")?STRUQ.Utils.addEventListener(k.el,"click",c,!1):STRUQ.Utils.addEventListener(k.el,"click",b,!1)}this.xmlNode=a}}})();(function(){STRUQ.Page=function(a,b){var c=document.createElement("div");c.style.position="absolute";b.el.appendChild(c);c.setAttribute("type","page");this.el=c;this.parent=b;c.className="creativeHover"}})();
(function(){STRUQ.SwipeDialog=function(a,b){function c(){k++;l.style.visibility="visible";TweenLite.to(l,.25,{alpha:1});h&&(TweenLite.to(l,.125,{delay:.25,left:Number(l.getAttribute("initL").split("px")[0])+10}),TweenLite.to(l,.25,{delay:.375,left:Number(l.getAttribute("initL").split("px")[0])-10}),TweenLite.to(l,.25,{delay:.625,left:Number(l.getAttribute("initL").split("px")[0])+10}),TweenLite.to(l,.25,{delay:.875,left:Number(l.getAttribute("initL").split("px")[0])-10}),TweenLite.to(l,.25,{delay:1.1,
left:Number(l.getAttribute("initL").split("px")[0]),ease:Quad.easeOut}));setTimeout(function(){TweenLite.to(l,.25,{delay:1.35,alpha:0,onComplete:function(){l.style.visibility="hidden"}});k&&(k<e||0==e)&&(x=setTimeout(c,1E3*p))},m)}function d(){clearTimeout(x);TweenLite.killTweensOf(l);0<STRUQ.HTMLHelper.getAlpha(l)&&TweenLite.to(l,.25,{alpha:0,onComplete:function(){l.style.visibility="hidden"}})}function g(a){a.preventDefault();STRUQ.URLNavigation.callURL((a.currentTarget?a.currentTarget:a.srcElement).getAttribute("href"),
STRUQ.vo.urlTarget,null,a.pageX,a.pageY)}var h=a.getAttribute("animation"),f=a.getAttribute("delay")?Number(a.getAttribute("delay")):2,m=a.getAttribute("time")?Number(a.getAttribute("time")):3,e=a.getAttribute("repeat")?Number(a.getAttribute("repeat")):null,p=a.getAttribute("repeatInterval")?Number(a.getAttribute("repeatInterval")):f,k=0;STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.STOP_ANIMATION,d);STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.NEXT,d);STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.PREV,
d);STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.NAV_TO,d);var l=document.createElement("div");l.style.visibility="hidden";STRUQ.HTMLHelper.setAlpha(l,0);for(var r=a.getElementsByTagName("element"),w=0;w<r.length;w++)STRUQ.ObjectFactory.getObject(r[w].getAttribute("type"),r[w],l);var x=setTimeout(c,1E3*f);l.style.position="absolute";STRUQ.Utils.setAttributesToElement(l,a);l.setAttribute("initT",l.style.top);l.setAttribute("initL",l.style.left);a.getAttribute("href")&&""!=a.getAttribute("href")&&
(l.style.cursor="pointer",STRUQ.Utils.addEventListener(l,"click",g,!1),STRUQ.Utils.addEventListener(l,"touchend",g,!1));b.appendChild(l);this.el=l;this.xmlNode=a;this.parent=b}})();
(function(){STRUQ.Text=function(a,b,c){function d(){clearInterval(r)}function g(a){a.preventDefault();STRUQ.URLNavigation.callURL((a.currentTarget?a.currentTarget:a.srcElement).getAttribute("href"),STRUQ.vo.urlTarget,null,a.pageX,a.pageY)}var h="countdown"==c?!0:!1;if(b)var f=b;var m=f.el?f.el:f,e=STRUQ.XMLHelper.getNodeValue(a);"upper"==a.getAttribute("caseType")?e=e.toUpperCase():"lower"==a.getAttribute("caseType")&&(e=e.toLowerCase());var e=e?e.split("|"):null,p=document.createElement("div");p.className=
"elementHover";var k=document.createElement("p");(function(){var b=a.getAttribute("leading");p.style.position="absolute";p.style.textDecoration="none";if(b&&!isNaN(b)){var d=document.createAttribute("lineHeight");d.value=16+parseFloat(b);a.setAttributeNode(d)}STRUQ.Utils.setAttributesToElement(p,a,"borderColor borderAlpha cornerRadius borderSize bgColor bgAlpha textDecoration font fontSize fontColor fontStyle italic bold underline align vAlign".split(" "));p.setAttribute("initT",p.style.top);p.setAttribute("initL",
p.style.left);var c=a.getAttribute("bgColor"),l=a.getAttribute("bgAlpha"),b=a.getAttribute("borderColor"),d=a.getAttribute("borderSize"),f=a.getAttribute("borderAlpha"),r=a.getAttribute("cornerRadius");if(!a.getAttribute("font")){var t=document.createAttribute("font");t.value="Arial";a.setAttributeNode(t)}c&&(t=document.createElement("div"),t.id="background",t.style.position="absolute",t.style.width=a.getAttribute("width")+"px",t.style.height=a.getAttribute("height")+"px",t.style.backgroundColor=
"#"+c,t.style.borderRadius=r+"px",t.style.mozBorderRadius=r+"px",t.style.webkitBorderRadius=r+"px",t.style.pointerEvents="none",STRUQ.HTMLHelper.setAlpha(t,l),p.appendChild(t));if(b||d)c=document.createElement("div"),c.id="border",c.style.position="absolute",c.style.width=a.getAttribute("width")+"px",c.style.height=a.getAttribute("height")+"px",c.style.borderStyle="solid",c.style.borderColor="#"+b,c.style.borderWidth=d+"px",c.style.borderRadius=r+"px",c.style.mozBorderRadius=r+"px",c.style.webkitBorderRadius=
r+"px",c.style.boxSizing="border-box",c.style.MozBoxSizing="border-box",c.style.webkitBoxSizing="border-box",c.style.pointerEvents="none",STRUQ.HTMLHelper.setAlpha(c,f),p.appendChild(c);STRUQ.Utils.setAttributesToElement(k,a,"borderColor borderAlpha cornerRadius borderSize bgColor bgAlpha alpha top left rotation".split(" "));k.style.position="relative";k.style.display="table-cell";k.style.wordWrap="break-word";k.style.margin="0px";k.style.padding="0px";k.getAttribute("align")||k.setAttribute("align",
"center");a.getAttribute("vAlign")?k.setAttribute("vAlign",a.getAttribute("vAlign")):k.setAttribute("vAlign","top");p.appendChild(k);e&&(k.innerHTML=e[0]);h||STRUQ.Utils.wrapTextToElement(k);a.getAttribute("href")&&""!=a.getAttribute("href")&&(p.style.cursor="pointer",STRUQ.Utils.addEventListener(p,"click",g,!1),STRUQ.Utils.addEventListener(p,"touchend",g,!1));m.appendChild(p)})();if(e&&1<e.length){b=a.getAttribute("alternateTime")||1E3;var l=this;l.pos=0;var r=setInterval(function(){l.pos+1<=e.length-
1?l.pos++:l.pos=0;k.innerHTML=e[l.pos];STRUQ.Utils.wrapTextToElement(k)},b);STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.STOP_ANIMATION,d)}this.xmlNode=a;this.parent=f;this.parentEl=m;this.el=p;this.strings=e}})();
(function(){STRUQ.Vector=function(a,b){function c(a){a.preventDefault();STRUQ.URLNavigation.callURL((a.currentTarget?a.currentTarget:a.srcElement).getAttribute("href"),STRUQ.vo.urlTarget,null,a.pageX,a.pageY)}this.xmlNode;this.parent;this.parentEl;this.el;this.xmlNode=a;b&&(this.parent=b);this.parentEl=this.parent.el?this.parent.el:this.parent;this.el=document.createElement("div");this.el.className="elementHover";this.el.style.position="absolute";STRUQ.Utils.setAttributesToElement(this.el,this.xmlNode);
this.el.setAttribute("initT",this.el.style.top);this.el.setAttribute("initL",this.el.style.left);this.xmlNode.getAttribute("href")&&""!=this.xmlNode.getAttribute("href")&&(this.el.style.cursor="pointer",STRUQ.Utils.addEventListener(this.el,"click",c,!1),STRUQ.Utils.addEventListener(this.el,"touchend",c,!1));this.parentEl.appendChild(this.el)}})();
(function(){STRUQ.Video=function(a,b){function c(a){a&&a.stopPropagation&&a.stopPropagation();u.pause();STRUQ.HTMLHelper.setAlpha(e,0);e.style.visibility="hidden";STRUQ.WDInterface&&STRUQ.WDInterface.setAdStatus("videoPlaying",!1)}function d(){STRUQ.Utils.removeEventListener(u,"canplay",d);var a=Number(f.getAttribute("width")),b=Number(f.getAttribute("height"));STRUQ.HTMLHelper.alignElement(u,a,b,e);u.currentTime=0;t.hide();STRUQ.WDInterface&&STRUQ.WDInterface.setAdStatus("videoPlaying",!0)}function g(){x++;
n.style.visibility="visible";TweenLite.to(n,.25,{alpha:1});p&&(TweenLite.to(n,.125,{delay:.25,left:10}),TweenLite.to(n,.25,{delay:.375,left:-10}),TweenLite.to(n,.25,{delay:.625,left:10}),TweenLite.to(n,.25,{delay:.875,left:-10}),TweenLite.to(n,.25,{delay:1.1,left:0,ease:Quad.easeOut}));setTimeout(function(){TweenLite.to(n,.25,{delay:1.35,alpha:0,onComplete:function(){n.style.visibility="hidden"}});x&&(x<r||0==r)&&setTimeout(g,1E3*w)},l)}function h(a){a.preventDefault();STRUQ.URLNavigation.callURL((a.currentTarget?
a.currentTarget:a.srcElement).getAttribute("href"),STRUQ.vo.urlTarget,null,a.pageX,a.pageY)}STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.NEXT,c);STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.PREV,c);STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.NAV_TO,c);var f=a,m=b.el||b,e=document.createElement("div");e.className="elementHover";var p=f.getAttribute("animation"),k=f.getAttribute("delay")?Number(f.getAttribute("delay")):2,l=f.getAttribute("time")?Number(f.getAttribute("time")):3,r=f.getAttribute("repeat")?
Number(f.getAttribute("repeat")):null,w=f.getAttribute("repeatInterval")?Number(f.getAttribute("repeatInterval")):k,x=0;(function(){e.style.position="absolute";e.style.overflow="hidden";STRUQ.Utils.setAttributesToElement(e,f,"borderColor borderSize borderAlpha borderStyle bgColor bgAlpha cornerRadius".split(" "));e.setAttribute("initT",e.style.top);e.setAttribute("initL",e.style.left);var a=f.getAttribute("bgColor")||"FFFFFF",b=f.getAttribute("bgAlpha"),c=f.getAttribute("borderColor"),d=f.getAttribute("borderSize"),
l=f.getAttribute("borderAlpha"),g=f.getAttribute("cornerRadius");if(a){var k=document.createElement("div");k.id="background";k.style.position="absolute";k.style.width=f.getAttribute("width")+"px";k.style.height=f.getAttribute("height")+"px";k.style.backgroundColor="#"+a;k.style.borderRadius=g+"px";k.style.mozBorderRadius=g+"px";k.style.webkitBorderRadius=g+"px";k.style.pointerEvents="none";STRUQ.HTMLHelper.setAlpha(k,b);e.appendChild(k)}if(c||d)a=document.createElement("div"),a.id="border",a.style.position=
"absolute",a.style.width=f.getAttribute("width")+"px",a.style.height=f.getAttribute("height")+"px",a.style.borderStyle="solid",a.style.borderColor="#"+c,a.style.borderWidth=d+"px",a.style.borderRadius=g+"px",a.style.mozBorderRadius=g+"px",a.style.webkitBorderRadius=g+"px",a.style.boxSizing="border-box",a.style.MozBoxSizing="border-box",a.style.webkitBoxSizing="border-box",a.style.pointerEvents="none",STRUQ.HTMLHelper.setAlpha(a,l),e.appendChild(a);f.getAttribute("masked")&&"true"==f.getAttribute("masked")&&
(e.style.overflow="hidden",e.style.borderRadius=g+"px");f.getAttribute("href")&&""!=f.getAttribute("href")&&(e.style.cursor="pointer",STRUQ.Utils.addEventListener(e,"click",h,!1),STRUQ.Utils.addEventListener(e,"touchend",h,!1));m.appendChild(e)})();if(STRUQ.vo.isTouchDevice){var n=document.createElement("div");n.style.position="absolute";n.style.visibility="hidden";STRUQ.HTMLHelper.setAlpha(n,0);e.appendChild(n);for(var z=f.getElementsByTagName("element"),A=0;A<z.length;A++)if("close"!=z[A].getAttribute("id"))STRUQ.ObjectFactory.getObject(z[A].getAttribute("type"),
z[A],n);else var q=STRUQ.ObjectFactory.getObject(z[A].getAttribute("type"),z[A],e);setTimeout(g,1E3*k);q&&STRUQ.Utils.addEventListener(q.el,"click",c,!1)}var t=new STRUQ.Preloader(e),u=document.createElement("video");u.style.position="absolute";u.style.width="100%";u.style.height="auto";u.src=STRUQ.XMLHelper.getNodeValue(f.getElementsByTagName("link")[0]||f);u.loop="loop";u.muted="muted";f.getAttribute("vAlign")?u.setAttribute("vAlign",f.getAttribute("vAlign")):u.setAttribute("vAlign","top");0<e.childNodes.length?
"background"==e.childNodes[0].getAttribute("id")&&2<=e.childNodes.length?e.insertBefore(u,e.childNodes[1]):"background"==e.childNodes[0].getAttribute("id")&&2==e.childNodes.length?e.appendChild(u):e.insertBefore(u,e.childNodes[0]):e.appendChild(u);this.xmlNode=f;this.parent=m;this.el=e;this.play=function(a){a&&a.stopPropagation();u.play();4!=u.readyState?(t.show(),STRUQ.Utils.addEventListener(u,"canplay",d)):d();a=Number(e.getAttribute("alpha"))||1;0==STRUQ.HTMLHelper.getAlpha(e)&&STRUQ.HTMLHelper.setAlpha(e,
a);e.style.visibility="visible"};this.pause=c}})();
(function(){STRUQ.Zoom=function(a,b){function c(a){var b=a.currentTarget||a.relatedTarget||a.fromElement;a=STRUQ.HTMLHelper.getMousePos(b,a.clientX||a.pageX,a.clientY||a.pageY);var c=t.clientWidth-Number(b.style.width.split("px")[0]),d=t.clientHeight-Number(b.style.height.split("px")[0]);t.style.left=-c*(a.x/Number(b.style.width.split("px")[0]))+"px";t.style.top=-d*(a.y/Number(b.style.height.split("px")[0]))+"px"}function d(a){a.stopPropagation();a.preventDefault();if("touchstart"==a.type&&1==a.changedTouches.length)touchX=
Number(a.changedTouches[0].clientX),touchY=Number(a.changedTouches[0].clientY);else if("touchmove"==a.type&&1==a.changedTouches.length){STRUQ.MessageCenter.publish(STRUQ.MessageCenter.ZOOMING);STRUQ.vo.zooming=!0;endX=Number(a.changedTouches[0].clientX);endY=Number(a.changedTouches[0].clientY);a=endX-touchX;var b=endY-touchY,c=Number(t.style.left.split("px")[0]),d=Number(t.style.top.split("px")[0]),l=q.clientWidth-t.clientWidth,e=q.clientHeight-t.clientHeight;TweenLite.killTweensOf(t);5<Math.abs(a)&&
(0>a&&c-30>=l?TweenLite.to(t,.25,{left:c-30,ease:Quad.easeOut}):0<a&&0>=c+30&&TweenLite.to(t,.25,{left:c+30,ease:Quad.easeOut}));5<Math.abs(b)&&(0>b&&d-30>=e?TweenLite.to(t,.25,{top:d-30,ease:Quad.easeOut}):0<b&&0>=d+30&&TweenLite.to(t,.25,{top:d+30,ease:Quad.easeOut}))}else(5>Math.abs(endX-touchX)||5>Math.abs(endY-touchY)&&"touchend"==a.type)&&m(a)}function g(){x++;e.getAttribute("interactionTarget")&&"self"!=e.getAttribute("interactionTarget")&&(q.style.visibility="visible");STRUQ.HTMLHelper.setAlpha(q,
1);p&&u&&(TweenLite.to(u,.125,{delay:.25,left:10}),TweenLite.to(u,.25,{delay:.375,left:-10}),TweenLite.to(u,.25,{delay:.625,left:10}),TweenLite.to(u,.25,{delay:.875,left:-10}),TweenLite.to(u,.25,{delay:1.1,left:0,ease:Quad.easeOut}));setTimeout(function(){u&&TweenLite.to(u,.25,{delay:1.35,alpha:0,onComplete:function(){u.style.visibility="hidden"}});x&&(x<r||0==r)&&(n=setTimeout(g,1E3*w))},l)}function h(a){a&&a.hasOwnProperty("stopPropagation")&&a.stopPropagation();e.getAttribute("interactionTarget")&&
"self"!=e.getAttribute("interactionTarget")&&(q.style.visibility="hidden");STRUQ.HTMLHelper.setAlpha(q,0);t.style.left=t.getAttribute("initL");t.style.top=t.getAttribute("initT");f()}function f(){clearTimeout(n);u&&TweenLite.killTweensOf(u);u&&0<STRUQ.HTMLHelper.getAlpha(u)&&TweenLite.to(u,.25,{alpha:0,onComplete:function(){u.style.visibility="hidden"}})}function m(a){a.preventDefault();STRUQ.URLNavigation.callURL((a.currentTarget?a.currentTarget:a.srcElement).getAttribute("href"),STRUQ.vo.urlTarget,
null,a.pageX,a.pageY)}var e=a,p=e.getAttribute("animation"),k=e.getAttribute("delay")?Number(e.getAttribute("delay")):2,l=e.getAttribute("time")?Number(e.getAttribute("time")):3,r=e.getAttribute("repeat")?Number(e.getAttribute("repeat")):null,w=e.getAttribute("repeatInterval")?Number(e.getAttribute("repeatInterval")):k,x=0,n;STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.STOP_ANIMATION,f);STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.NEXT,h);STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.PREV,
h);STRUQ.MessageCenter.subscribe(STRUQ.MessageCenter.NAV_TO,h);if(b)var z=b;var A=z.el?z.el:z,q=document.createElement("div");q.className="elementHover";q.setAttribute("canShow","false");e.getAttribute("interactionTarget")&&"self"!=e.getAttribute("interactionTarget")?q.style.visibility="hidden":STRUQ.HTMLHelper.setAlpha(q,0);var t=document.createElement("img");t.style.position="absolute";t.style.border=0;e.getAttribute("align")?t.setAttribute("align",e.getAttribute("align")):t.setAttribute("align",
"center");e.getAttribute("vAlign")?t.setAttribute("vAlign",e.getAttribute("vAlign")):t.setAttribute("vAlign","middle");k=e.getElementsByTagName("link")[0]||e;(function(a,b,c,d){a.src=b;a.onload=function(){var b=Number(c.getAttribute("width")),l=Number(c.getAttribute("height"));STRUQ.HTMLHelper.alignElement(a,b,l,d);0<q.childNodes.length?"background"==q.childNodes[0].getAttribute("id")&&2<=q.childNodes.length?d.insertBefore(a,q.childNodes[1]):"background"==q.childNodes[0].getAttribute("id")&&2==q.childNodes.length?
d.appendChild(a):d.insertBefore(a,q.childNodes[0]):d.appendChild(a);d.setAttribute("canShow","true");a.setAttribute("initL",a.style.left);a.setAttribute("initT",a.style.top)}})(t,STRUQ.XMLHelper.getNodeValue(k),e,q);(function(){q.style.position="absolute";STRUQ.Utils.setAttributesToElement(q,e,"borderColor borderSize borderAlpha borderStyle bgColor bgAlpha cornerRadius".split(" "));q.setAttribute("initL",q.style.left);q.setAttribute("initT",q.style.top);var a=e.getAttribute("bgColor")||"FFFFFF",b=
e.getAttribute("bgAlpha")||1,c=e.getAttribute("borderColor")||"CCCCCC",d=e.getAttribute("borderSize")||"1",l=e.getAttribute("borderAlpha")||1,f=e.getAttribute("cornerRadius")||0,g=document.createElement("div");g.id="background";g.style.position="absolute";g.style.width=e.getAttribute("width")+"px";g.style.height=e.getAttribute("height")+"px";g.style.backgroundColor="#"+a;g.style.borderRadius=f+"px";g.style.mozBorderRadius=f+"px";g.style.webkitBorderRadius=f+"px";g.style.pointerEvents="none";STRUQ.HTMLHelper.setAlpha(g,
b);q.appendChild(g);if(c||d)a=document.createElement("div"),a.id="border",a.style.position="absolute",a.style.width=e.getAttribute("width")+"px",a.style.height=e.getAttribute("height")+"px",a.style.borderStyle="solid",a.style.borderColor="#"+c,a.style.borderWidth=d+"px",a.style.borderRadius=f+"px",a.style.mozBorderRadius=f+"px",a.style.webkitBorderRadius=f+"px",a.style.boxSizing="border-box",a.style.MozBoxSizing="border-box",a.style.webkitBoxSizing="border-box",a.style.pointerEvents="none",STRUQ.HTMLHelper.setAlpha(a,
l),q.appendChild(a);q.style.overflow="hidden";q.style.borderRadius=f+"px";e.getAttribute("href")&&""!=e.getAttribute("href")&&(q.style.cursor="pointer",STRUQ.Utils.addEventListener(q,"click",m,!1),STRUQ.Utils.addEventListener(q,"touchend",m,!1));A.appendChild(q)})();if(STRUQ.vo.isTouchDevice){var u=document.createElement("div");u.style.position="absolute";q.appendChild(u);for(var k=e.getElementsByTagName("element"),y=0;y<k.length;y++)if("close"!=k[y].getAttribute("id"))STRUQ.ObjectFactory.getObject(k[y].getAttribute("type"),
k[y],u);else var E=STRUQ.ObjectFactory.getObject(k[y].getAttribute("type"),k[y],q);E&&STRUQ.Utils.addEventListener(E.el,"click",h,!0);STRUQ.Utils.addEventListener(q,"touchstart",d,!1);STRUQ.Utils.addEventListener(q,"touchend",d,!1);STRUQ.Utils.addEventListener(q,"touchmove",d,!1)}else STRUQ.Utils.addEventListener(q,"mousemove",c),STRUQ.Utils.addEventListener(q,"mouseout",h);this.el=q;this.xmlNode=e;this.parent=z;this.parentEl=A;this.show=g;this.hide=h}})();
(function(){STRUQ.ObjectFactory=new function(){objects=[];STRUQ.elementToObject=function(a){for(var b=0;b<objects.length;b++)if(objects[b].el==a)return objects[b]};this.getObject=function(a,b,c,d){switch(a){case "background":return new STRUQ.Background(b,c,d);case "dynamic":return new STRUQ.Dynamic(b,c,d);case "nav":return new STRUQ.Nav(b,c,d);case "config":return new STRUQ.Config(b,c,d);case "creative":return new STRUQ.Creative(b,c,d);case "page":return new STRUQ.Page(b,c,d);case "item":return new STRUQ.Item(b,
c,d);case "div":return new STRUQ.Div(b,c,d);case "vector":if(null==b.getAttribute("id")||-1==b.getAttribute("id").indexOf("mask"))return new STRUQ.Vector(b,c,d);break;case "txt":return new STRUQ.Text(b,c,d);case "img":return new STRUQ.Image(b,c,d);case "zoom":return a=new STRUQ.Zoom(b,c,d),objects.push(a),a;case "countdown":return new STRUQ.Countdown(b,c,d);case "video":if(document.createElement("video").canPlayType&&""!=document.createElement("video").canPlayType("video/mp4"))return a=new STRUQ.Video(b,
c,d),objects.push(a),a;break;case "swipedialog":if(STRUQ.vo.isTouchDevice)return new STRUQ.SwipeDialog(b,c,d)}}}})();
(function(){STRUQ.MasterRenderer=new function(){function a(a){"object"==typeof a&&a.responseXML?(STRUQ.vo.xmlDoc=a.responseXML,e=a.responseXML.documentElement):(a="object"==typeof a&&a.responseText?STRUQ.Utils.stringToXML(a.responseText):STRUQ.Utils.stringToXML(a),STRUQ.vo.xmlDoc=a,e=a.documentElement);if(STRUQ.WDInterface&&1==STRUQ.WDInterface.is("setCountdown")&&STRUQ.WDInterface.getOpts("setCountdown")){a=STRUQ.WDInterface.getOpts("setCountdown");for(var c in a)STRUQ.Utils.getXMLNodeByAttr(e,"id",
"countdown").setAttribute(c,a[c]);delete a}if(STRUQ.WDInterface&&1==STRUQ.WDInterface.is("setVideo")&&STRUQ.WDInterface.getOpts("setVideo")){a=STRUQ.WDInterface.getOpts("setVideo");for(var d=STRUQ.Utils.getXMLNodeByAttr(e,"type","video",!0),f=0;f<d.length;f++)for(c in a)d[f].setAttribute(c,a[c]);delete a;delete d}if(STRUQ.WDInterface&&1==STRUQ.WDInterface.is("setTransition")&&STRUQ.WDInterface.getOpts("setTransition")){a=STRUQ.WDInterface.getOpts("setTransition");for(c in a)e.getElementsByTagName("transition")[0].setAttribute(c,
a[c]);delete a}if(STRUQ.WDInterface&&1==STRUQ.WDInterface.is("setInactive")&&STRUQ.WDInterface.getOpts("setInactive"))for(c in a=STRUQ.WDInterface.getOpts("setInactive"),a)STRUQ.Utils.getXMLNodeByAttr(e,"id","prod").setAttribute(c,a[c]);e.getAttribute("maxtime")&&0<e.getAttribute("maxtime").length&&(STRUQ.vo.maxTime=Number(e.getAttribute("maxtime")));if(0<e.getElementsByTagName("font").length){a=[];for(c=0;c<e.getElementsByTagName("font").length;c++)e.getElementsByTagName("font")[c].getAttribute("html")&&
a.push(e.getElementsByTagName("font")[c].getAttribute("html"));0<a.length?STRUQ.FontLoader.loadFonts(a,b):b("fonts loaded")}else b("no fonts to load");a=e.getElementsByTagName("creative");d=[];for(c=0;c<a.length;c++){if(f=a[c].getElementsByTagName("config")[0])if(f.getElementsByTagName("transition")[0])f.getElementsByTagName("transition")[0].getAttribute("type")&&STRUQ.Model.isValidTransition(f.getElementsByTagName("transition")[0].getAttribute("type"))||f.getElementsByTagName("transition")[0].setAttribute("type",
"horizontal");else{var g=STRUQ.vo.xmlDoc.createElement("transition");g.setAttribute("type","horizontal");f.appendChild(g)}f&&-1==d.indexOf(f.getElementsByTagName("transition")[0].getAttribute("type"))&&d.push(f.getElementsByTagName("transition")[0].getAttribute("type"))}0<d.length?STRUQ.TransitionLoader.loadTransitions(d,b):b("transitions loaded")}function b(){k++;if(k==STRUQ.vo.noComponents){m.hide();m=null;STRUQ.WDInterface&&STRUQ.WDInterface.setAdStatus("adLoaded",!0);STRUQ.ActivityMonitor.initialise(e.getElementsByTagName("config")[0].getElementsByTagName("event"));
"true"==e.getElementsByTagName("creative")[0].getAttribute("isfallback")&&(STRUQ.vo.isFallback=!0);h.xmlNode=e.getElementsByTagName("creative")[0];h=STRUQ.ObjectFactory.getObject("background",h.xmlNode);STRUQ.vo.isFallback||(STRUQ.MasterRenderer.dynamic=STRUQ.ObjectFactory.getObject("dynamic",e),f.xmlNode=STRUQ.Utils.getXMLNodeByAttr(e,"id","nav"),f=STRUQ.ObjectFactory.getObject("nav",f.xmlNode));STRUQ.MasterRenderer.config.xmlNode=e.getElementsByTagName("config")[0];STRUQ.MasterRenderer.config=STRUQ.ObjectFactory.getObject("config",
STRUQ.MasterRenderer.config.xmlNode,STRUQ.MasterRenderer.container);STRUQ.vo.isTouchDevice&&e.getElementsByTagName("swipedialog")[0]&&STRUQ.ObjectFactory.getObject("swipedialog",e.getElementsByTagName("swipedialog")[0],STRUQ.MasterRenderer.container);if(e.getAttribute("borderColor")||e.getAttribute("borderSize"))e.getAttribute("borderSize")&&(STRUQ.vo.borderDefaults.size=Number(e.getAttribute("borderSize"))||"1"),e.getAttribute("borderColor")&&(STRUQ.vo.borderDefaults.color="#"+STRUQ.Utils.correctColor(e.getAttribute("borderColor"))),
e.getAttribute("borderAlpha")&&(STRUQ.vo.borderDefaults.alpha=Number(e.getAttribute("borderAlpha")));var a=document.createElement("div");a.id="topBorder";a.className="wslAdBorderClass";a.type="vector";a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.width=STRUQ.vo.adWidth+"px";a.style.height=STRUQ.vo.borderDefaults.size+"px";a.style.backgroundColor=STRUQ.vo.borderDefaults.color;a.style.zIndex=9999;STRUQ.MasterRenderer.container.appendChild(a);a=document.createElement("div");
a.id="rightBorder";a.className="wslAdBorderClass";a.type="vector";a.style.position="absolute";a.style.left=STRUQ.vo.adWidth-STRUQ.vo.borderDefaults.size+"px";a.style.top="0px";a.style.width=STRUQ.vo.borderDefaults.size+"px";a.style.height=STRUQ.vo.adHeight+"px";a.style.backgroundColor=STRUQ.vo.borderDefaults.color;a.style.zIndex=9999;STRUQ.MasterRenderer.container.appendChild(a);a=document.createElement("div");a.id="bottomBorder";a.className="wslAdBorderClass";a.type="vector";a.style.position="absolute";
a.style.left="0px";a.style.top=STRUQ.vo.adHeight-STRUQ.vo.borderDefaults.size+"px";a.style.width=STRUQ.vo.adWidth+"px";a.style.height=STRUQ.vo.borderDefaults.size+"px";a.style.backgroundColor=STRUQ.vo.borderDefaults.color;a.style.zIndex=9999;STRUQ.MasterRenderer.container.appendChild(a);a=document.createElement("div");a.id="leftBorder";a.className="wslAdBorderClass";a.type="vector";a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.width=STRUQ.vo.borderDefaults.size+"px";a.style.height=
STRUQ.vo.adHeight+"px";a.style.backgroundColor=STRUQ.vo.borderDefaults.color;a.style.zIndex=9999;STRUQ.MasterRenderer.container.appendChild(a)}}function c(a){"mouseover"==a.type&&"active"!=STRUQ.vo.state?(STRUQ.vo.state="active",STRUQ.MessageCenter.publish(STRUQ.MessageCenter.ACTIVE)):"mouseout"!=a.type||"inactive"==STRUQ.vo.state||a.relatedTarget!=document.getElementsByTagName("body")[0]&&a.relatedTarget!=document.getElementsByTagName("html")[0]&&null!=a.relatedTarget||(STRUQ.vo.state="inactive",
STRUQ.MessageCenter.publish(STRUQ.MessageCenter.INACTIVE))}function d(){STRUQ.vo.elapsedTime<STRUQ.vo.maxTime?STRUQ.vo.elapsedTime++:(clearInterval(p),STRUQ.MessageCenter.publish(STRUQ.MessageCenter.STOP_ANIMATION),e.getAttribute("endFrame")&&STRUQ.MessageCenter.publish(STRUQ.MessageCenter.NAV_TO,{itemPos:Number(e.getAttribute("endFrame"))-1}))}var g,h={},f={},m,e,p,k=0;this.config={};this.dynamic=void 0;this.init=function(b){g=document.getElementById("struqAdPlaceHolder");STRUQ.MasterRenderer.container=
g;STRUQ.vo.adWidth=g.style.width.split("px")[0];STRUQ.vo.adHeight=g.style.height.split("px")[0];document.getElementsByTagName("html")[0].style.width=STRUQ.vo.adWidth;document.getElementsByTagName("html")[0].style.height=STRUQ.vo.adHeight;document.body.style.margin=0;document.body.style.padding=0;document.body.scroll="no";var e=document.createElement("style");e.type="text/css";e.innerHTML="body:hover .creativeHover {pointer-events: none;} body:hover .elementHover {pointer-events: auto;}";document.getElementsByTagName("head")[0].appendChild(e);
p=setInterval(d,1E3);STRUQ.vo.isTouchDevice="ontouchstart"in window;if(-1<navigator.userAgent.indexOf("Opera Mobi")||-1<navigator.userAgent.indexOf("Opera Tablet"))STRUQ.vo.isOperaMini=!0;STRUQ.vo.urlTarget=STRUQ.vo.isOperaMini?"_top":"_blank";STRUQ.vo.events.click=STRUQ.vo.isTouchDevice?"touchend":"click";STRUQ.vo.events.mouseup=STRUQ.vo.isTouchDevice?"touchend":"mouseup";STRUQ.vo.events.mousedown=STRUQ.vo.isTouchDevice?"touchstart":"mousedown";STRUQ.vo.isTouchDevice||(STRUQ.Utils.addEventListener(g,
"mouseover",c),STRUQ.Utils.addEventListener(g,"mouseout",c));m=new STRUQ.Preloader(g);m.show();if(document.getElementById("xmlByteArray")&&0<document.getElementById("xmlByteArray").innerHTML.length&&"%%inlineAdPressContent%%"!=document.getElementById("xmlByteArray").innerHTML)b=STRUQ.HTMLHelper.getText(document.getElementById("xmlByteArray")),b=b.split("$").join("+"),b=window.atob(b),b=JSInflate.inflate(b),a(b);else if(STRUQ.xmlString)a(STRUQ.xmlString);else if(document.getElementById("previewFlashVars")&&
0<document.getElementById("previewFlashVars").innerHTML.length)a(STRUQ.HTMLHelper.getText(document.getElementById("previewFlashVars")));else if(-1==b.search("replaceCallback")){var f=STRUQ.Utils.request(b);f.onload=function(){a(f)};f.onerror=function(a){console.log("error on main XML load")};f.send()}else b=b.replace("replaceCallback","STRUQ.MasterRenderer.readXML"),e=document.createElement("script"),e.src=b,document.getElementsByTagName("body")[0].appendChild(e)};this.readXML=a}})();