var te_clr1_45220ef9_d660_458f_8ad3_21490138ea80_bi={aid:"moxie_verizon01",pid:"moxie01",cid:"9317865",width:120,height:240,icBaseUrl:"http://choices-or.truste.com/caic?",optoutLink:"http://preferences.truste.com?pid=moxie01&aid=moxie_verizon01&cid=9317865&w=120&h=240",sid:"_LBsidLB_"};
var TECA={interstitial:'  <div id="te-clr1-45220ef9-d660-458f-8ad3-21490138ea80-itl" style="position: absolute; margin: 0 auto; width:240px; height:220px; border: 1px solid #ccc; display:block; background:#FFF; overflow:hidden; padding:0; font-size:12px; font-family: arial,helvetica,clean,sans-serif; text-align:left; z-index:1001;">\n    <div class="closeTag" style="float:right; padding:5px"><a style="cursor:pointer; color:#456d88; text-decoration:none; " alt="close" onclick="javascript:self.close()"/>[close]</a></div> \n    <div class="mainRolloverSection" style="padding:5px 15px"> \n      <a onclick="truste.ca.interstitial_click(\'001\', te_clr1_45220ef9_d660_458f_8ad3_21490138ea80_bi )" href="http://www22.verizon.com/home/verizonglobalhome/ghp_landing.aspx" target="_blank"><img src="http://choices.truste.com/get?name=verizonlogo.png" alt="ad choices" class="advertiserLogo"/></a> \n      <br /> \n      <p style="padding:0 0 5px;><b><a style="color:#456d88; text-decoration:none;" href="http://www22.verizon.com/home/verizonglobalhome/ghp_landing.aspx" target="_blank">Verizon</a> cares about your privacy.</b> \n            <a style="color:#456d88; text-decoration:none;" href="{PartnerLink}" target="_blank">{PartnerName}</a> delivered this personalized ad based on your interests. \n             This is a placeholder for custom text.\n      </p> \n      <div style="padding-bottom:5px; ">\n        <a style="color:#456d88; text-decoration:none;" onclick="truste.ca.interstitial_click(\'005\', te_clr1_45220ef9_d660_458f_8ad3_21490138ea80_bi )" href="http://preferences.truste.com?pid=moxie01&aid=moxie_verizon01&cid=9317865&w=120&h=240" target="_blank"><b>Set Your Ad Preferences &raquo;</b></a><br /> \n        <a style="color:#456d88; text-decoration:none;" onclick="truste.ca.interstitial_click(\'002\', te_clr1_45220ef9_d660_458f_8ad3_21490138ea80_bi )" href="http://www22.verizon.com/privacy/" target="_blank"><b>Verizon Privacy Policy &raquo;</b></a><br /> \n      </div> \n    </div> \n    <div style="padding:5px 15px; height:100%; background:#efefef"> \n      <h2 style="font-weight:bold;font-size:12px;">AdChoices by <a style="color:#456d88; text-decoration:none;" href="http://www.truste.com" target="_blank"><img style="vertical-align:middle; border:none; width:70px;" src="http://choices.truste.com/get?name=TRUSTe_logo.png" /></a></h2>\n    </div> \n  </div> \n\n',c:"te-6ff3",initialize:function(){if(truste.ca2.bindMap!="undefined"||truste.ca2.bindMap){var c=truste.ca2.bindMap[this.c];
var b=truste.ca2.cidToInt[c.pid+c.aid+this.c];if(b){b["120x240"]=[this.interstitial,[240,220]]}else{truste.ca2.cidToInt[c.pid+c.aid+this.c]={"120x240":[this.interstitial,[240,220]]}
}var a=truste.ca2.target[c.pid+c.aid+this.c];if(a){a["120x240"]="pop"}else{truste.ca2.target[c.pid+c.aid+this.c]={"120x240":"pop"}
}c.plc="tr";if(!(c.plc=="tr"||c.plc=="tl"||c.plc=="br"||c.plc=="bl")){c.plc="tr"}c.ox=0;c.oy=0;c.iplc="rel";
c.backgroundColor="white";c.cam="3";c.opacity=0.8;c.icon="http://choices.truste.com/assets/forward_i.png";c.icon_cam="http://choices.truste.com/assets/admarker.png";
c.zindex="100002";c.optoutLink="http://preferences.truste.com?pid=moxie01&aid=moxie_verizon01&cid=9317865&w=120&h=240";
c.iconText="&nbsp;AdChoices";c.iconSpanId=this.c+"-icon";c.containerId=this.c;if(window.location.protocol=="https:"){c.noticeBaseUrl=c.noticeBaseUrl.replace("http:","https:");
c.irBaseUrl=c.irBaseUrl.replace("http:","https:");c.icon=c.icon.replace("http:","https:");c.icon_cam=c.icon_cam.replace("http:","https:");
c.icon_cam_daa=c.icon_cam_daa.replace("http:","https:");c.icon_cam_mo=c.icon_cam_mo.replace("http:","https:")
}}}};TECA.initialize();