(function(a){a.__adroll=a.__adroll||{exp:5E4,eexp:720,pv:1E11*Math.random(),__adc:"__ar_v4",_nad:0,_lce:null,_broken:!1,_loaded:!1,_url:2E3,_r:{},_kwl:300,_logs:[],_secure:function(){return"https:"===this._protocol()},_head:function(){return(a.document.getElementsByTagName("head")||[null])[0]||(a.document.getElementsByTagName("body")||[null])[0]||a.document.getElementsByTagName("script")[0].parentNode},_protocol:function(){return a.document.location.protocol},_native:function(){try{return"http"!==
this._protocol().slice(0,4)}catch(b){return!0}},_has_email:function(){return"undefined"!==typeof a.adroll_email&&"username@example.com"!==a.adroll_email},_has_user_identifier:function(){return"undefined"!==typeof a.adroll_user_identifier&&"example_user_id"!==a.adroll_user_identifier},_srv:function(b){return(this._native()||this._has_email()?"https:":"")+"//d.adroll.com"+("undefined"===typeof b?"":b)},_cdn:function(b){b="undefined"===typeof b?"":b;return this._secure()?"https://s.adroll.com"+b:"http://a.adroll.com"+
b},is_email_valid:function(b){return/[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?/.test(b)},md5:function(b){function c(b,a){var c=(b&65535)+(a&65535);return(b>>16)+(a>>16)+(c>>16)<<16|c&65535}function d(b,a,d,e,f,g){a=c(c(a,b),c(e,g));return c(a<<f|a>>>32-f,d)}function e(b,a,c,e,f,g,k){return d(a&c|~a&e,b,a,f,g,k)}function k(b,a,c,e,f,g,k){return d(a&e|c&~e,b,a,f,g,k)}function l(b,a,c,e,f,g,k){return d(c^(a|~e),
b,a,f,g,k)}function p(b,a){var h=b[0],j=b[1],f=b[2],g=b[3],h=e(h,j,f,g,a[0],7,-680876936),g=e(g,h,j,f,a[1],12,-389564586),f=e(f,g,h,j,a[2],17,606105819),j=e(j,f,g,h,a[3],22,-1044525330),h=e(h,j,f,g,a[4],7,-176418897),g=e(g,h,j,f,a[5],12,1200080426),f=e(f,g,h,j,a[6],17,-1473231341),j=e(j,f,g,h,a[7],22,-45705983),h=e(h,j,f,g,a[8],7,1770035416),g=e(g,h,j,f,a[9],12,-1958414417),f=e(f,g,h,j,a[10],17,-42063),j=e(j,f,g,h,a[11],22,-1990404162),h=e(h,j,f,g,a[12],7,1804603682),g=e(g,h,j,f,a[13],12,-40341101),
f=e(f,g,h,j,a[14],17,-1502002290),j=e(j,f,g,h,a[15],22,1236535329),h=k(h,j,f,g,a[1],5,-165796510),g=k(g,h,j,f,a[6],9,-1069501632),f=k(f,g,h,j,a[11],14,643717713),j=k(j,f,g,h,a[0],20,-373897302),h=k(h,j,f,g,a[5],5,-701558691),g=k(g,h,j,f,a[10],9,38016083),f=k(f,g,h,j,a[15],14,-660478335),j=k(j,f,g,h,a[4],20,-405537848),h=k(h,j,f,g,a[9],5,568446438),g=k(g,h,j,f,a[14],9,-1019803690),f=k(f,g,h,j,a[3],14,-187363961),j=k(j,f,g,h,a[8],20,1163531501),h=k(h,j,f,g,a[13],5,-1444681467),g=k(g,h,j,f,a[2],9,-51403784),
f=k(f,g,h,j,a[7],14,1735328473),j=k(j,f,g,h,a[12],20,-1926607734),h=d(j^f^g,h,j,a[5],4,-378558),g=d(h^j^f,g,h,a[8],11,-2022574463),f=d(g^h^j,f,g,a[11],16,1839030562),j=d(f^g^h,j,f,a[14],23,-35309556),h=d(j^f^g,h,j,a[1],4,-1530992060),g=d(h^j^f,g,h,a[4],11,1272893353),f=d(g^h^j,f,g,a[7],16,-155497632),j=d(f^g^h,j,f,a[10],23,-1094730640),h=d(j^f^g,h,j,a[13],4,681279174),g=d(h^j^f,g,h,a[0],11,-358537222),f=d(g^h^j,f,g,a[3],16,-722521979),j=d(f^g^h,j,f,a[6],23,76029189),h=d(j^f^g,h,j,a[9],4,-640364487),
g=d(h^j^f,g,h,a[12],11,-421815835),f=d(g^h^j,f,g,a[15],16,530742520),j=d(f^g^h,j,f,a[2],23,-995338651),h=l(h,j,f,g,a[0],6,-198630844),g=l(g,h,j,f,a[7],10,1126891415),f=l(f,g,h,j,a[14],15,-1416354905),j=l(j,f,g,h,a[5],21,-57434055),h=l(h,j,f,g,a[12],6,1700485571),g=l(g,h,j,f,a[3],10,-1894986606),f=l(f,g,h,j,a[10],15,-1051523),j=l(j,f,g,h,a[1],21,-2054922799),h=l(h,j,f,g,a[8],6,1873313359),g=l(g,h,j,f,a[15],10,-30611744),f=l(f,g,h,j,a[6],15,-1560198380),j=l(j,f,g,h,a[13],21,1309151649),h=l(h,j,f,g,
a[4],6,-145523070),g=l(g,h,j,f,a[11],10,-1120210379),f=l(f,g,h,j,a[2],15,718787259),j=l(j,f,g,h,a[9],21,-343485551);b[0]=c(h,b[0]);b[1]=c(j,b[1]);b[2]=c(f,b[2]);b[3]=c(g,b[3])}var v="0123456789abcdef".split(""),q=b;/[\x80-\xFF]/.test(q)&&(q=a.unescape(encodeURI(q)));var n=q.length;b=[1732584193,-271733879,-1732584194,271733878];var m;for(m=64;m<=q.length;m+=64){for(var r=b,u=q.substring(m-64,m),s=[],t=void 0,t=0;64>t;t+=4)s[t>>2]=u.charCodeAt(t)+(u.charCodeAt(t+1)<<8)+(u.charCodeAt(t+2)<<16)+(u.charCodeAt(t+
3)<<24);p(r,s)}q=q.substring(m-64);r=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];for(m=0;m<q.length;m++)r[m>>2]|=q.charCodeAt(m)<<(m%4<<3);r[m>>2]|=128<<(m%4<<3);if(55<m){p(b,r);for(m=0;16>m;m++)r[m]=0}r[14]=8*n;p(b,r);for(q=0;q<b.length;q++){n=b;m=q;r=b[q];u="";for(s=0;4>s;s++)u+=v[r>>8*s+4&15]+v[r>>8*s&15];n[m]=u}return b.join("")},log:function(a){this._logs.push(a)},read_log:function(a){return this._logs.join(a?"\n":"<br>\n")},cookieEnabled:function(b){if(a.adroll_ext_network||a.adroll_optout||this._broken)return!1;
if(2<=this._nad||b)return this._lce;this.set("_te_","1");return"1"===this.get("_te_")?(this.del("_te_"),0<this._nad&&!this.get(this.__adc)?this._lce=!1:this._lce=!0):this._lce=!1},parseUri:function(a){a=/^(?:(?![^:@]+:[^:@\/]*@)([^:\/?#.]+):)?(?:\/\/)?((?:(([^:@]*):?([^:@]*))?@)?([^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/.exec(a);for(var c={},d=14,e="source protocol authority userInfo user password host port relative path directory file query anchor".split(" ");d--;)c[e[d]]=
a[d]||"";c.queryKey={};c[e[12]].replace(/(?:^|&)([^&=]*)=?([^&]*)/g,function(a,b,d){b&&(c.queryKey[b]=d)});return c},get_keywords:function(){try{var b=a.document.referrer||"";if(!b)return"";var c=this.parseUri(b);return-1!==c.host.indexOf("www.google.")?c.queryKey.q.substring(0,this._kwl):-1!==c.host.indexOf("bing.com")?c.queryKey.q.substring(0,this._kwl):""}catch(d){return""}},get:function(b){var c=a.document.cookie;if(null===c)return this._broken=!0,null;var d;0>c.indexOf(b+"=")?c=null:(b=c.indexOf(b+
"=")+b.length+1,d=c.indexOf(";",b),-1===d&&(d=c.length),c=c.substring(b,d),c=""===c?null:a.unescape(c));return c},set:function(b,c,d){var e;!d||"number"!==typeof d?d="":(e=new Date,e.setTime(e.getTime()+36E5*d),d=e.toGMTString(),d="; expires="+d);e="; domain="+a.location.hostname;c=a.escape(c);a.document.cookie=b+"="+c+d+"; path=/"+e},del:function(a){this.set(a,"",-8760)},generate_link:function(){return""},get_base_url:function(b,c,d,e,k,l){b=b+"/"+c+"/"+d+(e?"/"+e:"")+(k?"/"+k:"");var p="";this.cookieEnabled(!1)?
(p=a.escape(this.get_eids()),b+="?pv="+this.pv+"&cookie="+p):b+="?no-cookies=1&pv="+this.pv;l&&(b+="&"+l.join("&"));if(b.length>this._url){this.del(this.__adc);if(b.length-p.length>this._url)return"#";this.log("Url was too big, shrinking it");return this.get_url(c,d,e,k,l)}this.log("Generated url: "+b);return b},get_url:function(a,c,d,e,k){var l=!d?this._srv("/r"):this._srv("/c");return this.get_base_url(l,a,c,d,e,k)},get_eids:function(){if(a.adroll_ext_network||a.adroll_optout)return"";try{for(var b=
this.get(this.__adc),c=b?b.split("|"):"",b=[],d=c.length-1;0<=d;d--)if(c[d]){var e=c[d].split(":");b.push([e[0],e[2]].join(":"))}return b.join("|")}catch(k){return this.del(this.__adc),""}},get_date:function(a){var c=new Date;a&&c.setTime(c.getTime()+36E5*a);a=""+c.getUTCFullYear();var d=c.getUTCMonth(),d=10<=d?d:"0"+d,c=c.getUTCDate();return[a,d,10<=c?c:"0"+c].join("")},normalize_url:function(a){return a.toLowerCase()},check_cookie:function(b,c){if(a.adroll_ext_network||a.adroll_optout)return"";
for(var d=b.split("|"),e=d.length-1;0<=e;e--)if(d[e]){var k=d[e].split(":");c===k[0]&&(k[2]=""+(parseInt(k[2])+1),d[e]=k.join(":"))}return d.join("|")},handle:function(a){var c=this.get(this.__adc)||"";-1!==c.indexOf(a)?this.set(this.__adc,this.check_cookie(c,a),this.exp):(a=[c,[a,this.get_date(this.eexp),"1"].join(":")].join("|"),this.set(this.__adc,a,this.exp))},expire_old:function(){if(!a.adroll_ext_network&&!a.adroll_optout){for(var b=this.get_date(),c=this.get(this.__adc),c=c?c.split("|"):[""],
d=[],e=c.length-1;0<=e;e--)c[e]&&c[e].split(":")[1]>b&&d.push(c[e]);this.set(this.__adc,d.join("|"),this.exp)}},render_win_notification:function(b){if(b.adroll_cpm_macro&&b.adroll_win_notif){var c=new a.Image,d=this._secure()?"https://":"http://";c.src=d+b.adroll_win_notif+b.adroll_cpm_macro;c.setAttribute("width","1");c.setAttribute("height","1");c.setAttribute("border","0");this._head().appendChild(c)}},render_ad_code:function(b,c,d,e){e="undefined"===typeof e?null:e;if("undefined"===typeof this._r[c]||
e){var k=["width="+a.adroll_width,"height="+a.adroll_height,"x=0","y=0"];if(d)this.log("Rendering test ad "+d+" in space "+c),k.push("test_ad="+d),b=this.get_url(b,c,null,"ad",k);else if(e){this.log("Rendering adgroup "+e);d=this.macro_values();var l=this.macro_url_params(d,!1,!1,!1,!1);k.push(l);this.render_win_notification(d);b=this.get_url(b,c,e,null,k)}else this.log("Rendering ad space "+c),b=this.get_url(b,c,null,"ad",k);this.expire_old();a.document.write('<script src="'+b+'">\x3c/script>');
this._nad+=1;this._r[c]=1}},endswith:function(a,c){return-1!==a.indexOf(c,a.length-c.length)},macro_values:function(){a.adroll_cpm_macro="undefined"===typeof a.adroll_cpm_macro?null:a.adroll_cpm_macro;a.adroll_url_macro="undefined"===typeof a.adroll_url_macro?null:a.adroll_url_macro;a.adroll_c_macro="undefined"===typeof a.adroll_c_macro?null:a.adroll_c_macro;a.adroll_subnetwork="undefined"===typeof a.adroll_subnetwork?null:a.adroll_subnetwork;a.adroll_ad_payload="undefined"===typeof a.adroll_ad_payload?
null:a.adroll_ad_payload;a.adroll_win_notif="undefined"===typeof a.adroll_win_notif?null:a.adroll_win_notif;var b={r:/^\$\{.*\}$/i,g:/^%%.*%%$/i,b:/^\[.*\]$/i,x:/^\$\{.*\}$/i,t:/INSERTCLICKTRACKER/}[a.adroll_ext_network],b="undefined"===typeof b?/CANNOT_MATCH_THIS/:b,c={};a.adroll_cpm_macro&&!b.test(a.adroll_cpm_macro)&&(c.adroll_cpm_macro=a.adroll_cpm_macro);a.adroll_url_macro&&!b.test(a.adroll_url_macro)&&(c.adroll_url_macro=a.adroll_url_macro);a.adroll_c_macro&&!b.test(a.adroll_c_macro)&&(c.adroll_c_macro=
a.adroll_c_macro);a.adroll_subnetwork&&!b.test(a.adroll_subnetwork)&&(c.adroll_subnetwork=a.adroll_subnetwork);a.adroll_ad_payload&&!b.test(a.adroll_ad_payload)&&(c.adroll_ad_payload=a.adroll_ad_payload);a.adroll_win_notif&&!b.test(a.adroll_win_notif)&&(c.adroll_win_notif=a.adroll_win_notif);return c},format_macros:function(a,c,d,e){return this.macro_url_params(this.macro_values(),a,c,d,e)},macro_url_params:function(b,c,d,e,k){k="undefined"===typeof k?!1:k;var l=e?a.escape:function(a){return a},p=
b.adroll_cpm_macro,v=b.adroll_url_macro,q=d?b.adroll_c_macro:null,n=[],m=c?this.parseUri(c):null,m=m?this.endswith(m.path,".tp"):!1;!m&&k&&n.push(["desturl",""]);q&&0===q.indexOf("http")?(k=l,"g"===a.adroll_ext_network&&(k=e?function(a){return a}:a.unescape),n.push(["clickurl",k(q)])):m&&k&&n.push(["clickurl",""]);a.adroll_ext_network&&n.push(["adroll_network",a.adroll_ext_network]);p&&n.push(["cpm",p]);b.adroll_subnetwork&&n.push(["adroll_subnetwork",b.adroll_subnetwork]);b.adroll_ad_payload&&n.push(["adroll_ad_payload",
b.adroll_ad_payload]);v&&(b=this.parseUri(a.unescape(v)),n.push(["site_url",l("http://"+b.host)]),d&&(n.push(["adroll_width",l(a.adroll_width)]),n.push(["adroll_height",l(a.adroll_height)])));this.log("Macros found "+this.serialize(n));return c?this.buildurl(c,n):this.serialize(n)},view:function(b){var c=new a.Image;c.src=this._srv("/view/"+b);c.setAttribute("width","1");c.setAttribute("height","1");c.setAttribute("border","0");this._head().appendChild(c)},serialize:function(a){if(a.length){for(var c=
[],d=a.length-1;0<=d;d--)c.push(a[d].join("="));return c.join("&")}return""},buildurl:function(a,c){var d=this.serialize(c),e=a.indexOf("?");return!d?a:e===a.length-1?a+d:-1!==e?"&"===a[a.length-1]?a+d:a+"&"+d:a+"?"+d},set_cookie:function(){},reset:function(){a.adroll_c_id=null;a.adroll_url_macro="";a.adroll_c_macro="";a.adroll_cpm_macro="";a.adroll_ext_network=null;a.adroll_subnetwork=null;a.adroll_ad_payload=null;a.adroll_win_notif=null},addLoadEvent:function(b){if("undefined"!==typeof a.__adroll_loaded&&
a.__adroll_loaded||"undefined"!==typeof a._adroll_ie&&a._adroll_ie||/msie/i.test(a.navigator.userAgent))return b();if(/WebKit/i.test(a.navigator.userAgent)){var c=a.setInterval(function(){/loaded|complete/.test(a.document.readyState)&&a.clearInterval(c);b()},10);return null}var d=a.onload;a.onload=function(){b();d&&d()}},render_pixel_code:function(b,c){this.expire_old();var d=this._srv("/pixel"),e=a.document.createElement("script");e.setAttribute("async","true");e.type="text/javascript";var k=a.__adroll.get_keywords();
this.addLoadEvent(function(){var l=[];try{l.push("adroll_s_ref="+a.escape(a.document.referrer))}catch(p){}try{l.push("keyw="+a.escape(k))}catch(v){}try{"undefined"!==typeof a.adroll_segments&&l.push("name="+a.escape(a.adroll_segments.toLowerCase()))}catch(q){}try{var n=a.__adroll.get_conversion_value();n.conv_value&&l.push("conv_value="+n.conv_value);n.currency&&l.push("adroll_currency="+n.currency)}catch(m){}try{if(a.__adroll._has_email()){var r=a.adroll_email,r=r.replace(/^\s\s*/,"").replace(/\s\s*$/,
"");l.push("email="+a.escape(r));a.__adroll.is_email_valid(r)?l.push("hashed_email="+a.__adroll.md5(r.toLowerCase())):(l.push("data_error=email"),l.push("data_error_message=invalid_format"))}}catch(u){}try{if(a.__adroll._has_user_identifier()){var s=a.adroll_user_identifier,s=s.replace(/^\s\s*/,"").replace(/\s\s*$/,"");l.push("user_identifier="+a.__adroll.md5(s))}}catch(t){}try{var w=a.__adroll.external_data_to_qs(!0);w&&l.push(w)}catch(x){}l=a.__adroll.get_base_url(d,b,c,null,"",l);e.src=l;a.__adroll._head().appendChild(e)})},
record_user:function(b){var c="adroll_conversion_value adroll_conversion_value_in_dollars adroll_segments adroll_email adroll_user_identifier adroll_currency".split(" "),d,e;b=b||{};var k={adroll_email:!0,adroll_user_identifier:!0};for(d=0;d<c.length;d++){try{delete a[c[d]]}catch(l){}if(c[d]in b){a[c[d]]=c[d]in k?a.escape(b[c[d]]):b[c[d]];try{delete b[c[d]]}catch(p){}}}try{delete a.adroll_custom_data}catch(v){}for(e in b)if(b.hasOwnProperty(e)){a.adroll_custom_data=b;break}this.render_pixel_code(a.adroll_adv_id,
a.adroll_pix_id)},normalize_var:function(b,c){if(!b)return"";b=b.toString().substr(0,this._kwl).replace(/,/gi,".");c&&(b=a.escape(b));return b},get_conversion_value:function(){a.adroll_currency="undefined"===typeof a.adroll_currency?null:a.adroll_currency;a.adroll_conversion_value="undefined"===typeof a.adroll_conversion_value?null:a.adroll_conversion_value;a.adroll_conversion_value_in_dollars="undefined"===typeof a.adroll_conversion_value_in_dollars?null:a.adroll_conversion_value_in_dollars;return a.adroll_conversion_value?
{conv_value:""+a.adroll_conversion_value,currency:a.adroll_currency}:a.adroll_conversion_value_in_dollars?{conv_value:""+parseInt(100*a.adroll_conversion_value_in_dollars),currency:"USC"}:null},get_external_data:function(){if("undefined"!==typeof a.adroll_custom_data){var b=a.adroll_custom_data,c={},d;for(d in b)b.hasOwnProperty(d)&&(c[d.toLowerCase()]=b[d]);return c}return null},_gurl:function(){var b=a.location;return this.normalize_url(b.pathname+b.search)},extract_pid:function(a,c,d){function e(a){return a?
(a=RegExp(a,"gi"),!!a.exec(l)):null}a||(a={});var k=c=null,l=this._gurl(),p=this.get_external_data();p&&p.product_id&&(k=p.product_id);p&&p.product_group&&(c=p.product_group);if(!k&&a.regexp_group&&!("string"===a.regexp_group&&a.regexp_group instanceof String)&&"html"===a.regexp_group.scheme){if(e(a.blacklist_regexp)||!0!==e(a.regexp))return"";k=this.get_product_id_from_dom(a.regexp_group)}else if(!k){if(e(a.blacklist_regexp))return"";k=this.get_product_id_from_url(l,a.regexp,a.regexp_group)}!c&&
a.product_group_group&&!("string"===a.product_group_group&&a.product_group_group instanceof String)&&"html"===a.product_group_group.scheme?c=this.get_product_id_from_dom(a.product_group_group):c||a.product_group_regexp&&(c=this.get_product_id_from_url(l,a.product_group_regexp,a.product_group_group));if(!k)return null;c||(c="");a={product_id:k,product_group:c,product_action:p?p.product_action:null};d&&d(a);return a},get_pid:function(b){this.extract_pid(b,"adroll",function(b){if(b){var d=b.product_id,
e=b.product_group;b=b.product_action;var k="";if(d instanceof Array)for(var k="?",l=0;l<d.length;l++)k+="adroll_product_id="+this.normalize_var((d[l]+"").toLowerCase(),!0),l<d.length-1&&(k+="&");else k="?adroll_product_id="+this.normalize_var((d+"").toLowerCase(),!0);e=e?"&adroll_product_group="+this.normalize_var((e+"").toLowerCase(),!0):"";b=b?"&adroll_product_action="+this.normalize_var(b+"").toLowerCase():"";d=this._srv("/p/"+a.adroll_adv_id+"/"+k+e+b);e=a.document.createElement("img");e.src=
d;e.height=e.width=1;e.border=0;this._head().appendChild(e)}}.bind(this))},get_product_id_from_dom:function(b){var c=null,d;b.path&&(a.jQuery?(d=a.jQuery(b.path),d.length&&(d=d.eq(0),c="text"===b.attribute?d.text():d.attr(b.attribute))):a.Prototype&&a.$$?(d=a.$$(b.path),d.length&&(d=d[0],c="text"===b.attribute?d.innerText&&!a.opera?d.innerText:d.innerHTML.stripScripts().unescapeHTML().replace(/[\n\r\s]+/g," "):d.readAttribute(b.attribute))):a.YUI?(d=a.YUI().use("node"),d.one&&(d=d.one(b.path),c=null,
d&&(c="text"===b.attribute?d.get("text"):d.getAttribute(b.attribute)))):a.$$&&(d=a.$$(b.path),d.length&&(d=d[0],c="text"===b.attribute?d.get("text"):d.getProperty(b.attribute))));if(c&&(c=c.replace(/^\s\s*/,"").replace(/\s\s*$/,""),b.regular_expression&&b.regular_expression_replace))if(d=RegExp(b.regular_expression,"gi"),c=d.exec(c),null!==c){b=b.regular_expression_replace;for(d=0;d<c.length;d++)b=b.replace(RegExp("\\\\"+d,"gi"),c[d]||"");c=b}else c="";return c},get_product_id_from_url:function(a,
c,d){var e=null;try{e=parseInt(d)}catch(k){}return null!==e&&(!isNaN(e)&&c)&&(a=RegExp(c,"gi").exec(a),null!==a&&e in a)?a[e]:null},external_data_to_qs:function(b){var c=[],d=this.get_external_data();if(!d)return null;for(var e in d)d.hasOwnProperty(e)&&c.push(this.normalize_var(a.escape(""+e)+"="+a.escape(""+d[e])));c=c.join("&");b&&(c=a.escape(c));return"adroll_external_data="+c},replace_external_data:function(b){var c=this.get_external_data(),d=this.get_conversion_value(),e=null,k;if(c)for(k in c)c.hasOwnProperty(k)&&
(e=RegExp("\\["+k+"\\]","gi"),b=b.replace(e,c[k]),e=RegExp("\\["+k+"_ESC\\]","gi"),b=b.replace(e,a.escape(c[k])));if(d)for(k in d)d.hasOwnProperty(k)&&(e=RegExp("\\["+k+"\\]","gi"),b=b.replace(e,d[k]),e=RegExp("\\["+k+"_ESC\\]","gi"),b=b.replace(e,a.escape(d[k])));return b},set_pixel_cookie:function(b,c,d){a.adroll_optout||(this.handle(b),this.handle(c),this.handle(d),this.pixel_loaded())},add_pixel_load_callback:function(b){this._loaded?b():a.adroll_callbacks.push(b)},pixel_loaded:function(){this._loaded=
!0;for(var b=0;b<a.adroll_callbacks.length;b++)a.adroll_callbacks[b]()}};a.adroll_optout=!1;a.adroll_a_eid="undefined"===typeof a.adroll_ad_eid?null:a.adroll_ad_eid;a.adroll_c_eid="undefined"===typeof a.adroll_c_id?null:a.adroll_c_id;a.adroll_ext_network="undefined"===typeof a.adroll_ext_network?null:a.adroll_ext_network;a.adroll_subnetwork="undefined"===typeof a.adroll_subnetwork?null:a.adroll_subnetwork;a.adroll_ad_payload="undefined"===typeof a.adroll_ad_payload?null:a.adroll_ad_payload;a.adroll_win_notif=
"undefined"===typeof a.adroll_win_notif?null:a.adroll_win_notif;a.adroll_c_eid&&!a.adroll_ext_network&&(a.adroll_ext_network="g");a.__adroll.render_ad_code(a.adroll_s_id,a.adroll_a_id,a.adroll_a_eid,a.adroll_c_eid)})(window);
